### PR TITLE
Primarily an update to the flag values and definitions

### PR DESCRIPTION
**Pull request by shefty**
Define the 3 supported completion modes.
Simple update to flag values.
Remove FI_CANCEL flag
Add FI_RMA_EVENT capability flag to indicate if remote RMA operations can generate local events
Add new fields to domain_attr to report how many EPs may be attached to a shared context.

### CODE REVIEW

**Comment by shefty** [comment]
@shantonu @jithinjosepkl @j-xiong  - this PR includes minor updates to the PSM and sockets provider

**Comment by j-xiong** [comment]
psm changes look fine.

**Comment by shantonu** [comment]
sockets looks fine as well.

**Comment by jithinjosepkl** [comment]
:+1:

**Pull request merged**
