### PR TITLE
Replaced vnic_rq descriptor ring with usd native ring in rdm_post_recv

### PR DESCRIPTION
**Pull request by xuywang**
This fixed the segment fault in fi_rdm_pingpong with usnic provider

Signed-off-by: Xuyang Wang <xuywang@cisco.com>

### CODE REVIEW

**Comment by goodell** [comment]
This looks good to me and seems to work fine in my testing, so I'm going to pull it.

This made me curious about `fi_ud_pingpong`, which now appears to be broken but for a reason besides the vnic_rq/usd issue.  I'm still investigating.

**Comment by xuywang** [comment]
What is symptom? It seems to work from me.

I just used only –S all option though.

Xuyang

**Comment by goodell** [comment]
When I run it, it fails to `fi_av_insert` (with a confusing error message) and then SEGVs.  I bisected it back to the fabtests PR that refactored the tests to use a common infrastructure (ofiwg/fabtests#139 and ofiwg/fabtests#140 -- ofiwg/fabtests@7cf45e3 works but ofiwg/fabtests@1a31686 does not), but I don't see the bug yet.

This happens with and without a `-s` option.

**Comment by goodell** [comment]
It's caused by an extra `&` in a part of the API that is untyped.  I'll submit a fix soon.

**Pull request merged**
