### PR TITLE
prov/verbs: Return back registration of the QP, because it's dealloca…

### PR DESCRIPTION
**Pull request by shefty**
…ted in case of PASSIVE when route resolved

Signed-off-by: Dmitry Gladkov <dmitry.gladkov@intel.com>

### CODE REVIEW

**Comment by gladkovdmitry17** [comment]
@shefty these changes haven't been included to v1.5.x yet.
I mean we need to cherry-pick [this](https://github.com/ofiwg/libfabric/commit/b8c17b4ca6e841da786dc25d6f4296274252ad82)

**Comment by shefty** [comment]
Oops - I just picked your original patch and pushed it.  Didn't even notice that it ends up blank!

**Comment by gladkovdmitry17** [comment]
> Oops - I just picked your original patch and pushed it. Didn't even notice that it ends up blank!

Should I prepare the PR?

**Comment by shefty** [comment]
If you can that would be great.  Otherwise, I'll try again until I can get the right commit.

**Comment by gladkovdmitry17** [comment]
> If you can that would be great

Yes, I'll do that.

**Pull request closed without merging**
