### PR TITLE
prov/verbs: Apply remaining comments from the PR #3268

### PR DESCRIPTION
**Pull request by gladkovdmitry17**
This patch applies comments from the PR #3268 + some code cleanups for the new added functions

Signed-off-by: Dmitry Gladkov <dmitry.gladkov@intel.com>

### CODE REVIEW

**Comment by gladkovdmitry17** [comment]
@a-ilango @shefty Please, check this, if there is time for that.
Thanks!

Please, don't merge this into the master branch, because it's not tested and I want to avoid excessive looping through `fi_info` lists

**Comment by gladkovdmitry17** [comment]
Please, ignore my previous mention regarding merging this. Now this PR is in a good shape.

**Comment by shefty** [comment]
@a-ilango - please merge once this looks okay to you

**Comment by a-ilango** [comment]
Thanks. This looks good. Just one question. Is it not possible to use rdma_create_ep for UD QPs? I see the filtering of fi_info list based on device is done only for MSG and RDM endpoints.

**Comment by shefty** [comment]
rdma_create_ep should be usable for UD QPs.  I'm not sure if it's been tested -- it's been too long since I've worked with the code at this point.

**Comment by gladkovdmitry17** [comment]
> Is it not possible to use rdma_create_ep for UD QPs?

Yes, it's possible.
But verbs/DGRAM uses own address format (not sockaddr-compliant as it is done for both MSG and RDM ep types).
My goal was to not use any CM for verbs/DGRAM to avoid scalability issues just in case. If the you disagree with this, we could have a discussion and re-implement (there are no any complexities for that). 
Btw, @shefty Does rdma_cm library establish any out-of-band connections for the UD QPs? Seems we are free to specify type of CM - TCP,UDP (if I'm not mistaken)

**Comment by shefty** [comment]
The rdma_cm does not establish connections for UD QPs.  It does support the native IB service address resolution protocol, however.

**Comment by a-ilango** [comment]
> The rdma_cm does not establish connections for UD QPs.  It does support the native IB service address resolution protocol, however.

In this case we might be able to use rdmacm for just fi_getinfo to discover the devices. That could avoid separate code paths for MSG, RDM vs DGRAM.

@gladkovdmitry17 please use whichever method you think is best.

**Comment by gladkovdmitry17** [comment]
> The rdma_cm does not establish connections for UD QPs.  It does support the native IB service address resolution protocol, however.

How do you think it would be nice to switch verbs/DGRAM to rdma_cm? The fact that we would have a IB address resolution seems is good enough to plan this work for the future.

**Comment by gladkovdmitry17** [comment]
> @gladkovdmitry17 please use whichever method you think is best.

Seems, rdma_cm looks good to me. But let's plan this work for the future and I'll implement this. I'll probably have timeframe for that in December.

**Pull request merged**
