### PR TITLE
v1.8: backport usNIC fixes from master

### PR DESCRIPTION
**Pull request by jsquyres**
Just in case there's another v1.8.x release.

There is no need to do a v1.8.x release because of this PR.

### CODE REVIEW

**Comment by jsquyres** [comment]
@shefty Are you still accepting PRs on the v1.8.x branch?  (per the main description, this is not urgent / there's no need to trigger a new v1.8.x release -- I just made this PR in case there is ever another v1.8.x release)

**Comment by shefty** [comment]
Yes, I think we should cherry pick from 1.9 into 1.8.x and create a 1.8.2 release within the next couple of months.

**Comment by jsquyres** [comment]
@shefty Is the Intel CI failure correct?  Or should it be ignored / merge anyway?

**Comment by shefty** [comment]
CI failure is an OMPI segfault over DL sockets provider running stress tests.

**Comment by jsquyres** [comment]
Ok.  That CI failure sounds unrelated to this PR.

**Pull request merged**
