### PR TITLE
[v1.19.x] prov/shm: Only poll IPC list when ROCR IPC is enabled

### PR DESCRIPTION
**Pull request by a-szegel**

### CODE REVIEW

**Comment by sunkuamzn** [comment]
Do you not need to cherry-pick the other commit? https://github.com/ofiwg/libfabric/pull/9185/commits/f8ee8b0eafb4519de1d97bb817f51d53cfeefbe6

**Comment by shefty** [comment]
needs missing commit included in PR

**Comment by a-szegel** [comment]
re-pushed.

**Comment by shefty** [comment]
Can you rebase and repush?

**Comment by shefty** [comment]
Commits have been picked manually into PR #9221, so that I could include them in rc2.  Leaving this PR open for tracking, but it will be discarded once rc2 updates are merged.

**Pull request closed without merging**
