### PR TITLE
add fi_rx_size_left/fi_tx_size_left functions

### LINKED ISSUE #480: Define 'send_credit' scheme
There's been too much discussion on this to write the details.  Adding issue to ensure that the man pages and implementation are updated with the final solution.

### PR DESCRIPTION
**Pull request by goodell**
Per Reese's proposal here: http://lists.openfabrics.org/pipermail/ofiwg/2014-December/000477.html

This PR also adds support in the usnic provider.

A corresponding fabtests PR is imminent.

fixes #480 

@rfaucett please review

### CODE REVIEW

**Comment by goodell** [comment]
After discussion with @jsquyres, he will review instead (though everyone's comments are welcome on this interface addition).

**Comment by goodell** [comment]
Updated the PR in response to some of Jeff's offline comments.  Particularly, I dropped the accidental double-documentation of the new functions in the man pages and fixed the per-function man "links".

**Comment by jsquyres** [comment]
This PR has been around for several days and no one has commented on it, so I guess it's safe to merge.

**Comment by shefty** [comment]
I haven't had time to review any comments over the past week because I've been consumed with tons of other activities.

**Pull request merged**
