### PR TITLE
prov/rxm: Enable dynamic receive buffer by default (again - just to watch CI fail...)

### PR DESCRIPTION
**Pull request by shefty**
Dynamic receive buffering eliminates receive side data
copies when layering over tcp.  Enable it by default, but
keep the environment variable to force it off (as a work-
around in case errors are discovered).

Signed-off-by: Sean Hefty <sean.hefty@intel.com>

### CODE REVIEW

**Comment by shefty** [comment]
This is the AWS failure, which only showed up on Ubuntu.  The same test on alinux passed.
```
timeout 30m /opt/amazon/openmpi/bin/mpirun -x 'FI_PROVIDER=tcp;ofi_rxm' -x NCCL_ALGO=ring --hostfile /home/ubuntu/hosts -x FI_EFA_ENABLE_SHM_TRANSFER=0 -x FI_EFA_TX_MIN_CREDITS=64 -x RDMAV_FORK_SAFE=1 -x NCCL_DEBUG=INFO -n 24 -N 8 --mca btl tcp,self --mca btl_tcp_if_exclude lo,docker0 --mca pml '^cm' --bind-to none /home/ubuntu/nccl-tests/build/all_reduce_perf -b 8 -e 1G -f 2 -g 1 -c 1 -n 100
```
For some reason removing the receive side bounce buffers results in this failure.  I've analyzed the NCCL plug-in, and there isn't anything that stands out there as suspect.  All other CI is passing.  I'm struggling to find a reason why this test continues to fail in this environment, and it appears to do so near the start of the test.  My best guess is that somehow the initial address exchange is corrupt.

@rwespetal @wzamazon -- Is it possible to get debug help from AWS for this?

**Comment by wzamazon** [comment]
bot:aws:retest

**Comment by wzamazon** [comment]
Could be a hardware issue of nvidia GPU, which we have seen recently. I started retest.

**Comment by shefty** [comment]
The failure has been consistent for ubuntu NCCL multi-node.  I just can't figure out why that environment has issues.

**Pull request closed without merging**
