### PR TITLE
V1.1.x

### PR DESCRIPTION
**Pull request by shefty**
Cherry pick bug fixes from the mainline tree for the 1.1.1 release.  This is the list of psm, verbs, and usnic provider fixes.  Please review that I didn't miss any.

The socket provider patches still needs to be picked.  (I hit a conflict on the first attempt and need to run off to a meeting.)

### CODE REVIEW

**Comment by shefty** [comment]
Updated to include sockets provider commits

**Comment by bturrubiates** [comment]
Could the `usNIC` provider also get c86de1c, 8cc4693, 3274d20, and 57c4a65? 

Unfortunately many of these bugs were only found after the fabtests refactoring.

**Comment by shefty** [comment]
Added additional usnic commits.

**Comment by bturrubiates** [comment]
Thanks!

**Comment by shefty** [comment]
I've double checked the lists that everyone gave me, and everything looks to be there.  Merging this.  Additional updates can be pulled through separate requests.

**Pull request merged**
