### PR TITLE
psm2: fix CPU detection

### PR DESCRIPTION
**Pull request by hhoffstaette**
This should address #4355

### CODE REVIEW

**Comment by hhoffstaette** [comment]
@j-xiong I wasn't sure whether the uname output is supposed to be standardized; can you give me an example fotr output of `uname -p` that differs from mine? As far as I can tell this has nothing to do with Gentoo, it's plain uname from coreutils (8.30 in my case). But then I just looked at [Wikipedia](https://en.wikipedia.org/wiki/Uname) and it seems ot be a mess..or that page is wrong.

**Comment by hhoffstaette** [comment]
@j-xiong I just looked at the official uname source in [coreutils](http://git.savannah.gnu.org/cgit/coreutils.git/tree/src/uname.c) and the -p flag looks like
a system-specific mess. I guess we weill have to trust your judgement. :)

**Comment by j-xiong** [comment]
@hhoffstaette Yes the output is not standardized. Per my past experience the output of "uname -m" and "uname -p" are the same on RHEL and SLES. I didn't try it on Gentoo before, but you mentioned that "uname -m" worked better there. I am not sure how it will behave on other systems.

**Comment by j-xiong** [comment]
Fixes #4355

**Pull request merged**
