### PR TITLE
v1.21.1

### PR DESCRIPTION
**Pull request by aingerson**

### CODE REVIEW

**Comment by j-xiong** [comment]
bot:aws:retest

**Comment by shijin-aws** [comment]
AWS CI failed for shm 

```
024-07-24 00:29:58,885 - INFO - utils - Executing command: /home/ec2-user/PortaFiducia/build/libraries/libfabric/pr10214-debug-mempoison-asan/install/libfabric/bin/fi_info -p shm
2024-07-24 00:29:59,302 - ERROR - utils - Command /home/ec2-user/PortaFiducia/build/libraries/libfabric/pr10214-debug-mempoison-asan/install/libfabric/bin/fi_info -p shm failed with error:

=================================================================
==8062==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 784 byte(s) in 2 object(s) allocated from:
    #0 0x7f9d03a24753 in __interceptor_calloc (/lib64/libasan.so.4+0xd8753)
    #1 0x7f9cfccc5b83  (<unknown module>)
    #2 0x7f9cfcd267f7  (<unknown module>)
    #3 0x7f9cfe688519  (<unknown module>)
    #4 0x7f9cfe68b8df  (<unknown module>)
    #5 0x7f9d0273cc25 in __pthread_once_slow (/lib64/libpthread.so.0+0xec25)

Direct leak of 112 byte(s) in 2 object(s) allocated from:
    #0 0x7f9d03a24753 in __interceptor_calloc (/lib64/libasan.so.4+0xd8753)
    #1 0x7f9cfccc1156  (<unknown module>)
    #2 0x7f9cfcd267e4  (<unknown module>)
    #3 0x7f9cfe688519  (<unknown module>)
    #4 0x7f9cfe68b8df  (<unknown module>)
    #5 0x7f9d0273cc25 in __pthread_once_slow (/lib64/libpthread.so.0+0xec25)

Direct leak of 112 byte(s) in 2 object(s) allocated from:
    #0 0x7f9d03a24753 in __interceptor_calloc (/lib64/libasan.so.4+0xd8753)
    #1 0x7f9cfccc10ce  (<unknown module>)
    #2 0x7f9cfcd267e4  (<unknown module>)
    #3 0x7f9cfe688519  (<unknown module>)
    #4 0x7f9cfe68b8df  (<unknown module>)
    #5 0x7f9d0273cc25 in __pthread_once_slow (/lib64/libpthread.so.0+0xec25)

Direct leak of 112 byte(s) in 2 object(s) allocated from:
    #0 0x7f9d03a24753 in __interceptor_calloc (/lib64/libasan.so.4+0xd8753)
    #1 0x7f9cfccc1026  (<unknown module>)
    #2 0x7f9cfcd267e4  (<unknown module>)
    #3 0x7f9cfe688519  (<unknown module>)
    #4 0x7f9cfe68b8df  (<unknown module>)
    #5 0x7f9d0273cc25 in __pthread_once_slow (/lib64/libpthread.so.0+0xec25)

SUMMARY: AddressSanitizer: 1120 byte(s) leaked in 8 allocation(s).

and output:
```

**Comment by shijin-aws** [comment]
We recently enabled ASAN in the CI, I will temporarily disable it for non-efa provider check. But we may want to fix it @aingerson

**Comment by shijin-aws** [comment]
bot:aws:retest

**Comment by shijin-aws** [comment]
AWS CI failure is not related. safe to ignore

**Comment by shijin-aws** [comment]
bot:aws:retest

**Pull request merged**
