### PR TITLE
prov/efa: Add tracepoint for poll cq ope

### PR DESCRIPTION
**Pull request by shijin-aws**
This tracepoint records the event when a polled cqe has an associated op entry already, which is expected for send, RMA, and zero-copy receive operations.

### CODE REVIEW

**Review by jiaxiyan — APPROVED** [review]

**Comment by shijin-aws** [comment]
bot:aws:retest

**Comment by shijin-aws** [comment]
bot:aws:retest

**Comment by shijin-aws** [comment]
bot:aws:retest

**Comment by shijin-aws** [comment]
bot:aws:retest

**Pull request merged**
