### PR TITLE
Re-enable logging on psm, verbs, and usnic providers

### PR DESCRIPTION
**Pull request by shefty**

### CODE REVIEW

**Comment by shefty** [comment]
Verbs provider was merged because of a build issue.  PSM and USNIC providers need review.
@j-xiong @jsquyres @goodell  - please let me know if the changes to the providers look okay.

**Comment by shefty** [comment]
Fixes #811 #809

**Comment by j-xiong** [comment]
psm changes look ok.

**Comment by shefty** [comment]
Updates to the verbs and PSM providers have been merged.  Closing this and opening a new PR for the usnic provider.

**Pull request closed without merging**
