### PR TITLE
Initialize param_list to avoid crashing in library destructor

### LINKED ISSUE #1119: libfabric apps crash during fi_param_fini if process forked
If an application forks a process that never runs the fi_* calls, `fi_param_fini` will crash while attempting to delete parameters. 

```
Program terminated with signal 11, Segmentation fault.
#0  0x000000000044994b in dlist_remove (item=0x0) at ./include/fi_list.h:89
89		item->prev->next = item->next;
(gdb) where
#0  0x000000000044994b in dlist_remove (item=0x0) at ./include/fi_list.h:89
#1  0x0000000000449925 in fi_param_fini () at src/var.c:307
#2  0x0000000000447f25 in fi_fini () at src/fabric.c:414
#3  0x000000000040469a in __do_global_dtors_aux ()
#4  0x0000000000489f2d in _real_fini ()
#5  0x0000000000489f22 in _fini ()
#6  0x00007fe719434874 in _dl_fini () from /lib64/ld-linux-x86-64.so.2
#7  0x00007fe718251665 in __run_exit_handlers () from /lib64/libc.so.6
#8  0x00007fe7182516b5 in exit () from /lib64/libc.so.6
#9  0x00007fe71823ac3d in __libc_start_main () from /lib64/libc.so.6
#10 0x000000000040462d in _start () at ../sysdeps/x86_64/elf/start.S:113
```

@shefty @hppritcha

### PR DESCRIPTION
**Pull request by jswaro**
@shefty @hppritcha 

closes #1119 

Signed-off-by: James Swaro <jswaro@cray.com>

### CODE REVIEW

**Comment by jswaro** [comment]
closes ofi-cray/libfabric#258

**Comment by shantonu** [comment]
I was working on the same issue! This fixes the seg fault issue in Fabtests if I run a test with only -h option. Thanks!

**Comment by hppritcha** [comment]
:+1:

**Comment by shefty** [comment]
thanks

**Comment by bturrubiates** [comment]
This does fix the issue, but I'm not sure this is the correct fix. There is already a `dlist_init` function. `fi_fini` shouldn't be attempting to cleanup resources allocated in `fi_ini` if `fi_ini` hasn't even been called yet.

**Comment by jswaro** [comment]
I'd leave the changes in, but put this in fabric.c

````
static void __attribute__((destructor)) fi_fini(void)
{
	struct fi_prov *prov;

+    if (!init)
+        return;

	while (prov_head) {
```

The static initializer doesn't hurt and we can use the macros in more locations than just this.

**Comment by bturrubiates** [comment]
Okay, that's fair.

**Comment by shefty** [comment]
Yes, that change looks good,

**Pull request merged**
