### PR TITLE
v1.9.0rc1

### PR DESCRIPTION
**Pull request by shefty**
Will coordinate actual rc1 release with maintainers.  There are updates to most providers to adjust for the updated version number.

### CODE REVIEW

**Comment by shefty** [comment]
Deferring rc1 until PRs #5377 #5376 #5374 #5365 are merged, with a target of Oct 18.  Add other PRs as needed.

**Comment by shefty** [comment]
Forcing CI in preparation of real rc1 package.  Target is end of day Oct 22

**Comment by shefty** [comment]
aws:bot:retest

**Comment by jswaro** [comment]
@shefty  I've added the Cray CI to the build, just to test the current state of 1.9.0rc1. However, if it fails, I wouldn't be concerned right away. We recently updated the testbed and there are changes to the pipeline definition that probably aren't part of this tag.

**Comment by shefty** [comment]
Updated for reals this time... merged all outstanding needed updates

**Pull request merged**
