### PR TITLE
prov/efa : two RMA related patches

### PR DESCRIPTION
**Pull request by wzamazon**
@rajachan Please review!

### CODE REVIEW

**Comment by shefty** [comment]
If you rebase over master, the tcp failures should be gone now.

**Comment by shefty** [comment]
Thanks - I'd like to get this reviewed and merged today, if possible.  I'll create rc2 immediately after, so I can hand it off to an eval team for testing over the week-end.

**Comment by rajachan** [comment]
> Thanks - I'd like to get this reviewed and merged today, if possible. I'll create rc2 immediately after, so I can hand it off to an eval team for testing over the week-end.

We noticed @a-ilango's patch in f37bfea is preventing Intel MPI from picking up the EFA provider, we will take a look at that.

**Comment by shefty** [comment]
You likely need to set the supported op_flags.  See the changes to shm provider as an example:

https://github.com/ofiwg/libfabric/commit/8fc0aa7ca39b9a76ac4a99a37c6b9f9a8f7f850d

**Pull request merged**
