### PR TITLE
Fixes from the Debian package

### PR DESCRIPTION
**Pull request by bdrung**
This pull request contains the patches that I applied to libfabric 1.5.2-1 in Debian.

### CODE REVIEW

**Comment by lanl-ompi** [comment]
Can one of the admins verify this patch?

**Comment by shefty** [comment]
@hppritcha - PLEASE kill the bot spam.  Why does it even post these comments?

**Comment by shefty** [comment]
@bdrung - Thanks for the fixes.  The man pages are automatically generated from the markdown files.  Any chance you could update those instead?  :)  If not, I will manually apply your changes to those files in place of the man page updates.

**Comment by bdrung** [comment]
Good point. Let me have a look an the markdown files later.

**Comment by hppritcha** [comment]
@shefty I added all the ofi libfabric groups to the whitelist.  Do you want to allow anyone to be able to trigger CI?

**Comment by hppritcha** [comment]
add to whitelist

**Comment by shefty** [comment]
@hppritcha - I don't understand what he whitelist is.  I would like all PRs to trigger CI, with appropriate feedback.  I just don't want the CI posting useless comments to every PR.  I don't understand why these comments are being posted.

**Comment by bdrung** [comment]
@shefty Done. The commits modify the markdown files instead of the generated man pages.

**Comment by shefty** [comment]
thanks

**Pull request merged**
