### PR TITLE
fabtests/configure.ac: Correct --with-libfabric doc string

### LINKED ISSUE #7411: fabtests: configure --help text needs updating
The README says to run configure with:
```
--with-libfabric=<directory>
```
which works correctly, but:
```
--with-libfabric <directory>
```
fails.  That surprised me because I was expecting it to work.  For instance, this configure in fabtests works as expected:
 ```
./configure --with-libfabric=/shared/libfabric/install/ --prefix ~/fabtests_install
```

And the `./configure --help` seems to also be missing the required equals sign:
``` 
  --with-libfabric        Use non-default libfabric location - default NO
  --with-cuda=DIR         Provide path to where the CUDA development and
                          runtime libraries are installed.
```

### PR DESCRIPTION
**Pull request by a-szegel**
Fixes #7411

### CODE REVIEW

**Comment by shefty** [comment]
Thanks!

**Review by wzamazon — CHANGES_REQUESTED** [review]
Can you update the commit messages to include more details?

the title line needs to start with the part this commit changes. In your case, probality "fabtests/configure.ac", etc.

In the commit message body, specify what the problem was, and how this commit addressed it.

**Comment by aingerson** [comment]
Please also rebase. It looks like you have two commits, one that undoes a change in upstream and one that redoes it with your help message

**Comment by wzamazon** [comment]
@shefty can you add @a-szegel to the ofiwg github organization?

**Review by wzamazon — APPROVED** [review]

**Review by aingerson — APPROVED** [review]

**Pull request merged**
