### PR TITLE
prov/shm: move all ofi_shm/util_shm code to prov/shm

### PR DESCRIPTION
**Pull request by a-szegel**
No one else uses the shm specific code which is specific to the provider and should be in the shm provider folder.

### CODE REVIEW

**Comment by a-szegel** [comment]
This is Alexia's patch that I cherry picked into main... I approve this.

**Comment by aingerson** [comment]
Is the git rm of the old files missing? I don't see it. (That was my bad sorry). I think this should just show up as a rename, not an addition

**Comment by a-szegel** [comment]
I also did some greps and saw a few things were missed.

**Review by aingerson — APPROVED** [review]
That looks correct now! Thanks for fixing my mistake!

**Review by shefty — APPROVED** [review]

**Comment by a-szegel** [comment]
AWS CI error not related.

**Pull request merged**
