### PR TITLE
windows: Add two new configurations that build libfabric with efa provider for Windows

### PR DESCRIPTION
**Pull request by gurusrik**
This pull request enables building efa provider for Windows using two new configurations `Release-Efa-v142` and `Debug-Efa-v142`.  The pull request depends on another pull request: [7263](https://github.com/ofiwg/libfabric/pull/7263).  This pull request will fail to build till the  other one is merged.

The main reason for creating new configurations as opposed to using existing configurations is to let customers build efa provider for Windows without enabling it by default for every current user of libfabric.

### CODE REVIEW

**Comment by wzamazon** [comment]
The earlier CI failure is because this PR depends on https://github.com/ofiwg/libfabric/pull/7264.

Now that https://github.com/ofiwg/libfabric/pull/7264 was merged, this should pass

**Comment by gurusrik** [comment]
There is one failure with rma trigger test which has been unreliable in past builds, but all other builds have passed.  The failing configuration(Release-v140) is not related to the changes as no efa code is enabled for that configuration.

**Comment by wzamazon** [comment]
@shefty Would you mind take a look at this PR?

**Comment by wzamazon** [comment]
The continous-integration failure is because `fi_rma_trigger`, which has happened before, so should not be related to this PR.

**Review by wzamazon — APPROVED** [review]

**Comment by wzamazon** [comment]
Looks good to me. This PR add new configurations to `libfabric.sln`, thus should not impact existing CI.

**Comment by shefty** [comment]
Should these be separate commits, or merged into a single one?  Does this break git bisect?

**Comment by gurusrik** [comment]
I think these should stay separate commits given that they deal with separate areas of the project and failures can be addressed in the specific area.   I don't think keeping these as separate commits would break git bisect.  These commits are not tightly interdependent.  The only need here is for fourth(final) commit to go after the others.

Summarizing the commits here for convenience:

Commit1: Adds new configurations to sln and vcxproj files for libfabric (benign as it does not touch existing configurations)
Commit2: Adds new configurations to sln, vcxproj and Makefile for fabtests(benign as it does not touch existing configurations)
Commit3: Adds a copy step to powershell used by appveyor (this has low risk, but in theory the download could fail causing the CI build to fail - easy to find and fix, proven to be working in current validation run)
Commit4: Adds build configurations to Appveyor (this is the commit that enables the build with the new configurations in the CI)

**Pull request merged**
