### PR TITLE
src/hmem: extend pointer query functions

### PR DESCRIPTION
**Pull request by aingerson**

### CODE REVIEW

**Comment by j-xiong** [comment]
bot:aws:retest

**Comment by j-xiong** [comment]
It would be nice to have this included in 1.14, even if the hook provider itself can't make it (wish that can be include, too). @aingerson @shefty your opinions?

**Comment by shefty** [comment]
I'm not convinced this is ready, but it might be in time for v1.14.  I want to create an rc2 on Friday to pull in the recent fixes.

Extra overhead is being added to all is_addr_valid() checks in order to support the hooking provider.  It may be better to have a separate call, or restructure how the device is obtained to limit the performance impact.

**Comment by aingerson** [comment]
Well as far as I can tell, no one is actually using the is_addr_valid calls anyway so we're adding extra overhead to nothing :)
Alternative would be to only set the device/flags if provided ie
```
if (device)
    // do any extra overhead to set the device
```

**Comment by shefty** [comment]
Well, if nothing is actually calling the function, then there's no need to optimize.  :)

**Comment by j-xiong** [comment]
There is a single existing usage case inside  `ofi_get_hmem_iface()` where `device` and `flags` fields are not used. I think it makes sense to bypass the extra check when `device` is NULL.

**Comment by aingerson** [comment]
Fair enough. I'll update

**Review by j-xiong — APPROVED** [review]

**Comment by shefty** [comment]
Restarted CI -- Intel nodes are having technical difficulties.

**Pull request merged**
