### PR TITLE
usnic: Unify sendmsg and sendv into single function.

### PR DESCRIPTION
**Pull request by bturrubiates**
- Use a common base instead of having almost identical `sendmsg` and `sendv` implementations.
- Add support for `FI_INJECT` to `fi_sendv` implementation for `FI_EP_RDM`.

@jsquyres

### CODE REVIEW

**Comment by bturrubiates** [comment]
Need to split out some common functionality into a separate file. This can be pushed past 1.2rc2.

**Comment by shefty** [comment]
Is this PR good to go?

**Comment by jsquyres** [comment]
This PR will not be ready for 1.2rc2.

**Comment by bturrubiates** [comment]
@shefty 
The part of this PR that was for 1.2rc2 was submitted separately. Unfortunately this one might need more review so this will be for the 1.2 release proper.

**Comment by shefty** [comment]
Is this patch needed for 1.2?  If so, is it almost ready?

**Comment by bturrubiates** [comment]
It's not necessary, but would be nice if we could get it in. When is 1.2 expected to release? This is almost ready but it's pending some review and I need to do some further testing. I return tomorrow and I think some of the other Cisco folks are still on break.

**Comment by jsquyres** [comment]
@bturrubiates has done some testing on this PR, and something still isn't quite right.  This can easily slip to v1.3.

**Comment by bturrubiates** [comment]
This is still blocked due to #1747. Once that issue is resolved, this will be ready for merging.

**Comment by bturrubiates** [comment]
@goodell @jsquyres 

This is ready for review. The problems aren't in this code, they're in other code in the provider. We can get this merged in and I'll continue debugging to find the other problems.

**Comment by goodell** [comment]
:+1:

**Pull request merged**
