### PR TITLE
pytest/efa: unset strict mode for dgram pingpong test

### PR DESCRIPTION
**Pull request by wenduwan**
Increase timeout from 5s(default) to 30s

### CODE REVIEW

**Review by a-szegel — APPROVED** [review]

**Review by shijin-aws — CHANGES_REQUESTED** [review]
dgram pingpong is not reliable. We shouldn't fail if we got a ENODATA in cq read. Increasing the timeout is not the right fix.

**Comment by wenduwan** [comment]
I think @shijin-aws is correct. Please see update.

**Review by shijin-aws — APPROVED** [review]
thx

**Comment by wenduwan** [comment]
Strictly EFA change. Ready to merge @shijin-aws

**Pull request merged**
