### PR TITLE
prov/rxm: Revert HMEM changes to capability bits

### PR DESCRIPTION
**Pull request by shefty**
Disable FI_HMEM support from rxm by removing the capability bits.
This fixes a regression where rxm over verbs fails CI validation.

Signed-off-by: Sean Hefty <sean.hefty@intel.com>

### CODE REVIEW

**Comment by shefty** [comment]
We're seeing multiple CI failures since merging this PR.  Guessing on which change is responsible.

**Comment by shefty** [comment]
bot:aws:retest

**Comment by shefty** [comment]
I think the issue is that adding FI_HMEM as a cap isn't necessarily the problem.  It's that adding that results in adding a new FI_MR_HMEM mr_mode bit.  And that breaks the apps.

**Comment by iziemba** [comment]
The additional core provider FI_MR_HMEM requirement is only added if the if the user hints have requested FI_HMEM.

**Comment by shefty** [comment]
That's not the case if the app does not specify any hints, which is common.

**Comment by iziemba** [comment]
That is not what I am seeing. I have been using fi_info without parameters which should pass in NULL hints to fi_getinfo. Here is the output I see.

```
fi_info:
    caps: [ FI_MSG, FI_RMA, FI_TAGGED, FI_READ, FI_WRITE, FI_RECV, FI_SEND, FI_REMOTE_READ, FI_REMOTE_WRITE, FI_MULTI_RECV, FI_LOCAL_COMM, FI_REMOTE_COMM, FI_HMEM ]
    mode: [  ]
    addr_format: FI_SOCKADDR_IN
    src_addrlen: 16
    dest_addrlen: 0
    src_addr: fi_sockaddr_in://10.0.0.11:0
    dest_addr: (null)
    handle: (nil)
    fi_tx_attr:
        caps: [ FI_MSG, FI_RMA, FI_TAGGED, FI_READ, FI_WRITE, FI_SEND, FI_HMEM ]
        mode: [  ]
        op_flags: [  ]
        msg_order: [ FI_ORDER_RAR, FI_ORDER_RAW, FI_ORDER_RAS, FI_ORDER_WAW, FI_ORDER_WAS, FI_ORDER_SAW, FI_ORDER_SAS, FI_ORDER_RMA_RAR, FI_ORDER_RMA_RAW, FI_ORDER_RMA_WAW, FI_ORDER_ATOMIC_RAR, FI_ORDER_ATOMIC_RAW, FI_ORDER_ATOMIC_WAW ]
        comp_order: [ FI_ORDER_NONE ]
        inject_size: 16320
        size: 1024
        iov_limit: 4
        rma_iov_limit: 1
    fi_rx_attr:
        caps: [ FI_MSG, FI_RMA, FI_TAGGED, FI_RECV, FI_REMOTE_READ, FI_REMOTE_WRITE, FI_MULTI_RECV, FI_HMEM ]
        mode: [  ]
        op_flags: [  ]
        msg_order: [ FI_ORDER_RAR, FI_ORDER_RAW, FI_ORDER_RAS, FI_ORDER_WAW, FI_ORDER_WAS, FI_ORDER_SAW, FI_ORDER_SAS, FI_ORDER_RMA_RAR, FI_ORDER_RMA_RAW, FI_ORDER_RMA_WAW, FI_ORDER_ATOMIC_RAR, FI_ORDER_ATOMIC_RAW, FI_ORDER_ATOMIC_WAW ]
        comp_order: [ FI_ORDER_NONE ]
        total_buffered_recv: 0
        size: 1024
        iov_limit: 4
    fi_ep_attr:
        type: FI_EP_RDM
        protocol: FI_PROTO_RXM
        protocol_version: 1
        max_msg_size: 1073741824
        msg_prefix_size: 0
        max_order_raw_size: 1073741824
        max_order_war_size: 0
        max_order_waw_size: 1073741824
        mem_tag_format: 0xaaaaaaaaaaaaaaaa
        tx_ctx_cnt: 1
        rx_ctx_cnt: 1
        auth_key_size: 0
    fi_domain_attr:
        domain: 0x0
        name: mlx5_0
        threading: FI_THREAD_SAFE
        control_progress: FI_PROGRESS_AUTO
        data_progress: FI_PROGRESS_MANUAL
        resource_mgmt: FI_RM_ENABLED
        av_type: FI_AV_UNSPEC
        mr_mode: [ FI_MR_LOCAL, FI_MR_VIRT_ADDR, FI_MR_ALLOCATED, FI_MR_PROV_KEY ]
        mr_key_size: 4
        cq_data_size: 4
        cq_cnt: 65536
        ep_cnt: 32768
        tx_ctx_cnt: 1
        rx_ctx_cnt: 1
        max_ep_tx_ctx: 1
        max_ep_rx_ctx: 1
        max_ep_stx_ctx: 0
        max_ep_srx_ctx: 0
        cntr_cnt: 0
        mr_iov_limit: 1
    caps: [ FI_LOCAL_COMM, FI_REMOTE_COMM ]
    mode: [  ]
        auth_key_size: 0
        max_err_data: 0
        mr_cnt: 0
    fi_fabric_attr:
        name: IB-0xfe80000000000000
        prov_name: verbs;ofi_rxm
        prov_version: 112.0
        api_version: 1.12
```

Since master verbs provider does not support HMEM, it seems like the FI_HMEM cap should not have been applied to the RXM info.

**Comment by shefty** [comment]
Hmm, then I expect FI_MR_HMEM will be a problem somewhere down the line then.  The fi_av_test is failing consistently for us with any rxm + verbs provider (no data available).  Reading the test, I didn't notice anything that should result in failures.  My revert patch allows the test to pass, but I've updated the patch to simply fold in the FI_HMEM bit into the base cap bits.  That's probably still not what we want.  Does FI_HMEM being enabled have a negative impact on performance?

**Comment by iziemba** [comment]
I don't think having FI_HMEM set in RXM should negatively impact performance, but it is falsely advertising FI_HMEM support.

**Comment by shefty** [comment]
What do you mean falsely reporting FI_HMEM?  If it's not actually handling FI_HMEM, the revert patch might be the best option for now.  The current changes I have add FI_HMEM directly as a cap, which causes both tcp and verbs to fail.  But that also makes is easier for me to see what's wrong.

**Comment by iziemba** [comment]
It appears that FI_HMEM is always set in RXM even if the core provider does not support FI_HMEM. It seems like FI_HMEM should only be set if the core provider supports FI_HMEM.

I agree with reverting the patch.

**Comment by shefty** [comment]
This removes FI_HMEM capability from rxm.  There's an issue with having it that shows up with fi_av_test and fi_dom_test.  Those tests return ENODATA.  When we add it back, we need to ensure that doesn't re-occur.

**Pull request merged**
