### PR TITLE
Opx upstream for 1.17

### PR DESCRIPTION
**Pull request by charlesshereda**
OPX provider-specific updates. Included are:
prov/opx: prov/opx: Add fi_opx_tid.h to Makefile.include
prov/opx: Fix progress checks and default domain
prov/opx: Revert is_intranode simplification.
prov/opx: Don't inline handle_ud_ping function
prov/opx: Allow atomic fetch ops to use SDMA for sufficiently large counts.
prov/opx: Cleaned up FI_LOG_LEVEL=warn output
prov/opx: Cleaned up unused macros for FI_REMOTE_COMM and FI_LOCAL_COMM
prov/opx: Reset default progress to FI_PROGRESS_MANUAL
prov/opx: Fixed GCC 10 build error with Auto Progress
prov/opx: Add support for FI_PROGRESS_AUTO
prov/opx: Use max allowed packet size in SDMA path when expected TID is turned off.
prov/opx: Update Copyrights
prov/opx:  Expected receive (TID) rendezvous
prov/opx: RMA Read/Write operations over SDMA
prov/opx: Remove origin_rs from cts and dput packet header.
prov/opx: Fix for hang - unable to match inbound packets with receive context->src_addr (DAOS CART tests)
prov/opx: Use single IOV for bounce buffer in SDMA requests.
prov/opx: check for FI_MULTI_RECV with bitwise OR instead of AND
prov/opx: Fix for intermittent intra-node deadlock hang (DAOS CART tests)
prov/opx: Fix to RPC transport error failure (DAOS CART tests)
prov/opx: Fix for context->buf set to NULL
prov/opx: Fix bad asserts
prov/opx: Avoid RED/BLACK conflict with ofi_tree.h
prov/opx: Ensure atomicity of atomic ops
prov/opx: fi_opx_cq_poll_inline count and head check fix
prov/opx: Fix intermittent intra-node hang causing RPC timeouts (DAOS CART tests)

### CODE REVIEW

**Comment by shefty** [comment]
There's a problem with the signed-off-by line on 1 or more of the patches.

**Comment by charlesshereda** [comment]
Yeah, thanks Sean, working on it.

From: Sean Hefty ***@***.***>
Date: Wednesday, November 30, 2022 at 7:26 PM
To: ofiwg/libfabric ***@***.***>
Cc: Shereda, Charles ***@***.***>, Author ***@***.***>
Subject: Re: [ofiwg/libfabric] Opx upstream for 1.17 (PR #8292)

There's a problem with the signed-off-by line on 1 or more of the patches.

—
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fofiwg%2Flibfabric%2Fpull%2F8292%23issuecomment-1332935307&data=05%7C01%7Ccharles.shereda%40cornelisnetworks.com%7C10e5b6718737497d13e608dad332bba0%7C4dbdb7da74ee4b458747ef5ce5ebe68a%7C0%7C0%7C638054512113267773%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=EZOqw2uXDt00YIlGr%2F5p0hLvUnQEq5hBpNbDpgPtZbo%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FA2ZW2HYPGUF2WSWHAAHMSQLWK7WENANCNFSM6AAAAAASQGIYPM&data=05%7C01%7Ccharles.shereda%40cornelisnetworks.com%7C10e5b6718737497d13e608dad332bba0%7C4dbdb7da74ee4b458747ef5ce5ebe68a%7C0%7C0%7C638054512113267773%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=cxPhGZc3jZGh6pk4je18ZzbmtVqrsjM8KQeHf2BadM8%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

External recipient

**Comment by charlesshereda** [comment]
The Signed-off-by issues should at least be fixed.

**Comment by charlesshereda** [comment]
Not sure why that tid header isn't being found and build checks are failing, checking.

**Comment by j-xiong** [comment]
Build checks failed with missing file. Forgot to add `fi_opx_tid.h` to Makefile.include?

**Comment by charlesshereda** [comment]
Maybe that's it, or maybe I missed something - Checking with the team, may not have an answer until tomorrow.

**Comment by charlesshereda** [comment]
New push has a new commit with the corrected Makefile.include.

**Comment by shefty** [comment]
Note that this PR was against main.  You'll need a separate PR for the v1.17.x branch to pull into 1.17 release.

**Comment by charlesshereda** [comment]
ok, oops.

**Pull request merged**
