### PR TITLE
[v1.22.x] prov/efa: Handle recv cancel for zero copy recv

### PR DESCRIPTION
**Pull request by shijin-aws**
backport https://github.com/ofiwg/libfabric/pull/10215

### CODE REVIEW

**Comment by shijin-aws** [comment]
@j-xiong does this have to be merged by 5 pm?

**Review by wenduwan — APPROVED** [review]

**Comment by j-xiong** [comment]
@shijin-aws No. It's enough to have the PR is here. I can monitor the CI and get it merged before I create my updated version of #102111

**Comment by shijin-aws** [comment]
@j-xiong Awesome, thx!

**Comment by j-xiong** [comment]
@shijin-aws What is the AWS CI error about? the same "out of memory error" as we saw in #10216?

**Comment by shijin-aws** [comment]
Yeah, not sure why, anyway, we may need to reduce the message size in this test 

```
server_command: ssh -n -o StrictHostKeyChecking=no -o ConnectTimeout=30 -o BatchMode=yes 172.31.66.252 'timeout 1800 /bin/bash --login -c '"'"'FI_LOG_LEVEL=warn /home/ec2-user/PortaFiducia/build/libraries/libfabric/pr10218-debug/install/fabtests/bin/fi_unexpected_msg -e rdm -M 1024 -I 5 -v -S 1048576 -D cuda -i 0 -p shm -E=9228'"'"''

client_command: ssh -n -o StrictHostKeyChecking=no -o ConnectTimeout=30 -o BatchMode=yes 172.31.66.252 'timeout 1800 /bin/bash --login -c '"'"'FI_LOG_LEVEL=warn /home/ec2-user/PortaFiducia/build/libraries/libfabric/pr10218-debug/install/fabtests/bin/fi_unexpected_msg -e rdm -M 1024 -I 5 -v -S 1048576 -D cuda -i 0 -p shm -E=9228 172.31.66.252'"'"''
client_stdout:
[error] fabtests:common/hmem_cuda.c:305: cudaMalloc failed: cudaErrorMemoryAllocation out of memory
timeout: the monitored command dumped core

client returncode: 255
server_stdout:

server returncode: 124

```

**Comment by shijin-aws** [comment]
I opened a PR https://github.com/ofiwg/libfabric/pull/10219 to remove that 1M test, will see how it goes

**Comment by j-xiong** [comment]
bot:aws:retest

**Pull request merged**
