### PR TITLE
fabtests: Adding tests for SM2 Provider

### PR DESCRIPTION
**Pull request by a-szegel**
Creates a test directory and config files for SM2 provider. Included only passing tests for SM2 with its current limited functionality.  This is the first step in putting SM2 in AWS CI.  Will expand tests as SM2 functionality increases.

### CODE REVIEW

**Comment by a-szegel** [comment]
```
/fsx/PortaFiducia/build/libraries/libfabric/main/install/fabtests/bin/runfabtests.py --junit-xml /tmp/fabtests_phk058.xml -v -p /fsx/PortaFiducia/build/libraries/libfabric/main/install/fabtests/bin -N sm2 127.0.0.1 127.0.0.1
only efa provider support parallelized tests. Setting nworkers to 1 ....
cd /fsx/PortaFiducia/build/libraries/libfabric/main/install/fabtests/share/fabtests/pytest; pytest --provider=sm2 --server-id=127.0.0.1 --client-id=127.0.0.1 -v -rfE --tb=short -m 'ubertest_quick or short or unit or functional' --junit-xml /tmp/fabtests_phk058.xml --exclude-negative-tests --binpath=/fsx/PortaFiducia/build/libraries/libfabric/main/install/fabtests/bin --timeout=360 --ubertest-config-file=/fsx/PortaFiducia/build/libraries/libfabric/main/install/fabtests/share/fabtests/test_configs/sm2/quick.test sm2
================================================================================= test session starts =================================================================================
platform linux -- Python 3.7.16, pytest-7.2.2, pluggy-1.0.0 -- /home/ec2-user/env/bin/python3
cachedir: .pytest_cache
metadata: {'Python': '3.7.16', 'Platform': 'Linux-5.10.149-133.644.amzn2.x86_64-x86_64-with-glibc2.2.5', 'Packages': {'pytest': '7.2.2', 'pluggy': '1.0.0'}, 'Plugins': {'typeguard': '2.13.3', 'xdist': '3.2.0', 'metadata': '2.0.4', 'html': '3.2.0'}}
rootdir: /fsx/PortaFiducia/build/libraries/libfabric/main/install/fabtests/share/fabtests/pytest, configfile: pytest.ini
plugins: typeguard-2.13.3, xdist-3.2.0, metadata-2.0.4, html-3.2.0
collected 19 items / 5 deselected / 14 selected                                                                                                                                       

sm2/test_av.py::test_av_xfer[rdm] PASSED                                                                                                                                        [  7%]
sm2/test_av.py::test_av_xfer[dgram] SKIPPED (ENODATA)                                                                                                                           [ 14%]
sm2/test_cntr.py::test_cntr PASSED                                                                                                                                              [ 21%]
sm2/test_cq.py::test_cq PASSED                                                                                                                                                  [ 28%]
sm2/test_dom.py::test_dom PASSED                                                                                                                                                [ 35%]
sm2/test_eq.py::test_eq PASSED                                                                                                                                                  [ 42%]
sm2/test_mr.py::test_mr PASSED                                                                                                                                                  [ 50%]
sm2/test_rdm.py::test_rdm_bw_functional[transmit_complete] PASSED                                                                                                               [ 57%]
sm2/test_rdm.py::test_rdm[transmit_complete] PASSED                                                                                                                             [ 64%]
sm2/test_rdm.py::test_rdm_pingpong[transmit_complete-host_to_host-short] PASSED                                                                                                 [ 71%]
sm2/test_rdm.py::test_rdm_tagged_pingpong[transmit_complete-host_to_host-short] PASSED                                                                                          [ 78%]
sm2/test_rdm.py::test_rdm_tagged_bw[transmit_complete-host_to_host-short] PASSED                                                                                                [ 85%]
sm2/test_sighandler.py::test_sighandler PASSED                                                                                                                                  [ 92%]
sm2/test_ubertest.py::test_ubertest[quick] PASSED                                                                                                                               [100%]

-------------------------------------------------------------------- generated xml file: /tmp/fabtests_phk058.xml ---------------------------------------------------------------------
==================================================================== 13 passed, 1 skipped, 5 deselected in 31.07s =====================================================================
(
```

**Comment by shijin-aws** [comment]
what's the main difference between the sm2 and shm test suite?

**Comment by a-szegel** [comment]
sm2 doesn't have RMA, Atomics, Delivery Complete or HMEM.

**Review by shefty — APPROVED** [review]

**Comment by a-szegel** [comment]
@shefty is IMPI failure real?

**Comment by shijin-aws** [comment]
I do not think Intel CI every use pytest scripts in fabtests

**Comment by shefty** [comment]
Intel CI does not use the python scripts.  It also won't run sm2 tests currently.  CI failure was some verbs DAOS problem -- not sure of the reason, but guessing maybe a down CI node.

**Review by shijin-aws — APPROVED** [review]

**Pull request merged**
