### PR TITLE
configure: Fix ICC 17 compilation

### LINKED ISSUE #3995: compiler error with icc 17.0.4.196
I am writing to report another building problem of libfabric. Intel Compiler 17.0.4.196 Build 20170411 failed to build libfabric at the linking stage, regardless of the backend gcc versions of default 4.8.5 or 6.3.0 in the Red Hat Enterprise Linux Server release 7.3 system. Error messages follow,

```
../configure CC=icc CXX=icpc --enable-psm2 --disable-udp --disable-sockets --disable-rxm  --prefix=$NWCHEM_ROOT/deps


make -j 16 
<.....>
  CC       util/info.o
  CC       util/strerror.o
  CC       util/pingpong.o
  CCLD     libpsmx.la <http://libpsmx.la> 
  CCLD     libpsmx2.la <http://libpsmx2.la> 
  CCLD     src/libfabric.la <http://libfabric.la> 
  CCLD     util/fi_info
  CCLD     util/fi_strerror
  CCLD     util/fi_pingpong
src/.libs/libfabric.so: undefined reference to `__builtin_ia32_rdpmc'
src/.libs/libfabric.so: undefined reference to `__builtin_ia32_rdpmc'
src/.libs/libfabric.so: undefined reference to `__builtin_ia32_rdpmc'
make[1]: *** [util/fi_info] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [util/fi_strerror] Error 1
make[1]: *** [util/fi_pingpong] Error 1
make[1]: Leaving directory `/work1/home/u1/molpro/src/i17/nwchem-6.8.1.opt/libfabric/build'
make: *** [all] Error 2
```

### PR DESCRIPTION
**Pull request by gladkovdmitry17**
Fixes #3995 

Signed-off-by: Dmitry Gladkov <dmitry.gladkov@intel.com>

### CODE REVIEW

**Comment by jsquyres** [comment]
@gladkovdmitry17 Is the issue that icc 17 declares `__builtin_ia32_rdpmc` but does not define it?

Also, might want to update the AC_DEFINE_UNQUOTED comment (i.e., 3rd argument) to include that the symbol is actually defined, too.

**Comment by shefty** [comment]
I think that's the case @jsquyres.  The declaration check passes, but the report is that the compile fails during the link stage.

**Comment by shefty** [comment]
AppVeyor is frequently, but not always, failing on the fi_poll -t counter test.  Usually only 1 of the 6 windows runs hits the error.  We can ignore this for now.

**Comment by gladkovdmitry17** [comment]
@shefty @jsquyres Thanks!


> AppVeyor is frequently, but not always, failing on the fi_poll -t counter test. Usually only 1 of the 6 windows runs hits the error. We can ignore this for now.

Yes. Me and @RozanovAnatoliy are going to look into this.
I saw this failure from time to time, but it wasn't reproducible constantly (1 failure per month). But now I can see this for almost all PRs

**Pull request merged**
