### PR TITLE
travis: Added steps to build and run fabtests

### PR DESCRIPTION
**Pull request by shantonu**
- Added prefix to libfabric build
- Added steps to clone, build and run fabtests

Signed-off-by: Shantonu Hossain <shantonu.hossain@intel.com>

### CODE REVIEW

**Comment by shantonu** [comment]
@shefty, I've cleaned up based on your fabtests's <code>.travis.yaml </code>. Will do a separate PR for building verbs provider once this PR is merged.

**Comment by shefty** [comment]
Hmmm... looking at the travis log details, I don't see where fabtests actually ran.  I'm not sure why.  Maybe make test causes travis to exit at that point?  (Wild guessing here.)

**Comment by shantonu** [comment]
There is no after-install step in Travis. It has before-install, install, before-script, script and after script. Should I put the "fabtests step" in the script?

**Comment by shantonu** [comment]
Added under script, and it works fine.

**Comment by shefty** [comment]
perfect

@hppritcha - can you make your changes work on top of this patch?

**Comment by hppritcha** [comment]
yes I'll try merging these two PRs together.

**Comment by hppritcha** [comment]
@shantonu I can't seem to fetch from your repo on github.

**Comment by hppritcha** [comment]
never mind fixed my url problem.

**Comment by shantonu** [comment]
Great! It's pr/travis-ci repo. I just updated my branch to ofiwg/master.

**Comment by hppritcha** [comment]
I combined the commits in #1351 .

**Comment by shantonu** [comment]
I am closing this PR then.

**Pull request closed without merging**
