### PR TITLE
prov/efa: Warning and fallback on ptrace protection

### PR DESCRIPTION
**Pull request by zhngaj**

### CODE REVIEW

**Comment by zhngaj** [comment]
> The last commit in your series has an internal link, please update that commit message.

Ah. Thanks for your reminder. I will remove it.

**Comment by zhngaj** [comment]
@shefty Could you send me the failure of Intel CI?

**Comment by shefty** [comment]
Intel MPI failure with tcp provider
```
# Barrier
Abort(407981839) on node 2 (rank 2 in comm 0): Fatal error in PMPI_Comm_split: Other MPI error, error stack:
PMPI_Comm_split(499)........................: MPI_Comm_split(MPI_COMM_WORLD, color=-32766, key=2, new_comm=0x17c2d04) failed
PMPI_Comm_split(481)........................: 
MPIR_Comm_split_impl(163)...................: 
MPIR_Allgather_intra_auto(141)..............: Failure during collective
MPIR_Allgather_intra_auto(137)..............: 
MPIR_Allgather_intra_recursive_doubling(117): 
MPIC_Sendrecv(320)..........................: 
MPID_Isend(606).............................: 
MPIDI_isend_unsafe(258).....................: 
MPIDI_OFI_send_lightweight_request(98)......: 
(unknown)(): Other MPI error
```

**Comment by shefty** [comment]
So, ignore Intel CI failure

**Comment by zhngaj** [comment]
Got it. Thank you.

**Pull request merged**
