### PR TITLE
prov/gni: change 32-bit atomic addition to subtraction

### PR DESCRIPTION
**Pull request by gladkovdmitry17**
Signed-off-by: Dmitry Gladkov <dmitry.gladkov@intel.com>

### CODE REVIEW

**Comment by gladkovdmitry17** [comment]
@jswaro @shefty you're maybe interesting in this PR.

James, as I see in GNI provider, the returned value of `atomic_add` is utilized:
`collisions = ofi_atomic_add32(&ht->ht_collisions, hits);`

Seems it's only one place with such usage in GNI provider source code.
The behavior of atomic addition/subtraction was changed in case of C11 atomic. It was just aligned with non-C11 atomic. Before that, the return value of this functions were preceding value of add/sub atomic variable +/- 1. From now, the return value is preceding value +/- effect of atomic operation. Seems, it may break behavior, in `_gnix_ht_insert`. Please, check that these changes are OK for you. Thank in advance.

**Comment by shefty** [comment]
@gladkovdmitry17 I'm not following your comment.  From what I saw, the new ofi_atomic ops maintained the same behavior of the previous atomic_t definitions.

**Comment by jswaro** [comment]
I don't believe that it is anything so esoteric. I looked at the code in the previous pull request. 

In the previous pull request, the following locations were refactored incorrectly. All of the operations in these locations had their function swapped from an subtraction operation to an addition operation: 
https://github.com/ofiwg/libfabric/pull/2894/files?diff=split#diff-dbb3c58dbc1fb046072b5eeea9e97e2dL347
https://github.com/ofiwg/libfabric/pull/2894/files?diff=split#diff-dbb3c58dbc1fb046072b5eeea9e97e2dL481
https://github.com/ofiwg/libfabric/pull/2894/files?diff=split#diff-51daf151f5cb6375da738b06f16a733eL1147


However, he has a point in that it seems the atomic_add and atomic_sub for the previous definitions added 1, instead of the value to the returned value from atomic_fetch_{op}_explicit.

**Comment by jswaro** [comment]
> However, he has a point in that it seems the atomic_add and atomic_sub for the previous definitions added 1, instead of the value to the returned value from atomic_fetch_{op}_explicit.

> However, he has a point in that it seems the atomic_add and atomic_sub for the previous definitions added 1, instead of the value to the returned value from atomic_fetch_{op}_explicit.

See https://github.com/ofiwg/libfabric/pull/2894/files?diff=split#diff-4664d4036609b2b9d2afc7ce5fc99d47L107

**Comment by shefty** [comment]
Got it -- then are these changes good to merge?

**Comment by jswaro** [comment]
I'm testing them right now. Please do not merge. 

I'm guessing it will be fine, but since it broke once, let's verify it before we merge it.

**Comment by gladkovdmitry17** [comment]
@shefty @jswaro Sorry for my typo, and thanks for quick review

**Comment by jswaro** [comment]
> @shefty @jswaro Sorry for my typo, and thanks for quick review

It happens. Thanks for looking into the issue. 

The tests pass for me with these modifications, so go ahead.

**Comment by shefty** [comment]
thanks

**Pull request merged**
