### PR TITLE
man: Minor cleanup

### PR DESCRIPTION
**Pull request by jithinjosepkl**
Remove invalid link in domain man page.

### CODE REVIEW

**Comment by bturrubiates** [comment]
That isn't invalid, there is a `fi_ep.3` page. Why is it not showing up on the web version?

**Comment by shefty** [comment]
I believe it's fi_endpoint.3

**Comment by bturrubiates** [comment]
Oh it seems that the files that link others are not being rendered or converted to HTML correctly. See the [fi_gni.7](https://ofiwg.github.io/libfabric/master/man/fi_gni.7.html) page and it's link to `fi_open_ops`.

**Comment by bturrubiates** [comment]
> I believe it's fi_endpoint.3

I added an alias for `fi_ep`, it seems the web version doesn't have the aliases.

**Comment by bturrubiates** [comment]
In this case `fi_endpoint` is already listed above it, so `fi_ep` isn't necessary. So I guess :+1:

**Comment by jithinjosepkl** [comment]
Yeah, I dont thnk we need fi_ep. I think we should remove "man/man3/fi_ep.3" too

**Comment by bturrubiates** [comment]
> Yeah, I dont thnk we need fi_ep. I think we should remove "man/man3/fi_ep.3" too

I added `fi_ep` and I think some of the others expressed an interesting in having it. When using the command line man pages it helps to type `man fi_ep` since it comes a bit naturally. I think the issue is that we shouldn't reference the files that just source the others since those are intended for command line usage and exploration. I'll figure out which the dead links are.

**Comment by shefty** [comment]
Will you create a new PR that removes all of the dead links, or are we okay merging this change in?

I would like to keep the fi_ep man page myself.

**Comment by bturrubiates** [comment]
> Will you create a new PR that removes all of the dead links, or are we okay merging this change in?
> 
> I would like to keep the fi_ep man page myself.

Sure, I'll remove all of the links.

**Pull request closed without merging**
