### PR TITLE
gh-pages: website updates

### PR DESCRIPTION
**Pull request by goodell**
Add a new "Fork me on GitHub" ribbon and add the SC15 libfabric tutorial slides to the home page.

We should probably consider reorganizing the way we show all these presentations, we can't just keep adding new ones to the bottom indefinitely.

### CODE REVIEW

**Comment by jsquyres** [comment]
:+1:

**Comment by bturrubiates** [comment]
This looks right, and if I use Jekyll serve locally it's correct. Why is the running version on the website kinda borked?

**Comment by goodell** [comment]
Not 100% sure why it was broken on GH but working locally, but I just merged a fix via PR #1475 that seems to have fixed it.  My best guess is a version mismatch between my local Jekyll instance and GH's version.

**Comment by bturrubiates** [comment]
Cool, much better. Thanks.

**Pull request merged**
