### PR TITLE
v1.15.x: add opx

### PR DESCRIPTION
**Pull request by shefty**

### CODE REVIEW

**Comment by j-xiong** [comment]
Weird, what's this DCO error about? Brendan doesn't have a matching email in his profile?

Commit sha: [f223d44](https://github.com/ofiwg/libfabric/pull/7564/commits/f223d44e8da4a4b2c32bc2386365cbcf116a4021), Author: Brendan Cunningham, Committer: Sean Hefty; Can not find "Brendan Cunningham [14318587+BrendanCunningham@users.noreply.github.com](mailto:14318587+BrendanCunningham@users.noreply.github.com)", in ["Brendan Cunningham [bcunningham@cornelisnetworks.com](mailto:bcunningham@cornelisnetworks.com)", "Michael Heinz [mheinz@cornelisnetworks.com](mailto:mheinz@cornelisnetworks.com)"].

**Comment by shefty** [comment]
I saw that DCO error yesterday as well.  I don't understand, since these are cherry picked commits.

**Comment by rajachan** [comment]
I've noticed DCO checks not liking the co-author tags.

**Comment by shefty** [comment]
The co-authors are badly formed in one of the commits.  But why did main pass the check, but the cherry picked version did not?  Makes me think something is messed up with my git setup somehow.

**Comment by j-xiong** [comment]
I thought you used "force DCO to pass" option for main. We can do that here anyway.

**Comment by shefty** [comment]
Updated author to match sign-off-by line and co-authors in commit message

**Comment by shefty** [comment]
Did I?  I didn't mean to.

**Review by j-xiong — APPROVED** [review]

**Comment by shefty** [comment]
bot:aws:retest

**Comment by shefty** [comment]
Restarted Intel CI -- waiting to restart other CIs until the nodes clear.

**Pull request merged**
