### PR TITLE
prov/efa: detect and print error for recvwin overflow

### PR DESCRIPTION
**Pull request by wzamazon**
depend on https://github.com/ofiwg/libfabric/pull/6955

### CODE REVIEW

**Comment by wzamazon** [comment]
Ready for review, but depend on https://github.com/ofiwg/libfabric/pull/6955

**Review by mjkoop — COMMENTED** [review]
In the case of a wraparound recvwin_id, this will fail. A 'future' message could have a lower msg_id.

**Comment by wzamazon** [comment]
`ofi_recvwin_id_processed` used function `ofi_val32_gt` (instead of '>') to compare two uint32_t value, which is able to handle wrap around.

https://github.com/ofiwg/libfabric/blob/24dc9b17c81572ad7c8b709b0d34406709676368/include/ofi.h#L123.

**Comment by mjkoop** [comment]
Looks good to me.

**Review by mjkoop — APPROVED** [review]

**Pull request merged**
