### PR TITLE
sockets, man pages: Updates to FI_PEEK

### PR DESCRIPTION
**Pull request by jithinjosepkl**
- Update sockets provider to make FI_PEEK asynchronous (for message not-found case)
- Man page clarification about FI_PEEK

@shefty, @sayantansur, @j-xiong - Please review.

### CODE REVIEW

**Comment by shefty** [comment]
Thanks - can you also push these patches against the 1.1.x branch?

**Comment by jithinjosepkl** [comment]
sure, i will.

**Comment by j-xiong** [comment]
Looks good.

**Comment by sayantansur** [comment]
:+1:

**Pull request merged**
