### PR TITLE
Renamed gnix_buddy_allocator.* and moved to common code.

### LINKED ISSUE #1663: Move gni buddy allocator into common code
Please see #1661

### PR DESCRIPTION
**Pull request by e-harvey**
Removed gnix prefix from function names and updated headers.
Updated Makefile.am and prov/gni/Makefile.include to reflect
changes.
Fixes #1663 

@sungeunchoi @hppritcha 

Signed-off-by: Evan Harvey <eharvey@lanl.gov>

### CODE REVIEW

**Comment by bturrubiates** [comment]
If this is going to be in common code, then should the name for the `gnix_buddy_alloc_handle_t` change?

**Comment by shefty** [comment]
Before trying to re-implement glibc inside of libfabric, I'd really like to see evidence that there's a performance gain that we're getting from this.

**Comment by pmmccorm** [comment]
+1 for testing this. Malloc is smart. I watched a talk recently where a handful of projects had their custom allocators compared against standard malloc: the majority of the custom ones turned out to be slower. The projects of course never bothered to test..

**Comment by sungeunchoi** [comment]
This doesn't need to be pulled into common code.  It was requested in #1663.  I suggest we leave it where it is and close this PR for now.

**Comment by e-harvey** [comment]
Yes.  My mistake.

**Comment by e-harvey** [comment]
Ok, I agree with testing the performance.  There is no sense in using this if it performs poorly.  I will try to get some performance numbers in my free time.

**Comment by e-harvey** [comment]
Ok

**Comment by jithinjosepkl** [comment]
It was requested in 1663, hoping we could use this as a buffer pool. Many providers have their own implementations of buffer pool. But, unless we know that "buddy-allocator" offers better performance, there is no point in using it blindly.

Will gni provider eventually use this? Currently it seems that it is not being used.

**Comment by sungeunchoi** [comment]
FWIW, @hppritcha wanted it based on his experience with the Cray SW stack, and it made for a good starter project for Evan.  Whether it performs better than stock malloc is obviously going to depend on your particular use case.

**Comment by shefty** [comment]
*If* this exists at all, it should be in common code.  The question is why does it exist, and the argument that it may perform better in an unknown use case isn't very compelling.

**Comment by e-harvey** [comment]
Okay, I will look for some allocator benchmarks to run.

**Comment by goodell** [comment]
Not to pile on here, but an allocator microbenchmark isn't going to be as compelling as showing the performance gain you get from real use in the gni provider.  I'd recommend pursuing that sort of benchmarking instead.

**Comment by e-harvey** [comment]
This allocator is for a specific use case.  We will leave this code in the gni provider for now until someone requests to move it to common code.

**Pull request closed without merging**
