### PR TITLE
Fix ucx set/getopt error return and hmem_ze error message 

### PR DESCRIPTION
**Pull request by j-xiong**

### CODE REVIEW

**Comment by j-xiong** [comment]
@shijin-aws Any detail on the AWS CI failure? It passed in the previous run.

**Comment by wenduwan** [comment]
@j-xiong We have internal CI flakiness. Please restart test.

**Comment by j-xiong** [comment]
bot:aws:retest

**Comment by wenduwan** [comment]
Also, the AWS CI failure is unlikely related to this PR. I don't think we need to block merge.

**Pull request merged**
