### PR TITLE
contrib/cray: Move all xunit processing to the test stage post processing.

### PR DESCRIPTION
**Pull request by tonyzinger**
contrib/cray: Move all xunit processing to the test stage post processing.

### CODE REVIEW

**Comment by tonyzinger** [comment]
@jswaro

**Comment by shefty** [comment]
Please hold off merging until after 1.7 is released/branched.

**Comment by jswaro** [comment]
@shefty It would be ideal if we could merge this prior to the 1.7 release. This only affects our internal CI, and would affect our testing of the 1.7 release tag if not merged. This issue with the Jenkins file causes the build to fail intermittently. Not a huge problem, but I'd like to fix it if possible.

**Comment by shefty** [comment]
Okay - merge when ready then.

**Comment by jswaro** [comment]
Thanks. Done.

**Pull request merged**
