### PR TITLE
Enhance support for sockets over OFI

### PR DESCRIPTION
**Pull request by shefty**
These patches introduce changes to the API to better support the implementation of socket APIs over OFI.

@patrickmacarthur - These are not quite ready for merging, but please look through the changes.  The sockets  and verbs providers would need to be updated to support the new functionality.

### CODE REVIEW

**Comment by shefty** [comment]
@jithinjosepkl @shantonu @goodell @a-ilango -- This series modifies the providers and how they support connection requests.  Please review the changes and let me know if they look okay.  I made the simplest changes that I could, not necessarily what might be optimal.

**Comment by goodell** [comment]
The changes look OK in general to me.  The usnic provider will obviously need further updates to support  `setname` and some of this passive --> active endpoint conversion, but we can add those after this PR is merged.

**Comment by a-ilango** [comment]
The changes look fine.

**Comment by jithinjosepkl** [comment]
Sockets provider changes look good too. 
Will add changes for fi_setname in a following PR.

**Pull request merged**
