### PR TITLE
prov/verbs: Fix intermittent CQ busy at MPI finalize when using XRC

### PR DESCRIPTION
**Pull request by swelch**
When an XRC connection request is rejected and the associated
XRC Send QP represents the physical QP to the rejecting host,
destroy that QP before any pending connection to that same
rejecting host proceeds.

Signed-off-by: Steve Welch <swelch@systemfabricworks.com>

### CODE REVIEW

**Comment by swelch** [comment]
@shefty - After this is approved and merged, I can create a PR for 1.7.x. Thanks.

**Comment by shefty** [comment]
AWS CI failure is unrelated (socket dgram test).  Waiting for other CI to finish

**Comment by swelch** [comment]
> AWS CI failure is unrelated (socket dgram test). Waiting for other CI to finish

@shefty - Is the Intel CI failure and issue?

**Comment by shefty** [comment]
@swelch - I have no idea.  I can't figure out how to find this build in the buildbot.  :/

**Comment by aingerson** [comment]
@shefty @swelch  The Intel CI error is the sockets Open MPI OSU failure that we've seen a couple of times. I think you can ignore it but I can retest if you like.

**Comment by rajachan** [comment]
What's our plan with these transient sockets failures? As for AWS CI, should we exclude the test that keeps failing if it is a known race condition?

**Comment by shefty** [comment]
My plan is to replace sockets with tcp and ignore it forever.  :)  However, people keep adding fixes for it, since it's the best option that we have for now for broad SW development purposes.  Maybe one of these fixes will make it work more reliably, but it's not a provider that I personally want to invest much time in.  (The last time I looked, there were complex races in the code that would take a significant amount of work to remove.)  But the failures are occurring more frequently, possibly because we've improved our testing.  If specific tests continue to fail, I vote to remove them from the testing,

**Comment by rajachan** [comment]
Good plan, I vote for that too. Will keep an eye out to see if it is the same test.

**Pull request merged**
