### PR TITLE
prov/rxm: Use regular send instead of inject to send ACKs

### PR DESCRIPTION
**Pull request by a-ilango**
This is to handle providers which doesn't support inject.

### CODE REVIEW

**Comment by jswaro** [comment]
Wouldn't it be more ideal to use inject when supported but use sendmsg otherwise?

**Comment by a-ilango** [comment]
> Wouldn't it be more ideal to use inject when supported but use sendmsg otherwise?

The RXM protocol requires completion even when inject (FI_INJECT flag to be specific) is used. The ACK is a small packet (< 100 bytes) and the assumption is there wouldn't be significant performance difference b/w send and sendmsg with FI_INJECT.

**Comment by shefty** [comment]
I kind of agree with Jim.  You could copy the two calls and invoke one or the other based on inject support size.  You could even set which call to invoke as a function pointer, so that it is setup at initialization time.

This sort of structure could be useful for dynamically selecting optimal implementations of other parts of the protocol handling, or to invoke the next protocol function based on the current state without needing switch statements. (These are longer term possibilities.)

I think the proposed change adds this overhead: cost of removing/returning buffer from a pool, plus need of underlying provider fetching the data buffer, rather then copying it as inline data.  Can we easily see if this measurable in a message rate test?  If not, I'm fine going with the simpler solution for now, and deferring performance optimizations when the code is more complete.

**Comment by jswaro** [comment]
> I think the proposed change adds this overhead: cost of removing/returning buffer from a pool, plus need of underlying provider fetching the data buffer, rather then copying it as inline data. Can we easily see if this measurable in a message rate test? If not, I'm fine going with the simpler solution for now, and deferring performance optimizations when the code is more complete.

Yep. A simple test to see what the overhead would be ideal. At the very least, please add a TODO to the code in that section as an optimization target.

**Comment by a-ilango** [comment]
I ran a latency test (rdm_pingpong) and the difference in performance with and without this patch were within noise levels. Nevertheless, I'll add the code for checking inject size. It's not a lot anyway.

**Comment by jswaro** [comment]
> I ran a latency test (rdm_pingpong) and the difference in performance with and without this patch were within noise levels. Nevertheless, I'll add the code for checking inject size. It's not a lot anyway.

Thanks!

**Comment by shefty** [comment]
A better test would be a message rate test (one-way streaming).  That typically shows up software overhead  better than pingpong, since the pingpong latency is significantly higher than small increases in software overhead.

**Comment by a-ilango** [comment]
> A better test would be a message rate test (one-way streaming). That typically shows up software overhead better than pingpong, since the pingpong latency is significantly higher than small increases in software overhead.

Not seeing a big difference with a streaming test as well.

**Pull request merged**
