### PR TITLE
rdma/fi_eq: Support cntr byte counting

### PR DESCRIPTION
**Pull request by chadkoster-hpe**
Define new enum value to support byte counting with counters.

### CODE REVIEW

**Review by swelch — CHANGES_REQUESTED** [review]
Please add the new enum definition to this function in src/fi_tostr.c
```static void
ofi_tostr_cntr_events(char *buf, size_t len, enum fi_cntr_events events)
{
        switch (events) {
        CASEENUMSTRN(FI_CNTR_EVENTS_COMP, len);
        default:
                ofi_strncatf(buf, len, "Unknown");
                break;
        }
}
```

**Comment by chadkoster-hpe** [comment]
> Please add the new enum definition to this function in src/fi_tostr.c
> 
> ```
> ofi_tostr_cntr_events(char *buf, size_t len, enum fi_cntr_events events)
> {
>         switch (events) {
>         CASEENUMSTRN(FI_CNTR_EVENTS_COMP, len);
>         default:
>                 ofi_strncatf(buf, len, "Unknown");
>                 break;
>         }
> }
> ```

My bad, you asked for this last time too.  Thanks for the reminder.

**Review by swelch — APPROVED** [review]

**Review by shefty — APPROVED** [review]

**Comment by j-xiong** [comment]
Please squash the two commits.

**Comment by shijin-aws** [comment]
bot:aws:retest

**Review by j-xiong — CHANGES_REQUESTED** [review]
Won't be merged until the two commits are squashed.

**Review by j-xiong — APPROVED** [review]

**Pull request merged**
