### PR TITLE
compiler warning fixes

### PR DESCRIPTION
**Pull request by jsquyres**
Fix compiler warnings in:

* core
* usnic
* sockets

### CODE REVIEW

**Comment by jsquyres** [comment]
@goodell Please review the usnic changes
@jithinjosepkl Please review the sockets changes
@shefty Please review the code changes (trivial)

**Comment by shefty** [comment]
These look good to me.  I will merge this in manually with a new PR to resolve the conflicts.

**Comment by goodell** [comment]
usnic changes look good to me

**Comment by shefty** [comment]
See PR #841

**Comment by jithinjosepkl** [comment]
Sockets provider changes look good.

**Pull request closed without merging**
