### PR TITLE
prov/psm3: Use AR variable and do not call ar directly

### PR DESCRIPTION
**Pull request by acgoldma**
Call randlib after ar.

Signed-off-by: Goldman, Adam <adam.goldman@intel.com>

### CODE REVIEW

**Comment by acgoldma** [comment]
Found this while debugging https://github.com/ofiwg/libfabric/issues/6614

**Comment by acgoldma** [comment]
when building with `AR=gcc-ar` this will cause a warning when building with psm3:
```
  CCLD     libpsm3.la
ar: .libs/libpsm3_exp.o: plugin needed to handle lto object
  CCLD     src/libfabric.la
```

**Comment by acgoldma** [comment]
Should this be merged into v1.12.x

**Comment by shefty** [comment]
@acgoldma - I'll leave this to your call to port to 1.12.x

**Pull request merged**
