### PR TITLE
fabric: Move ep_type from fi_info into ep_attr

### PR DESCRIPTION
**Pull request by shefty**
Conceptually, this is a simple change, but the impact is significant.  Please review the provider code to see that what was changed is correct and that nothing was missed!

@goodell @jithinjosepkl  @j-xiong @shantonu @a-ilango

### CODE REVIEW

**Comment by j-xiong** [comment]
PSM provider changes look fine to me.

**Comment by jithinjosepkl** [comment]
Sockets provider changes also look good.

**Comment by a-ilango** [comment]
Verbs provider changes look fine.

**Comment by goodell** [comment]
usnic provider changes look OK to me

**Pull request merged**
