### PR TITLE
various fixes and cleanups for tcp + rxm

### PR DESCRIPTION
**Pull request by shefty**
Pulling out fixes from #6684 .

Updates to fabtests data verification.
updates to rxm and tcp ubertest configs.
Fix rxm initialization of atomic headers
Fix tcp reporting message size (dynamic receive handling)
Fix ubertest error reporting
Code cleanups to rxm direct send and dynamic receive handling

### CODE REVIEW

**Comment by shefty** [comment]
bot:aws:retest

**Comment by shefty** [comment]
AWS failure was in EFA NCCL test, which should be unaffected by these changes.  Re-running.

**Comment by shefty** [comment]
AWS failure moved from EFA to TCP, so suspect both are transient.

**Comment by rwespetal** [comment]
The failure looks unrelated to your change, I'll ask about the error internally.

**Pull request merged**
