### PR TITLE
prov/psm3: Fix psm3 cuda rbtree conflict

### PR DESCRIPTION
**Pull request by acgoldma**
Signed-off-by: Goldman, Adam <adam.goldman@intel.com>

### CODE REVIEW

**Comment by acgoldma** [comment]
@shefty, should this wait until after v1.13.0 GA?

**Comment by shefty** [comment]
I think we want this for v1.13.

**Comment by acgoldma** [comment]
> I think we want this for v1.13.

Okay, this can be merged when the CI tests pass. 

Not sure why the Intel Jenkins test is taking so long. It looks like it is still going without issues, it has been 4 hours since it started. I think it is hitting some timeout?

The AWS failure looks unrelated.

**Comment by shefty** [comment]
Intel CI has a limited number of nodes available, so the job can get queued behind other jobs.  Each PR and each update to a PR generates a new job.  Currently, there's a more comprehensive nightly test suite that's running which takes something like 6-8 hours to complete.  I'm not sure why it started so late (~5AM PST), but could be the result that I updated the scripts that the nightly test uses.

**Comment by rajachan** [comment]
Jenkins's Github hook lets you kill a stale job if a PR gets updated ("cancel build on update" option IIRC). That might help with resource utilization.

**Comment by shefty** [comment]
bot:aws:retest

**Review by shefty — APPROVED** [review]

**Pull request merged**
