### PR TITLE
BUILD_ID config constant may be undefined

### PR DESCRIPTION
**Pull request by chrisdolan**

### CODE REVIEW

**Comment by shefty** [comment]
Can you clarify when this would be undefined?  And would we be better ensuring that it is defined in all cases?

**Comment by chrisdolan** [comment]
My build environment is idiosyncratic -- so maybe I'm the only one who needs this? But this code snippet for Windows suggests others needed it at some point: https://github.com/ofiwg/libfabric/blob/e48a8338b3bcb8eca677fc4c467c2205ae0c4b9e/include/windows/config.h#L200

If Linux had a similar #ifdef to that Windows config.h then this patch would likely be unnecessary.

**Comment by jsquyres** [comment]
I'm guess I'm curious as to when `BUILD_ID` would be undefined.

1. In the "we run `configure`" case, there's an unconditional `AC_DEFINE_UNQUOTED` that always defines `BUILD_ID` in `config.h`.  That file *should* be installed in all libfabric .c files.  If it's not, we should fix that.
2. In the Windows case, `include/windows/config.h`, as you cited, ensures that `BUILD_ID` is defined.

Meaning: I think that this PR is just masking some other problem (that `BUILD_ID` isn't defined properly when it should be).

**Comment by chrisdolan** [comment]
OK, sorry, sounds like this is only a problem in my build system. I'll close the PR.

**Pull request closed without merging**
