### PR TITLE
prov/efa: Fix shm file name

### PR DESCRIPTION
**Pull request by zhngaj**
Remove "/" from the shm file name.

Signed-off-by: Jie Zhang <zhngaj@amazon.com>

### CODE REVIEW

**Comment by wzamazon** [comment]
Why are we doing that? Would you please give some context?

**Comment by zhngaj** [comment]
> Why are we doing that? Would you please give some context?

The "/" is unnecessary here, as the file name can not have "/".
Even though we add it here, eventually it will be removed when creating shm file, like (/dev/shm//file)

**Comment by wzamazon** [comment]
I see, would you please add that to commit message?

**Comment by zhngaj** [comment]
Sure.

**Comment by zhngaj** [comment]
bot:aws:retest

**Comment by zhngaj** [comment]
The failure in AWS CI was due to an issue in libfabric-ci-scripts.
Fix awslabs/libfabric-ci-scripts#66 has been merged, re-triggering.
bot:aws:retests

**Comment by zhngaj** [comment]
The failure in AWS CI is CI system related issue now, and it can be ignored (https://libfabric-ci.aws.a2z.com/job/nccl-multi-node/PROVIDER=tcp%3Bofi_rxm,label=alinux/149/console).

**Pull request merged**
