### PR TITLE
[v1.13.x] cherry-picked fixes for hmem-ze and jenkins

### PR DESCRIPTION
**Pull request by j-xiong**

### CODE REVIEW

**Review by shefty — APPROVED** [review]

**Comment by j-xiong** [comment]
The intel CI error is for the MPICH build:
```
11:36:34  configure: error: do not use --enable-ch4-direct; use --without-ch4-shmmods instead
```
This is totally unrelated to this PR.

**Comment by j-xiong** [comment]
Add a commit to fix MPICH configure option. This only applies to v1.13.x (and maybe earlier branches) since the section has been removed in later branches.

**Comment by j-xiong** [comment]
Add a commit to fix issues with building benchmarks using Intel MPI.

**Comment by j-xiong** [comment]
bot:aws:retest

**Comment by j-xiong** [comment]
The remaining ci errors are due to failed attempt to access external repo. They can ignored for now.

**Pull request merged**
