### PR TITLE
util/mr_cache, prov/verbs: Implement new MR caching path w/o merging regions (for v1.6.x)

### PR DESCRIPTION
**Pull request by gladkovdmitry17**
This is back-port of #3974 

This fixes some boundary cases for MPI ring-based algorithm on large data

### CODE REVIEW

**Comment by gladkovdmitry17** [comment]
@shefty It would be nice to include this fix in 1.6.1

**Comment by gladkovdmitry17** [comment]
This solution is pretty well tested on master branch and should not cause any issue.

**Comment by shefty** [comment]
Can you add an update to NEWS as well?

**Comment by gladkovdmitry17** [comment]
> Can you add an update to NEWS as well?

Done. The 3rd patch contains the necessary updates to NEWS

**Comment by shefty** [comment]
Thanks!

**Pull request merged**
