### PR TITLE
[v1.15.x] prov/efa: Fix a bug in rxr_pkt_req_max_header_size

### PR DESCRIPTION
**Pull request by shijin-aws**
Backport https://github.com/ofiwg/libfabric/pull/8100

### CODE REVIEW

**Review by wzamazon — APPROVED** [review]

**Review by shefty — APPROVED** [review]

**Comment by shijin-aws** [comment]
AWS CI failure is a CI issue.

**Comment by shijin-aws** [comment]
bot:aws:retest

**Comment by wzamazon** [comment]
Please rebase on latest v1.15.x to fix the CI issue.

**Comment by shijin-aws** [comment]
AWS CI failed in socket provider: https://libfabric-ci.aws.a2z.com/job/multi-node/1009/PROVIDER=sockets,label=ubuntu1804/testReport/junit/ubuntu1804.test_suites.libfabric/test_fabtests/test_libfabric_fabtests_double_node_release__test_multi_mr_rdm_/, which is not related to this PR.

**Pull request merged**
