### PR TITLE
fabric: $FI_PROVIDER_PATH env var specifies where DLs live

### PR DESCRIPTION
**Pull request by jsquyres**
Having a default location for DLs is fine (i.e., `$pkglibdir`), but it's not enough.  Specifically, if a provider maintainer wants to provide an asynchronous update to their built-in/inbox provider, it's easy enough to create a DL of the provider and install it in `$pkglibdir`.

But what about the provider's extension header file?

That extension header file is currently installed into `$includedir/fi_ext_<provider>.h`.  It would be extremely anti-social for an async provider update to overwrite that file (and potentially make package managers -- such as rpm -- unhappy).  Indeed, the point of allowing DLs to "override" built-in providers is to provide async provider updates *without* replacing any of the libfabric packaged files (including the inbox-provided `fi_ext_<provider>.h`).

The async provider update will need to install its updated `fi_ext_<provider>.h` file elsewhere -- e.g., `/opt/vendor/include/fi_ext_<provider>.h`.  ...but then it's weird that the provider DL is in one location and the provider extension header is in another (e.g., `/usr/lib` vs. `/opt/vendor`).  It would be nicer if both could be installed under a single tree (e.g., `/opt/vendor`).

This commit therefore adds the `FI_PROIVDER_PATH` env var which allows a colon-delimited list of directories to search for provider DLs.  If `$FI_PROVIDER_PATH` is set, it is used instead of `$pkglibdir`.  If `$FI_PROVIDER_PATH` is not set, `$pkglibdir` is used (just like it used to be).

Signed-off-by: Jeff Squyres <jsquyres@cisco.com>

### CODE REVIEW

**Comment by pmmccorm** [comment]
I think this is a couple issues, and I think this this patch partially solves only one. Let me play around with it a little bit..

**Comment by jsquyres** [comment]
@pmmccorm Any update?  This is something we really, really want to include in the March 31 release.

**Comment by pmmccorm** [comment]
A solution for allowing async updates with headers that will work with package managers is to have a "update" or "extra" include dir (except named something better) like:

/usr/include/rdma/vendor/

This way a out of tree provider installs two things:

    $pkglibdir/fi-prov.so
    $prefix/include/rdma/vendor/fi_ext_prov.h

Then dependent libraries/apps just include the vendor dir first.

What does having environment specified paths for dl-loading providers gain us?

**Comment by jsquyres** [comment]
Having to pick between -Ifoo and -Ifoo/new_version is very distasteful -- it's very libnl-esque.  I'd really prefer to have a newer version in an entirely different tree (e.g., `/opt/vendor/...`).

The env settings for specific paths for DL-loading allows us to put the DL and the .h file in the same tree (e.g., `/opt/vendor`).

**Comment by pmmccorm** [comment]
If you install somewhere in /opt you will have to pick between -Iopt/new_version and -Ifoo, so what does it gain us?

If you make an official location for updated headers (think like kernel's extra or upates dir) then at least everyone has the same includes.

Changing provider interfaces mid stable release will cause pain-- it is not what the dl-system was intended to facilitate (right?). Bug fixes, performance fixes, debugging providers will all work fine without needing any of this..

**Comment by jsquyres** [comment]
I can't tell if your first line examples are "dash eye" or "dash ell"...

If we install the new provider in `/opt/vendor/lib/my_provider_dl.so`, then the user would still be linking against the system-installed libfabric.  So the user doesn't need to -L/opt/vendor/lib, they're still linking against `-lfabric`, which assumedly gets the libfabric in `/usr/lib`, or somesuch.

And to clarify: we are *definitely* interested in using the DL interface to install an updated usnic provider without disrupting the upstream libfabric.  I've stated this previously a few times.

Specifically: upstream libfabric will be installed by RPM (e.g., by the distro), and the usnic provider will be compiled in it.  But we/Cisco will issue new releases to fix bugs, support new hardware, etc.  And we want to be able to do this both via the distro (via the normal distro partner mechanisms), and also asynchronously for customers who need it at a different schedule than distros update.

Finally, I think a provider should be free to change their extension interfaces any time they want.

**Comment by pmmccorm** [comment]
Its I as in Include.

The linking stuff you mention: yeah that will work just fine as you describe.

Upgrading a distro-installed provider is fine, but if the new provider updates (for example adds a new fast_send call or adds a new parameter to an existing call) the interface dependent software will have to recompile (like *mpi) to use the new interface.

At this point they have two include two paths in their build (in order):

some/other/path  for updated fi_ext_* headers that may accompany new dl-providers
$prefix/include/    for rdma/fi* headers

I am saying that some/other/path should be a known location owned by libfabric vs different things for every provider.

So to return to the original patch: what does this patch gain us in an async-update scenario?

**Comment by jsquyres** [comment]
Re: Providers changing extension interfaces via an async update: of course.  If the provider *changes* (or *removes*) an interface, they're probably looking for pain.  If the provider *adds* an extension interface, codes will have to recompile to use the new functionality.

As for putting the provider DL in `/opt/vendor` (vs. `/usr/lib/libfabric` or whatever $pkglibdir is), there's two reasons:

1. It just seems nicer (and simpler, RPM-specfile-wise) to put all files in a single tree -- e.g., `/opt/vendor`).
1. Some distros have guidelines/prohibitions about vendor-provided packages installing files outside of `/opt`.  I.e., they frown on 3rd party packages installing into "system-controlled" trees such as `/usr`.

**Comment by jsquyres** [comment]
Any further comment on this?  Can we merge it?

**Comment by pmmccorm** [comment]
I think it is OK, but we should think about how to ship an "official" 3rd party provider and how that works. I don't think this patch interferes with that.

**Comment by jsquyres** [comment]
Agreed.

**Pull request merged**
