### PR TITLE
[v1.18.x] prov/tcp: Fixes to locking around MR and fi_trywait

### PR DESCRIPTION
**Pull request by shefty**

### CODE REVIEW

**Comment by shefty** [comment]
bot:aws:retest

**Comment by shijin-aws** [comment]
I think a patch is needed in our CI to make 1.18.x branch test pass. I will let you know when it is ready.

**Comment by shijin-aws** [comment]
bot:aws:retest

**Comment by shijin-aws** [comment]
The patch is applied in AWS CI now. Retesting.

**Comment by shijin-aws** [comment]
bot:aws:retest

**Comment by shijin-aws** [comment]
ready for merge

**Pull request merged**
