### PR TITLE
Bgq provider fixes and enhancements

### PR DESCRIPTION
**Pull request by pkcoff**
This branch cleans up some configuration issues, addresses some code inefficiencies and redundancies, adds cache and inlining optimizations, and adds some performance tests for the BGQ Provider.

### CODE REVIEW

**Comment by pkcoff** [comment]
@jsquyres  somehow the distclean issue is back but nothing in the bgq Makefile has changed that could affect this can you think of anything common or in the Makefile.am that could explain this?

**Comment by jsquyres** [comment]
I see you have a lot of commented-out stuff in your Makefile.include -- is there a reason for that?  Seems weird to commit commented-out stuff.

In terms of this specific error, it looks like it is looking for `prov/bgq/external/memory_impl.c`, but I do not see this file anywhere in your tree.

**Comment by pkcoff** [comment]
Hi Jeff that file is a bgq system file that we copy in at build time, I just realized it is also being used in some new test cases so I split the source files out with the nodist variable and fixed the issue locally, forced pushed now travis is running again

**Comment by jsquyres** [comment]
@pkcoff Right, I remember the discussion about looking for that file at run-time, etc.  But my point was that I do not see you making a copy (or even a sym link?) for that file anywhere in the configure/build system.  E.g., in master:

```
$ ack memory_impl.c
prov/bgq/configure.m4
78:                                     AS_IF([test -f /bgsys/source/$bgq_dir/spi/src/kernel/cnk/memory_impl.c],
88:                     AS_IF([test ! -f $bgq_external_source/spi/src/kernel/cnk/memory_impl.c], [

prov/bgq/Makefile.include
53:bgq_files_nodist = prov/bgq/external/memory_impl.c
58:prov/bgq/external/memory_impl.c: @bgq_external_source@/spi/src/kernel/cnk/memory_impl.c
```

Hence, it doesn't really make sense to list it in a Makefile.anything if there's no code that actually puts that file in the libfabric tree.

**Comment by jsquyres** [comment]
I don't know what it is about the human brain -- you check over something 6 times, and then you finally post about it on github, and then literally as your finger is irrevocably moving downward to click on the "submit comment" button, you see exactly where you were wrong.  Sigh.

Ok, I see in `prog/bgq/Makefile.include`, that you *do* `cp` the file into the source tree.

But yes, you are correct -- that only happens when you are actually building the bgq provider (which most of us can't).  Hence, that file needs to be a nodist in the Makefile.include wherever it is used.

**Comment by pkcoff** [comment]
@jsquyres @shefty Everything passes any other issue with merging this?

**Pull request merged**
