### PR TITLE
contrib/intel/jenkins: Disable ZE IPC path and use SAR instead

### PR DESCRIPTION
**Pull request by zachdworkin**
The performance is really bad and takes very long. Until we debug it the ZE IPC path it will be disabled and will use SAR instead.

### CODE REVIEW

**Comment by j-xiong** [comment]
@zachdworkin The 'oneCCL-GPU-v3' stage is also slow with ZE IPC.

**Comment by j-xiong** [comment]
Wait until the 'v1.21.x' branch is created.

**Comment by j-xiong** [comment]
The v1.21.x branch has been created.

**Comment by j-xiong** [comment]
Doesn't seem to make any difference.

**Comment by aingerson** [comment]
@j-xiong Based on the performance numbers in the log, it definitely did. It just doesn't look like it because it spent a long time waiting for nodes from other PRs that are still having the issue.

**Pull request merged**
