### PR TITLE
prov/gni: fix a configure flub up with udreg

### PR DESCRIPTION
**Pull request by hppritcha**
Fix a problem with udreg related configury.

@charlesarcher

Signed-off-by: Howard Pritchard <howardp@lanl.gov>

### CODE REVIEW

**Comment by hppritcha** [comment]
@sungeunchoi 
this is a configury fix.  Did upstream since intel found the problem.

**Comment by charlesarcher** [comment]
👍

**Comment by jsquyres** [comment]
@hppritcha Does this PR fix what I'm seeing on libfabric HEAD right now (when I run on a machine that obviously does not have GNI support):

```
configure: *** Configuring gni provider
checking for CRAY_GNI_HEADERS... no
./configure: line 21190: test: too many arguments
configure: gni provider: disabled
```

**Comment by hppritcha** [comment]
@jsquyres no that's a different gni configury issue.  I'll fix that with a subsequent PR.

**Comment by hppritcha** [comment]
@jsquyres decided to fix all the issues in one commit, so your "too many arguments" should go away once this PR is merged.
@sungeunchoi this is ready to go.

**Comment by jsquyres** [comment]
@hppritcha Confirmed: fixes the "test" issues I saw in GNI configury.

**Comment by sungeunchoi** [comment]
👍

**Pull request merged**
