### PR TITLE
prov/verbs: Speedup XRC connection setup time

### PR DESCRIPTION
**Pull request by swelch**
By allowing the verbs CM event processing to continue if
an internal XRC event has been processed, XRC connection
setup time can be reduced between 47% in light and medium
loaded PPN environments, and ~ 15% on fully loaded PPN
(i.e. PPN == # virtual cores) environments.

RC will not hit the condition checked and will continue
to process at most 1 CM event.

Signed-off-by: Steve Welch <swelch@systemfabricworks.com>

### CODE REVIEW

**Comment by swelch** [comment]
@a-ilango @jswaro - This is a relatively minor update to modify EQ CM event processing that helps XRC connection setup times where connection events can be processed internally by the handler and does not impact RC times.

**Comment by shefty** [comment]
Could RC benefit by a similar change?

**Comment by swelch** [comment]
> Could RC benefit by a similar change?

For RC almost every time a CM event is processed an event will be added to the EQ (or an error is available), so it might be better for RC to return and let the libfabric EQ event be processed by the application.

**Comment by a-ilango** [comment]
For RC, in case of RDMA_CM_EVENT_ROUTE_RESOLVED event, rdma_connect is called and EAGAIN is returned to the caller. I'm not sure if reading the event channel again would speed up things in this case. For both RC and XRC, EAGAIN would be returned for any unhandled events as well.

**Comment by swelch** [comment]
> For RC, in case of RDMA_CM_EVENT_ROUTE_RESOLVED event, rdma_connect is called and EAGAIN is returned to the caller. I'm not sure if reading the event channel again would speed up things in this case. For both RC and XRC, EAGAIN would be returned for any unhandled events as well.

For the RDMA_CM_EVENT_ROUTE_RESOLVED when the rdma_connect() is successful, since an FI_EAGAIN is returned, both RC and XRC should attempt to process another event. I missed that case. I'm not sure if that helps or not either though, it probably just depends on how many events are queued.

**Pull request merged**
