### PR TITLE
usnic: add missing fi_log_init()

### PR DESCRIPTION
**Pull request by jsquyres**
@goodell Please review -- fairly trivial

Signed-off-by: Jeff Squyres <jsquyres@cisco.com>

### CODE REVIEW

**Comment by goodell** [comment]
I think the calls to `fi_log_init()` should be removed from the provider initialization functions.  The logging should always be initialized already in `fi_ini()` before the first provider is initialized.

@pmmccorm do you know why you added those extra calls in c0606a4?  The repeated call seems like it will be harmless in its effect, but it's not what was originally intended.

**Comment by pmmccorm** [comment]
Looking at it now I think they should be removed too, it should just need one initialization in fi_ini, I don't know what I was thinking.

**Comment by goodell** [comment]
> I don't know what I was thinking.

No worries, glad we are all on the same page now.  Jeff, you'll amend the PR?

**Comment by jsquyres** [comment]
PR amended.

**Pull request merged**
