### PR TITLE
Multinode tests in runfabtests.sh

### PR DESCRIPTION
**Pull request by AMcKinley15**
Fab tests will now run the multinoded test at 16, 32, 48, and 64 processes. 

Signed-off-by: Alex McKinley <alex.mckinley@intel.com>

### CODE REVIEW

**Comment by shefty** [comment]
For simple multinode CI testing, we can run as a normal client/server test.  If it's easy, maybe spawn 2 processes per node.  We can run real scale up testing on an actual cluster.

**Comment by AMcKinley15** [comment]
Yeah, changing so it runs only 2 processes is pretty simple. I think because of the way the script is written, everything runs on one node, but I may also be misreading the script.

**Comment by shefty** [comment]
I believe the script is intended to run on a single system.  Travis uses this during CI, and we only have a single system through travis.  runfabtests is more of a sanity check that we don't break anything than anything more substantial.

**Comment by AMcKinley15** [comment]
That makes sense. I changed it to do a 2 and 3 node test as a couple of base cases. There were definitely times where 2 nodes would work but 3 would not in testing.

**Comment by shefty** [comment]
In that case, if you can have it run 4 processes by default that could work.

**Comment by AMcKinley15** [comment]
Ok, sounds good.

**Comment by shefty** [comment]
Please see CI failures

**Comment by shefty** [comment]
If it helps with changes, we can replace the runfabtests.sh script with a python script.  @a-ilango might be your friend for a week if you make that change.

**Comment by shefty** [comment]
This is a new test that's not integrated yet, so I plan on ignoring that there are a bunch of unrelated changes going into a single commit.  But please start trying to place separate changes into their own patches.

**Comment by shefty** [comment]
@AMcKinley15 - is this pull request ready for merging?

**Comment by AMcKinley15** [comment]
@shefty It should be!

**Pull request merged**
