### PR TITLE
contrib/intel/jenkins: Catch potential release package make issues

### PR DESCRIPTION
**Pull request by zachdworkin**
Add make distcheck and rpmbuild to jenkins for regular build.
We need to catch problems where a release package does not include all necessary files because of potential missing updates to makefile.includes.

Signed-off-by: Zach Dworkin <zachary.dworkin@intel.com>

### CODE REVIEW

**Comment by shefty** [comment]
Does this need to be picked for v1.16.x, or will the CI use this file once merged?

**Comment by zachdworkin** [comment]
@shefty this will need to be picked. The Jenkinsfile is not like the other files in contrib/intel/jenkins that the CI would use from upstream/main.

**Comment by zachdworkin** [comment]
@shefty The job 2 failure shows that this fix works for the checking of that missing verbs file in Makefile.include in prov/verbs. Job 1 failures are unrelated but you can see in the build stage that it ran what we expected it to do.

**Comment by shefty** [comment]
Thanks - so this PR will fail unless #8070 is added to it?

**Comment by zachdworkin** [comment]
@shefty yes.

**Comment by zachdworkin** [comment]
@shefty the https://github.com/ofiwg/libfabric/pull/8070 changes also need to be merged into upstream/main for this to pass. Should I add a commit that includes the verbs file addition?

**Comment by shefty** [comment]
If adding the patch from #8070 here will allow the CI to pass, then please go ahead and add that change.  I can close #8070.

**Comment by zachdworkin** [comment]
@shefty added. The CI is running a replay with my changes applied.

**Pull request merged**
