### PR TITLE
use #ifdef HAVE_ALIAS_ATTRIBUTE

### PR DESCRIPTION
**Pull request by ggouaillardet**
instead of #if HAVE_ALIAS_ATTRIBUTE == 1

### CODE REVIEW

**Comment by ggouaillardet** [comment]
@jsquyres could you please review this ?
this should eventually land into the Open MPI master

**Comment by jsquyres** [comment]
@ggouaillardet I think the code here in libfabric is ok -- note the unconditional AC_DEFINE of HAVE_ALIAS_ATTRIBUTE in https://github.com/ofiwg/libfabric/blob/master/configure.ac#L170.

I think the problem was in OMPI's temporarily-embedded configure.m4, which didn't emulate the real libfabric configure.ac linker alias test, which I think I just fixed in open-mpi/ompi@f040ef09ff015c2104048ea5cd4ededd7d52166e.

Do you agree?

**Comment by ggouaillardet** [comment]
i agree and you can close this PR

i got confused by the fact libfabric uses a mix of #ifdef HAVE... and #if HAVE... == 1
#ifdef HAVE_ATOMICS
#if  HAVE_ALIAS_ATTRIBUTE == 1
#ifdef HAVE_SYMVER_SUPPORT

**Comment by jsquyres** [comment]
Yeah, the libfabric code base is not entirely consistent on this point (yet).

**Pull request closed without merging**
