### PR TITLE
prov/efa: cleanup efa_rdm_ep_record_tx_op_submitted()

### PR DESCRIPTION
**Pull request by a-szegel**
Remove efa_rdm_ep_get_peer() from efa_rdm_ep_record_tx_op_submitted for a slight performance improvement.

### CODE REVIEW

**Review by shijin-aws — APPROVED** [review]

**Comment by shijin-aws** [comment]
Please fix the AWS CI failure

**Comment by a-szegel** [comment]
I think the UT failure might be the same as the previous merged pr... rebasing and trying again.

**Comment by a-szegel** [comment]
no I am wrong, looks different.

**Comment by a-szegel** [comment]
ope->peer != peer always b/c of handshake

**Pull request closed without merging**
