### PR TITLE
Fix formatting in README.md

### PR DESCRIPTION
**Pull request by fintelia**

### CODE REVIEW

**Comment by shefty** [comment]
Can you please add a signed-off-by line to the commit message?  (Yes, it seems pointless for this patch, but they all need them).

**Comment by fintelia** [comment]
I edited the commit message but is seems Signed-off-by checker still isn't happy?

**Comment by shefty** [comment]
Maybe it's case sensitive?  ("Signed-off-by:")  just guessing, but this works for me.  thanks

**Comment by shefty** [comment]
@a-ilango - please see the test failure in travis.  (It's unrelated to this PR).  Is this related to the tag verification check added to fabtests?  (I just merged that earlier today).

**Comment by jsquyres** [comment]
Git pro tip: just use `git commit -s` to get the right magic token in the commit message.  That's what the Signed-off-by checker is searching for.  Sorry to be so pedantic...  😦

**Comment by a-ilango** [comment]
>@a-ilango - please see the test failure in travis. (It's unrelated to this PR). Is this related to the tag verification check added to fabtests? (I just merged that earlier today).

I'm looking into this. I'm not getting the issue on my setup though. :-/ Probably a race condition. I'll keep looking.

**Comment by jswaro** [comment]
@fintelia git commit --amend -s

**Comment by gladkovdmitry17** [comment]
Seems "fi_poll" became unstable and it fails form time to time.
Could you re-execute "git commit -s --amend" and "git push <name_of_remote> patch-1", please?

**Comment by jsquyres** [comment]
We've already made @fintelia go through a bunch of hoops -- no need to make him re-commit, push, and wait for CI to finish on a finicky test when this is literally a trivial documentation update.

**Pull request merged**
