### PR TITLE
prov/rxd: AV/address cleanup

### PR DESCRIPTION
**Pull request by aingerson**
When removing an address from the AV, the rxd
address/dg address should not be removed as well.
This is because the EP could still be communicating
with a peer for an outstanding transfer (or a retry).

If removed and reinserted, rxd will handle the duplicate
rxd address and map it accordingly.

This fixes a rare failure with the fi_av_xfer test which
is caused by a race condition where a peer tries to send
a retry or ACK after the address was removed from the AV.

Signed-off-by: aingerson <alexia.ingerson@intel.com>

### CODE REVIEW

**Comment by aingerson** [comment]
@shefty @nikhilnanal I *think* this is the issue with the av_xfer test. The bufpool assert seems to be from UDP not being able to lookup the address in the AV and failing a send.
Planning on running this through the CI various times to test it.

**Comment by shefty** [comment]
Based on the description, this sounds like an issue, and I can see how the assert would be hit via ofi_av_get_addr() trying to access an invalid buffer region.

**Review by shefty — APPROVED** [review]

**Comment by nikhilnanal** [comment]
I see this happening on n15-n16 more frequently so may be it ll help to test it out on those nodes.

**Comment by shefty** [comment]
On a related note, does rxd cleanup the addresses somewhere else?

**Comment by nikhilnanal** [comment]
I am verifying again, but I don't think it does. this and the other reason why this was here was where the man pages say
fi_av_remove
fi_av_remove removes a set of addresses from an address vector. All resources associated with the indicated addresses are released. The removed address - either the mapped address (in the case of FI_AV_MAP) or index (FI_AV_TABLE) - is invalid until it is returned again by a new fi_av_insert.

The behavior of operations in progress that reference the removed addresses is undefined.

**Comment by shefty** [comment]
The man page isn't really referring to internal data needed to communicate with a peer.  It's only talking about the addressing data required to support the AV.   An app can only send data to an address in the AV.  However, the provider may need to communicate with peers that are not in the AV.  That's the case here.  The cleanup went too far and shutdown internal communication too early.

FWIW, PR #6833 addresses the same problem with rxm.  There's a peer array for all known peers, which is separate from addresses added to the local AV.  Reference counting tracks when it's safe to remove a peer from the peer array.  A peer is added to the peer array when its address is added to the AV or there's internal communication with the peer.  Cleanup occurs as part of closing an endpoint or destroying the AV.  (Reference count drops to 0 once all endpoints are destroyed and the AV is closed).

**Comment by aingerson** [comment]
@nikhilnanal @shefty Updated with another patch to handle proper AV cleanup

**Pull request merged**
