### PR TITLE
ofi_signal Add a lock to protect wcnt and rcnt

### PR DESCRIPTION
**Pull request by shefty**
fd_signal_set() and fd_signal_reset() have an optimization
to avoid writing more than needed to the signal socket.
Now this optimization is done with counters (wcnt and rcnt)
and if the user of fd_signal (for example prov/tcp) does
not protect the call chain with its own locks a
write leak might come up filling up the socket.

Prov/tcp uses struct fd_signal through util_wait, but it
is also not easily possible to use the util_wait_fd
lock to protect struct fd_signal counters, as a lock ordering
issue comes up

    Thread 14 (Thread 0x7fbaae42a700 (LWP 2623488)):

    ==> tries to aquire ep->lock
    tcpx_try_func           at prov/tcp/src/tcpx_progress.c:657

    ==> holds wait_fd->lock
    in util_wait_fd_try     at prov/util/src/util_wait.c:249
    ofi_trywait             at prov/util/src/util_wait.c:70
    fi_trywait              at include/rdma/fi_eq.h:314

    Thread 73 (Thread 0x7fbcf6ec6700 (LWP 2623413)):

    ==> Tries to acquire wait_fd->lock
    util_wait_fd_signal     at prov/util/src/util_wait.c:232
    util_cq_signal          at include/ofi_util.h:508
    cq_signal               at prov/util/src/util_cq.c:418
    tcpx_cq_report_success  at prov/tcp/src/tcpx_cq.c:168
    process_tx_entry        at prov/tcp/src/tcpx_progress.c:121
    tcpx_tx_queue_insert    at prov/tcp/src/tcpx_progress.c:692
    tcpx_send               at prov/tcp/src/tcpx_msg.c:263

    ==> holds ep->lock
    fi_send at include/rdma/fi_endpoint.h:291

Simplest solution is therefore to add a lock to fd_signal.

Signed-off-by: Bernd Schubert <bschubert@ddn.com>

### CODE REVIEW

**Comment by shefty** [comment]
Picked from PR #5900

**Comment by shefty** [comment]
bot:aws:retest

**Comment by shefty** [comment]
@rajachan - AWS failure looks unrelated, but appears to be a real issue:
```
17:10:36 172.31.27.177 - name:   fi_rma_bw -e rdm -o read -p "efa"
17:10:36 172.31.27.177   result: Fail
17:10:36 172.31.27.177   time:   3
17:10:36 172.31.27.177   server_cmd: /home/ec2-user/libfabric/fabtests/install/bin/fi_rma_bw -e rdm -o read -p "efa"  -E
17:10:36 172.31.27.177   server_stdout: |
17:10:36 172.31.27.177     bytes   iters   total       time     MB/sec    usec/xfer   Mxfers/sec
17:10:36 172.31.27.177     64      20k     1.2m        0.10s     12.28       5.21       0.19
17:10:36 172.31.27.177     256     20k     4.8m        0.10s     50.50       5.07       0.20
17:10:36 172.31.27.177     1k      20k     19m         0.12s    169.93       6.03       0.17
17:10:36 172.31.27.177     4k      20k     78m         0.14s    584.73       7.00       0.14
17:10:36 172.31.27.177     64k     2k      125m        0.08s   1638.52      40.00       0.03
17:10:36 172.31.27.177     1m      200     200m        0.06s   3536.57     296.49       0.00
17:10:36 172.31.27.177     fi_rma_bw: prov/util/src/util_buf.c:220: ofi_bufpool_destroy: Assertion `(pool->attr.flags & OFI_BUFPOOL_NO_TRACK) || (buf_region->use_cnt == 0)' failed.
17:10:36 172.31.27.177     bash: line 1: 28844 Aborted                 /home/ec2-
```

**Comment by rajachan** [comment]
That does look like a real failure. @zhngaj can you test this PR manually and see if you can reproduce it?

**Comment by zhngaj** [comment]
Doing it right now.

**Comment by zhngaj** [comment]
I'm not able to reproduce this error.

**Comment by rajachan** [comment]
The assertion is pointing to a leak, a bufpool entry that probably hasn't been returned to the pool. I don't think it is related to Sean's PR either, but something we can look at more closely internally.

**Pull request merged**
