### PR TITLE
use new synapse api

### PR DESCRIPTION
**Pull request by imasuari**
synapse-ai API now expose the base address we need directly, making the code more clean and simplified

### CODE REVIEW

**Comment by imasuari** [comment]
@nbeer-habana

**Review by j-xiong — COMMENTED** [review]
The changes look good to me. There is a question though, the implementation of the get_dmabuf_fd method is different from the one in libfabirc (src/hmem_synapseai.c). What is the difference between the two?

**Comment by zachdworkin** [comment]
@imasuari it looks like one of our nodes was stuck in a bad state. I am rebooting it and will re-run your PR.

**Comment by shijin-aws** [comment]
> The changes look good to me. There is a question though, the implementation of the get_dmabuf_fd method is different from the one in libfabirc (src/hmem_synapseai.c). What is the difference between the two?

I was asking the same question last time. But they intend to do that to keep backward compatibility?

**Review by j-xiong — APPROVED** [review]

**Pull request merged**
