### PR TITLE
prov/rxm: Implement static connections support

### PR DESCRIPTION
**Pull request by dmitrygx**

### CODE REVIEW

**Comment by dmitrygladkov** [comment]
This is draft implementation - for manual progress only + the PR requires some refactoring.

The first commit is ready and can be reviewed by community.

@shefty @alexander-sannikov

**Comment by dmitrygladkov** [comment]
The PR has been refactored and updated to support static connections for auto progress.
The description for the commits will be added today later.

**Comment by dmitrygladkov** [comment]
@a-ilango @shefty @alexander-sannikov Could you take a look into the patch, please? We don't want these changes in the 1.7.

**Comment by a-ilango** [comment]
@dmitrygladkov Thanks for the patches. A few questions / suggestions:
1. Do we need a comprehensive cmap state change subscription functionality? We could just call the function that updates the wait list when a cmap handle transitions to "connected" state. We can check if the handle is part of a wait list (handle is being tracked for state changes) to determine if we need to call the function. 
2. I think we may be able avoid adding multiple progress_fd to epoll_wait if we do something like:
    1. Maintain a list of tracked handles in `cmap->wait_list` (this is already being done).
    2. Maintain a list of cmap with tracked handles in `rxm_av->cmap_list`
    3. When a tracked handle transitions to connected state we remove it from `cmap->wait_list`
    4. If we find both `cmap->wait_list` and `rxm_av->cmap_list` to be empty, we can signal `rxm_av->conn_wait_fd` to wake up the app thread waiting on it in av insert.
    5. With the above in place, for auto progress polling on `rxm_av->conn_wait_fd` alone should be sufficient. Only for manual progress we would have to poll the EQ fd as well to progress connections. 
3. If it's not being done already, we would also need to track when a connection is rejected and return error on av insert.

**Comment by dmitrygladkov** [comment]
> 1. Do we need a comprehensive cmap state change subscription functionality? We could just call the function that updates the wait list when a cmap handle transitions to "connected" state. We can check if the handle is part of a wait list (handle is being tracked for state changes) to determine if we need to call the function.

This functionality can be used to implement error handling during static connection establishment, i.e. to cover the following item: 

> 3. If it's not being done already, we would also need to track when a connection is rejected and return error on av insert.

Also this functionality can be re-used by logging subsystem to log RxM connection state changes.

What do you think?

> 2. I think we may be able avoid adding multiple progress_fd to epoll_wait if we do something like:
Maintain a list of tracked handles in cmap->wait_list (this is already being done).
Maintain a list of cmap with tracked handles in rxm_av->cmap_list
When a tracked handle transitions to connected state we remove it from cmap->wait_list
If we find both cmap->wait_list and rxm_av->cmap_list to be empty, we can signal rxm_av->conn_wait_fd to wake up the app thread waiting on it in av insert.

This requires `struct rxm_av` implemented to contain the cmap_list (it must be allocated on the heap) and fd, and it is applicable only for auto-progress mode. This will save `(EP cnt - 1)` file descriptors and `(EP cnt) - 1` epoll events generated for each AV insert. Do we really need it?
But if you prefer the implementation with lists proposed by you, I'm ok to implement it :)

**Comment by a-ilango** [comment]
I guess as long as the subscription feature doesn't had too much overhead (when compared to alternatives) and complexity we can add it.

> it is applicable only for auto-progress mode

That's a good point.

Since when using static connections, all the connections get established during AV insertion, we could run the "auto-progress connection thread", `rxm_conn_progress` instead. We wouldn't have the thread overhead during data transfer as it's going to be sleeping unless there's a connection disconnect (which is supposed to happen only at the end of the job). Does this make the implementation simpler? What do you think?

**Comment by shefty** [comment]
Whatever solution is added, please keep this as simple as possible and reuse the code where you can.  The utility providers are ending up with very complex implementations.

**Comment by dmitrygladkov** [comment]
> Since when using static connections, all the connections get established during AV insertion, we could run the "auto-progress connection thread"
> Does this make the implementation simpler? What do you think?

This makes sense to me, but the following 

> there's a connection disconnect (which is supposed to happen only at the end of the job)

will be broken in case of imbalance of job termination/finalization, for example:
rank 0 calls `fi_close(RxM::EP)` while rank 1 polling network events (`fi_cq_read(RxM::CQ)`). It will lead that the CM thread of rank 1 closes the `MSG::EP` while the application thread calling `fi_cq_read(MSG::CQ)` (the `MSG::EP` is tied with this `MSG::CQ`). So, this is the data race, because there is an parallel access to the OFI resource (`MSG::EP` and/or `MSG::EP` -- depends on provider implementation) from several threads at the same time.

**Comment by a-ilango** [comment]
> So, this is the data race, because there is an parallel access to the OFI resource (MSG::EP and/or MSG::EP -- depends on provider implementation) from several threads at the same time.

This is related to FI_THREAD_DOMAIN, right? Isn't this already being handled in auto-progress? Don't we save MSG EP to be closed in a list?

**Comment by dmitrygladkov** [comment]
> This is related to FI_THREAD_DOMAIN, right?

Yep, you're right.

> Isn't this already being handled in auto-progress? Don't we save MSG EP to be closed in a list?

Yes, RxM does it. I forgot this fact.

I'll take a look into enabling auto-progress for the static connections case. It seems to be a good idea!

**Comment by shefty** [comment]
I'm concerned about the complexity of what's being added here, especially given that the cmap is already one of the more complex components of the provider.  What is driving the requirement for static connections?

The API allows receiving data from a peer without an address being in the local AV.  This can occur simultaneous with addresses being inserted.  Also, all addresses may not be inserted at once, so traffic could be occurring over some connections (inserted previously) while new addresses are being inserted.  Does the code try to handle these situations?

**Comment by dmitrygladkov** [comment]
> Does the code try to handle these situations?

These situations are not handled in this code. But RxM cmap is designed to cover it.

> What is driving the requirement for static connections?

This is more for the micro-benchmarks w/o warm-up mechanism (the fi iterations show poor performance). Also this fixes the case when a user runs OFI instances on all logical CPU cores -- the startup takes too much time in this case, because application thread burns CPU cycles calling `fi_cq_read` instead of establishing (accepting incoming connection requests in CM thread) connections.

**Comment by shefty** [comment]
Old PR that hasn't been updated in some time with conflicts.  Closing.

**Pull request closed without merging**
