### PR TITLE
travis: fix the default Travis CI build logic

### PR DESCRIPTION
**Pull request by goodell**
I have no experience with Travis, but the docs here indicate my patch
should improve our simple build test:

- http://docs.travis-ci.com/user/customizing-the-build/
- http://docs.travis-ci.com/user/languages/c/

Signed-off-by: Dave Goodell <dgoodell@cisco.com>

@shefty please review

### CODE REVIEW

**Comment by shefty** [comment]
The more fixes the merrier!  See #1344 and #1343

**Comment by shefty** [comment]
Do we want to keep the 'make test' option in #1343, or just do the make install?

**Comment by bturrubiates** [comment]
I kinda have experience doing this, I did the initial setup for the Travis instance that the GNI provider is using.  Is the eventual goal to include tests as well, or just test that something doesn't break the build?

**Comment by shefty** [comment]
IMO, the goal is to include as much testing as reasonable.  E.g. we're looking at running fabtests/scripts/runfabtests.sh.

**Comment by shefty** [comment]
I merged the relevant portions of this request with #1343.  Closing this and merging the other, so we at least have something that works.  We can expand testing from there.

**Pull request closed without merging**
