### PR TITLE
prov/shm: use spin lock in smr_region

### PR DESCRIPTION
**Pull request by wzamazon**
Previous commit switched to use mutex lock in smr_region,
which has resulted performance degration on various OS.
The degradation is most observable on CentOS 7 and CentOS 8.
For certain workload, the performance can degrade up to 30%.

To addres the issue, this patch switch back to use spinlock
in smr_region.

Signed-off-by: Wei Zhang <wzam@amazon.com>

### CODE REVIEW

**Comment by wzamazon** [comment]
The mac os build failure is because there is no spinlock on Mac OS. I need to look into how we dealt the issue previously.

**Comment by shefty** [comment]
The previous code used the term fastlock, which a configure check that either implemented fastlock as a spinlock or mutex.  However, I think it may be better to implement the needed calls in include/osx/pthread.h.  See include/windows/pthread.h.  If pthread.h exists on osx, we can add the defines into osx/osd.h.

**Comment by shefty** [comment]
Btw, I'm analyzing the shm provider locking now to see if there's a simple solution, like moving to a single provider lock.

**Comment by wzamazon** [comment]
@shefty 

> However, I think it may be better to implement the needed calls in include/osx/pthread.h.
> See include/windows/pthread.h. If pthread.h exists on osx, we can add the defines into osx/osd.h.

I see. I added a patch that implements pthread_spinlock on mac OS X using `os_unfair_lock` (provided by Mac OS X).

Because pthread.h already exists on Mac OS X, I put it in `include/macos/osd.h`.

**Review by shefty — APPROVED** [review]
Looks good -- I'm still hoping to update the util code to allow spinlocks, so that those changes can be merged with these.

Btw, I think switching back to spinlocks makes the provider susceptible to starvation.

**Comment by shefty** [comment]
See #7439 - which provides the basis for switching from a mutex to spinlock for the util domain and eventually util cq.

**Review by aingerson — APPROVED** [review]

**Comment by shefty** [comment]
I've pulled the 2 commits from this PR into #7439 and resolved the conflicts there.

**Pull request closed without merging**
