### PR TITLE
[v1.9.x] prov/shm: fix a memory leak

### PR DESCRIPTION
**Pull request by wzamazon**
This patch release smr_ep->ep_name in smr_ep_close()

Signed-off-by: Wei Zhang <wzam@amazon.com>

### CODE REVIEW

**Comment by shefty** [comment]
Are the AWS failures expected for 1.9?

**Comment by rajachan** [comment]
The sporadic master fi_rma_bw issue with EFA multi-node runs seem to be happening only in the CI.  We have had no luck reproducing it outside of it so far, but still continuing to look at it. 

The shm one here with 1.9.x is new. @zhngaj I don't think we have seen this before, right?

**Comment by wzamazon** [comment]
bot:aws:retest

**Comment by hppritcha** [comment]
bot:lanl:retest

**Comment by shefty** [comment]
Only AWS failure is the fi_rma_bw one.

**Pull request merged**
