### PR TITLE
move rx/tx size_left code to basic ep ops

### PR DESCRIPTION
**Pull request by goodell**
Per @shefty's request in #539

### CODE REVIEW

**Comment by shefty** [comment]
thanks - looks good to me.  I'll wait a bit to let others comment before merging.

**Comment by sayantansur** [comment]
Sorry haven't followed this thread closely. How does a provider indicate that it wants to use the EAGAIN model instead of the credits? Is it legal to point the size_left routines to return ENOSYS, and the app will have adjust to EAGAIN model?

**Comment by shefty** [comment]
Returning ENOSYS should work.

**Comment by goodell** [comment]
AIUI, apps should always be able to ignore the size_left functions and rely on `FI_EAGAIN` being returned from the rx/tx routines.

**Comment by shefty** [comment]
I think his question is that the provider doesn't know if the app is going to call rx/tx size left, so it must perform the accounting in case it is called.  Returning ENOSYS allows the provider to indicate that it does not do this accounting.  An app can check this up front.

**Comment by goodell** [comment]
@shefty agreed

**Comment by sayantansur** [comment]
Sounds good to me.

**Pull request merged**
