### PR TITLE
[v1.19.x] hmem/synapseai: Refine the error handling and warning

### PR DESCRIPTION
**Pull request by shijin-aws**
backport https://github.com/ofiwg/libfabric/pull/9523

### CODE REVIEW

**Review by wenduwan — APPROVED** [review]

**Review by j-xiong — APPROVED** [review]

**Comment by shijin-aws** [comment]
tcp provider test has a failure in AWS CI.

```
server_command: ssh -n -o StrictHostKeyChecking=no -o ConnectTimeout=30 -o BatchMode=yes 172.31.36.135 'timeout 360 /bin/bash --login -c '"'"'/home/ubuntu/PortaFiducia/build/libraries/libfabric/pr9579-debug/install/fabtests/bin/fi_cq_data -e rdm -o senddata -p tcp -s 172.31.36.135'"'"''

client_command: ssh -n -o StrictHostKeyChecking=no -o ConnectTimeout=30 -o BatchMode=yes 172.31.43.66 'timeout 360 /bin/bash --login -c '"'"'/home/ubuntu/PortaFiducia/build/libraries/libfabric/pr9579-debug/install/fabtests/bin/fi_cq_data -e rdm -o senddata -p tcp -s 172.31.43.66 172.31.36.135'"'"''
client_stdout:
Posting send with CQ data: 0x123456789abcdef
Done

client returncode: 0
server_stdout:
Waiting for CQ data from client
remote_cq_data: success
fi_cq_data_entry.len verify: success
timeout: the monitored command dumped core

server returncode: 255
```

Not related to this PR. Do you know if it is a known issue? @j-xiong

**Comment by j-xiong** [comment]
@shijin-aws not aware of this. Is it failing for all the builds or just a specific one?

**Comment by shijin-aws** [comment]
Just a specific one.

**Comment by shijin-aws** [comment]
bot:aws:retest

**Comment by j-xiong** [comment]
The ucx failure is a known issue and is unrelated.

**Pull request merged**
