### PR TITLE
[v1.16.x] contrib/intel/jenkins: Update with files from main

### PR DESCRIPTION
**Pull request by j-xiong**
Old files don't work properly with current CI infrastructure. The difference between the branch and main is too big to cherry-pick.

The v1.16.x branch doesn't support dsa. The jenkins scripts have some dsa related code but they are inactive.

### CODE REVIEW

**Comment by j-xiong** [comment]
@shefty This is similar to #8851 
@zachdworkin Could you also force it to test with Jenkinsfile from the PR?

**Comment by zachdworkin** [comment]
@j-xiong @shefty Yes, its going now.

**Comment by aingerson** [comment]
@shefty It looks like the runmultinode.sh script is missing from Makefile.am

**Comment by shefty** [comment]
The simplest option looks like removing references to multinode from the updated config files.

**Comment by aingerson** [comment]
@shefty I think the simplest option would be to try to add the script to the makefile....

**Comment by shefty** [comment]
Here's the commit that added multinode.sh to the Makefile.am.

https://github.com/ofiwg/libfabric/commit/8d3150b2ffb3274d4c5e30b3cc15e75b5cffe316

We would likely need to bring in the changes to multinode.sh as well.  Hopefully pulling in the lastest file would work.

**Comment by zachdworkin** [comment]
@j-xiong do you need me to do the jenkins "magic" again?

**Comment by j-xiong** [comment]
@zachdworkin Yes. Thanks!

**Comment by j-xiong** [comment]
@zachdworkin Looks like the new "magic" runs didn't include the newly added commit (12ee75c).

**Comment by j-xiong** [comment]
Tests passed. No need to wait for the ubuntu 18.04 builds (will backport more fixes to remove old ubuntu versions).

**Pull request merged**
