### PR TITLE
Just use a generic function to return ENOSYS for unimplemented.

### PR DESCRIPTION
**Pull request by pmmccorm**
No need for libfabric.so to ship dozens of empty function defs.

Signed-off-by: pmmccorm <patrick.m.mccormick@intel.com>

### CODE REVIEW

**Comment by shefty** [comment]
Isn't this using an obsolete feature of C?  Did the compiler not give any warnings for this?

**Comment by pmmccorm** [comment]
Compiles without warning with CFLAGS="-Wall" so I don't think so?

**Comment by jsquyres** [comment]
It's surprising to me that it compiles without warning. 

@goodell You're a C standards guy... is this kosher?

**Comment by pmmccorm** [comment]
I tried it with gcc 4.9.1, CFLAGS= -Wall and
-std=c99
-std=c11
(no std specified-- defaults to something like --std=gnu99)

No warnings except for some related to using asm and typeof (should probably change those in another commit).

Adding -Wextra and -pedantic trigger a bunch of errors all over the place elsewhere.

What we really want is:
```
int fi_enosys(...);
```

But that is forbidden by standard.

There is probably some reason why this hole in the type system is kept having to do with linking/calling to externally defined functions that I can't think of right now..

**Comment by bturrubiates** [comment]
I'm not sure why this compiles without warnings but an empty declarator list has been deprecated in both C99 and C11. 

[c99](http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1256.pdf): section 6.11.6
[c11](http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1570.pdf): section 6.11.6

**Comment by pmmccorm** [comment]
It is described as an "obsolescent feature", which is defined as (in introduction):

```
  Certain features are obsolescent  which means that they   may be considered for
withdrawal in future revisions of this International Standard.  They are retained because
of their widespread use, but their use in new  implementations (for implementation
features) or new programs (for language [6.11] or library features [7.31]) is discouraged.
```

So it is not deprecated (will be removed in a future language standard), just discouraged..

**Comment by bturrubiates** [comment]
That's fair, but that probably means we should investigate other options.

**Comment by goodell** [comment]
I'd prefer to leave it as-is.  The current approach doesn't seem to be causing much harm, just a slight increase the the source+binary sizes.

**Comment by shefty** [comment]
My preference is to leave it as is as well.  But I can see the use for a function that checks whether a provider has implemented a specific function or not.  This change could make that possible.

**Pull request closed without merging**
