### PR TITLE
prov/tcp: Handle emulated epoll support

### PR DESCRIPTION
**Pull request by shefty**
We can't get an epoll fd if we don't have real support for epoll.  Update the epoll abstraction and tcp provider to handle the emulated epoll case.

### CODE REVIEW

**Comment by thomasgillis** [comment]
this PR addresses #8847 
thanks @shefty

**Comment by shefty** [comment]
bot:aws:retest

**Comment by shefty** [comment]
Can someone from AWS report what the CI failure is?

**Comment by shefty** [comment]
bot:aws:retest

**Comment by raffenet** [comment]
@shefty this should be backported to v1.18.x. There is a small conflict when cherry-picking that I'm not confident how to fix, so your help would be appreciated.

**Comment by shefty** [comment]
@raffenet - I'll cherry pick.  It's not needed prior to v1.18, as that was using the older tcp implementation.

**Pull request merged**
