### PR TITLE
[v1.17.x] prov/efa: back port recent changes

### PR DESCRIPTION
**Pull request by wzamazon**
[prov/efa: compare pci bus id in hints](https://github.com/ofiwg/libfabric/commit/6b9c85df7f008bb8ddbda8bc22e0a31520b09460)

[prov/efa: avoid unnecessary copy when sending data from shm](https://github.com/ofiwg/libfabric/commit/530d9f93a057c8f9c251a41add0539084a5e8721)

[prov/efa: unit test to verify no copy with shm for small host message](https://github.com/ofiwg/libfabric/commit/92734d0bbdca2e601d37c5a37bbda6478a76393b)

### CODE REVIEW

**Comment by shijin-aws** [comment]
AWS CI failure seems real.

**Comment by darrylabbate** [comment]
> AWS CI failure seems real.

I have a g4dn cluster already set up so I'll attempt to reproduce this for Wei

**Comment by wzamazon** [comment]
bot:aws:retest

**Comment by wzamazon** [comment]
bot:aws:retest

**Pull request merged**
