### PR TITLE
[v1.18.x] prov/efa: Handle RNRs from RDMA writedata

### PR DESCRIPTION
**Pull request by sunkuamzn**
Re-implementation of the changes in https://github.com/ofiwg/libfabric/pull/9276 for 1.18.x branch

### CODE REVIEW

**Review by shijin-aws — APPROVED** [review]

**Comment by lrbison** [comment]
Intel: I see in the Intel CI the following error during windows build:

```
error sending AppVeyor compilation message: The remote server returned an error: (500) Internal Server Error.
```

Should we restart the CI or is this a known failure path?

**Comment by sunkuamzn** [comment]
`Image: Visual Studio 2017; Configuration: Release-v141` passed but `Image: Visual Studio 2017; Configuration: Debug-v141` failed. @shefty can you confirm if the failure is real?

**Comment by shijin-aws** [comment]
>loss of data (compiling source file prov\util\src\util_mr_map.c) [C:\projects\libfabric\libfabric.vcxproj]
c:\projects\libfabric\include\ofi_mem.h(258): warning C4267: 'function': conversion from 'size_t' to 'int16_t', possible loss of data (compiling source file prov\util\src\util_mr_map.c) [C:\projects\libfabric\libfabric.vcxproj]
Error sending AppVeyor compilation message: The remote server returned an error: (500) Internal Server Error.
  Message: 'function': conversion from 'uint64_t' to 'int', possible loss of data (compiling source file prov\util\src\util_mr_map.c)
  Category: Warning
  Code: C4244
  File: c:\projects\libfabric\include\ofi_mem.h
  Line: 291
  Column: 
  Project name: libfabric

Doesn't seem to be relevant to this change

**Comment by shijin-aws** [comment]
I tested it on p5 and it works

**Pull request merged**
