### PR TITLE
contrib/intel/jenkins: add CI support for net provider

### PR DESCRIPTION
**Pull request by ooststep**
The intent is to match the current TCP validations and to eventually merge the two.
It is understood that this will increase runtimes.

### CODE REVIEW

**Comment by ooststep** [comment]
@zachdworkin @Juee14Desai can you please take a look, not sure why it won't let me add you as reviewers.

**Review by aingerson — APPROVED** [review]

**Comment by shefty** [comment]
Has a bunch of CI failures

**Comment by shefty** [comment]
This shows up in a couple MPI failures:
```
MPIDI_OFI_mpi_init_hook(1552): OFI fi_getinfo() failed (ofi_init.c:1552:MPIDI_OFI_mpi_init_hook:No data available)
```
We'll need to run the MPI's manually to figure out what their requirements are and how net differs from rxm.

**Comment by shefty** [comment]
If we have to drop MPI testing for now, so that we can start getting some CI coverage, that would be okay.  We can work to add MPI testing as a follow on.

**Comment by shefty** [comment]
@ooststep - this is good to go for now, correct?

**Review by zachdworkin — APPROVED** [review]

**Pull request merged**
