### PR TITLE
util: cherry-picked fix for check_ep_attr

### PR DESCRIPTION
**Pull request by shefty**
Derived from PR #3287

### CODE REVIEW

**Comment by shefty** [comment]
This was picked from the v1.5.x branch, so I'm guessing the same error may appear there.

**Comment by j-xiong** [comment]
I will work on verifying the 1.5.x branch after the test on 1.4.x is done. It probably has part of the issue.

**Comment by j-xiong** [comment]
verified with fabtests 1.4.1 after applying my additional patch.

**Comment by shefty** [comment]
I dropped the psm changes to this PR.  Can you open a new PR against v1.4.x with an updated patch?

**Comment by j-xiong** [comment]
That sounds good. It's probably easier to do the same thing for the 1.5.x branch.

**Pull request merged**
