### PR TITLE
[v1.11.x] cherry-picked fixes from master for v1.11.2 release

### PR DESCRIPTION
**Pull request by shefty**

### CODE REVIEW

**Comment by raffenet** [comment]
@shefty make sure to grab thsi one otherwise my fabtest fix is incomplete: https://github.com/ofiwg/libfabric/pull/6366/commits/7737e522fc8a7e5f115cda2969e0238979367b37

**Comment by shefty** [comment]
@raffenet -- thanks, I'll pick that one too

**Comment by shefty** [comment]
PR rebased to pick up travis CI config changes.  All other CIs had passed.  No other changes have been made.  Should be okay to merge once travis passes.

**Comment by shefty** [comment]
Or I'll merge a broken travis.yml file and it won't run at all...

**Pull request merged**
