### PR TITLE
prov/efa: let rxr_pkt_post() post multiple medium RTM packets

### PR DESCRIPTION
**Pull request by wzamazon**
When posting medium RTM packets, multiple packets need to
be posted at the same time.

In a recent commit eef3ecffa, rxr_pkt_post() was simplified to
always post 1 packet. The handling of medium RTM packets was
moved to rxr_pkt_post_req(), which will queue medium RTM
if -FI_EAGAIN is encountered during posting packets. The
progress engine will resend.

This caused an issue because progress engine uses rxr_pkt_post()
to send packets. When a medium RTM is queued, multiple packets
need to be sent, but rxr_pkt_post() will only send one.

To address this issue, this patch made the following changes:

1. It introduce rxr_pkt_post_one(), which will post 1 packet.

2. It moved the handling of medium RTM packets from rxr_pkt_post_req()
   to rxr_pkt_post(), so rxr_pkt_post() can send multiple medium
   RTM packets.

The comments of each function were updated accordingly.

Signed-off-by: Wei Zhang <wzam@amazon.com>

### CODE REVIEW

**Review by shijin-aws — APPROVED** [review]

**Comment by shijin-aws** [comment]
where is `op_entry->queued_ctrl_entry` updated when the packets are queued?

**Comment by wzamazon** [comment]
> where is op_entry->queued_ctrl_entry updated when the packets are queued?

Prior to this change, both `rxr_pkt_post_or_queue` 

https://github.com/ofiwg/libfabric/blob/14d812194f9c1494a57d7f77130c4abb1707e376/prov/efa/src/rxr/rxr_pkt_cmd.c#L343

and `rxr_pkt_post_req` 

https://github.com/ofiwg/libfabric/blob/14d812194f9c1494a57d7f77130c4abb1707e376/prov/efa/src/rxr/rxr_pkt_cmd.c#L392

can put a tx_entry to `ep->queued_ctrl_list`.

After this change, `rxr_pkt_post_req` calls `rxr_pkt_post_or_queue`. So only `rxr_pkt_post_or_queue` can put tx_entry to `ep->queued_ctrl_list`.

**Comment by shijin-aws** [comment]
I am actually ask where `tx_entry->queued_ctrl_entry`  is actually assigned.

**Comment by shijin-aws** [comment]
Previous comment is  addressed via offline discussion.

**Comment by wzamazon** [comment]
This is pure EFA change, so ignore intel CI failure.

**Pull request merged**
