### PR TITLE
[V1.19.x] prov/efa,shm: backport the fix for SHM's 0 byte SAR and EFA's tx/rx op flags

### PR DESCRIPTION
**Pull request by shijin-aws**
This PR backports https://github.com/ofiwg/libfabric/pull/9203 and https://github.com/ofiwg/libfabric/pull/9200 to v1.19.x

### CODE REVIEW

**Review by wenduwan — APPROVED** [review]

**Review by aingerson — APPROVED** [review]

**Comment by zachdworkin** [comment]
@shijin-aws yes please. It should just be the one commit

**Comment by shijin-aws** [comment]
@zachdworkin I ingested that patch, but the Intel CI still failed?

**Comment by zachdworkin** [comment]
@shijin-aws I corrected it for you. The rerun should pass (assuming the changes in the PR dont cause test failures)

**Comment by shijin-aws** [comment]
sorry, i see the CI is running and those "failed" status will be updated after the CI finishes

**Pull request merged**
