### PR TITLE
 prov/udp: Fix build warnings

### LINKED ISSUE #3370: prov/udp: build warnings on windows
from appveyor build logs:

prov\udp\src\udpx_ep.c(46): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data [C:\projects\libfabric\libfabric.vcxproj]
prov\udp\src\udpx_ep.c(63): warning C4267: '=': conversion from 'size_t' to 'socklen_t', possible loss of data [C:\projects\libfabric\libfabric.vcxproj]
prov\udp\src\udpx_ep.c(79): warning C4133: 'function': incompatible types - from 'ip_mreq *' to 'const char *' [C:\projects\libfabric\libfabric.vcxproj]
prov\udp\src\udpx_ep.c(134): warning C4133: 'function': incompatible types - from 'ip_mreq *' to 'const char *' [C:\projects\libfabric\libfabric.vcxproj]
prov\udp\src\udpx_ep.c(297): warning C4244: '=': conversion from 'ssize_t' to 'int', possible loss of data [C:\projects\libfabric\libfabric.vcxproj]
prov\udp\src\udpx_ep.c(378): warning C4244: 'function': conversion from 'fi_addr_t' to 'int', possible loss of data [C:\projects\libfabric\libfabric.vcxproj]
prov\udp\src\udpx_ep.c(400): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data [C:\projects\libfabric\libfabric.vcxproj]
prov\udp\src\udpx_ep.c(401): warning C4389: '==': signed/unsigned mismatch [C:\projects\libfabric\libfabric.vcxproj]
prov\udp\src\udpx_ep.c(418): warning C4244: 'function': conversion from 'fi_addr_t' to 'int', possible loss of data [C:\projects\libfabric\libfabric.vcxproj]
prov\udp\src\udpx_ep.c(442): warning C4267: '=': conversion from 'size_t' to 'socklen_t', possible loss of data [C:\projects\libfabric\libfabric.vcxproj]
prov\udp\src\udpx_ep.c(501): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data [C:\projects\libfabric\libfabric.vcxproj]
prov\udp\src\udpx_ep.c(502): warning C4244: 'function': conversion from 'fi_addr_t' to 'int', possible loss of data [C:\projects\libfabric\libfabric.vcxproj]
prov\udp\src\udpx_ep.c(503): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data [C:\projects\libfabric\libfabric.vcxproj]
prov\udp\src\udpx_ep.c(504): warning C4389: '==': signed/unsigned mismatch [C:\projects\libfabric\libfabric.vcxproj]
prov\udp\src\udpx_ep.c(514): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data [C:\projects\libfabric\libfabric.vcxproj]
prov\udp\src\udpx_ep.c(515): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data [C:\projects\libfabric\libfabric.vcxproj]
prov\udp\src\udpx_ep.c(516): warning C4389: '==': signed/unsigned mismatch [C:\projects\libfabric\libfabric.vcxproj]
prov\udp\src\udpx_ep.c(725): warning C4244: '=': conversion from 'SOCKET' to 'int', possible loss of data [C:\projects\libfabric\libfabric.vcxproj]
  Compiling...
  udpx_fabric.c

### PR DESCRIPTION
**Pull request by gladkovdmitry17**
Fixes #3370

### CODE REVIEW

**Comment by shefty** [comment]
This breaks the Linux build.  Likely just a missing include file.

**Comment by gladkovdmitry17** [comment]
> This breaks the Linux build. Likely just a missing include file.

I should add the changes to `includeunix/osd.h` file. I've pushed the changes to the GitHub and then someone has interrupted me and as a result I forgot about this PR :)
Sorry for delaying. I've pushed the updates to unix's `osd.h`

**Comment by shefty** [comment]
Thanks - You do realize that we don't expect real-time responses and immediate fixes, right?  :)

**Comment by gladkovdmitry17** [comment]
> Thanks - You do realize that we don't expect real-time responses and immediate fixes, right?

Sure :)
Seems, I need to delete the corporate email from my phone

**Pull request merged**
