### PR TITLE
prov/rxm: Fix handling of RX buffer from unexpected queue in SAR

### PR DESCRIPTION
**Pull request by dmitrygladkov**
Signed-off-by: Dmitry Gladkov <dmitry.gladkov@intel.com>

### CODE REVIEW

**Comment by a-ilango** [comment]
> This fixes case when several SAR requests are in-flight and some segments are
re-transmitted due to lack of resources in TX queue. The segments from different
SAR requets can be mixed and it leads to unexpected behavior

If they're scheduled for re-transmission shouldn't that be done in order? Any new tx request should wait until the deferred requests have been progressed.

**Comment by dmitrygladkov** [comment]
> Any new tx request should wait until the deferred requests have been progressed.

This is not a case for messages > eager size. I'll add the deferred queue support for SAR, Rendezvous

**Comment by a-ilango** [comment]
> This is not a case for messages > eager size. I'll add the deferred queue support for SAR, Rendezvous

IIUC, would you be handling ordering (in the context of deferred queue) correctly instead of the fix in this PR?

**Comment by dmitrygladkov** [comment]
Since we are going to remove deferred queue, it handles case when several messages can be processed simultaneously and adds support of providers that doesn't ensure correct ordering, e.x. RxM doesn't rely on ordering of received segments

**Comment by shefty** [comment]
Is this PR ready?

**Comment by a-ilango** [comment]
This seems okay but should probably add a comment. I can add the changes along with a comment in a new PR.

**Comment by a-ilango** [comment]
I've opened PR #4314 which adds a comment to the changes.

**Pull request closed without merging**
