### PR TITLE
tcp + rxm

### PR DESCRIPTION
**Pull request by shefty**
Series of patches targeting rxm + tcp scaling and performance.

- rxm: reduce the default rx/tx sizes, but keep the same max supported value
- rxm: fix check for tcp core provider to ensure srx is used
- tcp: rework use of receive side staging buffer, add send side staging

As part of the changes, introduce 2 new common abstractions. Byte queue is used to implement staging, or bounce buffer, for sockets. The goal is to reduce the number of kernel calls and coalesce iovs for small message transfers for both sends and receives. The send side staging buffer is only used after getting pushback from the kernel accepting new data. The receive side buffer replaces the existing tcp staging buffer, with a tweaked algorithm. The receive buffer is used as a prefetch buffer when only a small amount of data needs to be received.

The second abstraction, called a buffered socket, is just a set of helper functions for using the byte queue with socket send/recv calls. This pushes the staging buffers away below a set of simple socket-like send/recv calls, removing the management of the buffer out of the provider. This will make it easier to adjust the algorithms that are used.

The performance impact of these changes still needs to be determined. (In a few simple benchmark runs, it didn't make things better or worse, but the run to run variation is huge).

Fixed tx progress to flush queued data even if no outstanding operations are pending.

### CODE REVIEW

**Comment by shefty** [comment]
Preliminary results show significant improvements on bandwidth tests for transfers under 4k.  The 4k threshold makes sense since the default buffer sizes and algorithm use that as a cut-off.

with staging buffers:
```
./fi_msg_bw -p tcp -s n8 n7
bytes   iters   total       time     MB/sec    usec/xfer   Mxfers/sec
64      20k     1.2m        0.05s     25.23       2.54       0.39
256     20k     4.8m        0.05s     98.96       2.59       0.39
1k      20k     19m         0.09s    235.54       4.35       0.23
4k      20k     78m         0.18s    451.29       9.08       0.11
64k     2k      125m        0.12s   1068.85      61.31       0.02
1m      200     200m        0.19s   1120.69     935.65       0.00
```

newer code, but staging buffers sizes set to 0
```
./fi_msg_bw -p tcp -s n8 n7
bytes   iters   total       time     MB/sec    usec/xfer   Mxfers/sec
64      20k     1.2m        0.08s     15.50       4.13       0.24
256     20k     4.8m        0.08s     60.68       4.22       0.24
1k      20k     19m         0.11s    185.56       5.52       0.18
4k      20k     78m         0.18s    450.12       9.10       0.11
64k     2k      125m        0.12s   1092.11      60.01       0.02
1m      200     200m        0.19s   1120.40     935.90       0.00
```

I don't see any impact on pingpong latency either way, but the run to run variation there is huge.

**Comment by shefty** [comment]
I'm begging to think that the AWS CI just doesn't like me.

**Review by ooststep — APPROVED** [review]

**Comment by shefty** [comment]
bot:aws:retest

**Comment by shefty** [comment]
AWS failures look to be node allocation related.

**Comment by shefty** [comment]
bot:aws:retest

**Comment by shefty** [comment]
bot:aws:retest

**Comment by shefty** [comment]
bot:aws:retest

**Comment by shefty** [comment]
@wzamazon @rwespetal - Can someone please look at the AWS failure?  It's consistently failing both the nccl-multi-node tests for tcp and efa on ubuntu.  The failure is from fi_getinfo.  I've tried restarting several times, but the same error persists.

**Comment by wzamazon** [comment]
@shefty  Looking into it.

**Comment by wzamazon** [comment]
@shefty  the ubuntu test failure is because a system setting: the LD_LIBRARY_PATH was not set correctly on ubuntu, causing fi_info to look for older version of library.

We have ran the nccl test manually and verified this PR passed the test.

We will fix the LD_LIBRARY_PATH issue with the tasing environment soon.

**Comment by shefty** [comment]
@wzamazon - thanks!

**Pull request merged**
