### PR TITLE
v1.20.0

### PR DESCRIPTION
**Pull request by j-xiong**
For CI testing. Don't merge. Will be pushed directly when done.

### CODE REVIEW

**Comment by j-xiong** [comment]
bot:aws:retest

**Comment by j-xiong** [comment]
Getting the same mpichtestsuite error (timeout) over verbs twice:
```
not ok 863 - ./threads/pt2pt/mt_mprobe_sendrecv_huge 2 # time=180.417918205261
```

**Comment by j-xiong** [comment]
bot:aws:retest

**Comment by j-xiong** [comment]
bot:aws:retest

**Comment by shijin-aws** [comment]
AWS CI failure is unrelated.

**Pull request merged**
