### PR TITLE
[cherry-picked] v1.15.x: A beautiful set of fixes from Alexia

### PR DESCRIPTION
**Pull request by shefty**
Fixes to check addr_format, plus updates to the util AV to allocate enough space to store addresses

### CODE REVIEW

**Review by aingerson — APPROVED** [review]
I know you don't need my approval but I do approve of this beautiful set of fixes

**Comment by shefty** [comment]
@aingerson - Does this CI failure look like something this series should have fixed?  Is something missing from the PR?  Or is an exclude needed?
```
name:   fi_multi_ep -e msg -v -p "verbs"
09:29:25    result: Fail
09:29:25    time:   2
09:29:25    server_cmd: /home/cstbuild/ofi-Install/libfabric/ofi_libfabric/PR-7704/1/dbg/bin/fi_multi_ep -e msg -v -p "verbs"   -s ci3-ib0
09:29:25    server_stdout: |
09:29:25      fi_getinfo(): common/shared.c:901, ret=-61 (No data available)
09:29:25    client_cmd: /home/cstbuild/ofi-Install/libfabric/ofi_libfabric/PR-7704/1/dbg/bin/fi_multi_ep -e msg -v -p "verbs"   -s ci4-ib0 ci3-ib0
09:29:25    client_stdout: |
09:29:25      fi_getinfo(): common/shared.c:1692, ret=-61 (No data available)
```

**Comment by aingerson** [comment]
Great question. Looks like the CI in this branch is older and still has the verbs only (no rxm/rxd) testing in it while the other one only tested with rxm or rxd. I thought I tested with just verbs but I guess I didn't test correctly. I'll look into it and either add a fix to let it pass or disable if appropriate.

**Comment by aingerson** [comment]
@shefty see #7707 - should fix the verbs failure

**Comment by shefty** [comment]
bot:aws:retest

**Comment by shefty** [comment]
Removed several patches and disabled fi_multi_ep from runfabtests.sh.  Letting CI run on this smaller set to see if it can pass before adding more patches.

**Comment by wzamazon** [comment]
bot:aws:reteset

**Comment by wzamazon** [comment]
bot:aws:retest

**Pull request merged**
