### PR TITLE
prov/efa: Fix mismanagement of pinned memory after fork()

### PR DESCRIPTION
**Pull request by wckzhang**
Linux copy-on-write semantics mean that following a fork() call,
parent and child processes will have page table entries pointing to
the same physical page. Since these pages are write protected, if
either the parent or child writes to the page, the hardware will
trap the event. The kernel will then allocate a new page and copy
the contents from the original page, breaking the virtual to physical
page link for that process.

To prevent this case, marking pinned memory with MADV_DONTFORK
only allows the memory range to be seen by the parent process, and
the copy-on-write semantics no longer apply to this memory range.

Since the rdma-core library already does all this work for us,
when we add rdma-core, we will move the logic down a layer and
remove it from here.

Signed-off-by: William Zhang <wilzhang@amazon.com>

### CODE REVIEW

**Comment by wzamazon** [comment]
@rajachan Please review

**Comment by rajachan** [comment]
Several tests are failing AWS-CI. Can you take a look @wckzhang ?

**Comment by wckzhang** [comment]
There is an issue regarding page alignment. Huge pages is having some trouble, digging deeper.

**Comment by wckzhang** [comment]
@shefty Can you confirm the Intel CI failures? AWS CI failure is a known, unrelated issue.

**Comment by a-ilango** [comment]
@wckzhang Sean is on vacation until 8/23. You can ignore the Intel CI failure. It's a temporary node issue.

**Pull request merged**
