### PR TITLE
V1.1.x

### PR DESCRIPTION
**Pull request by shefty**

### CODE REVIEW

**Comment by shefty** [comment]
@a-ilango

**Comment by a-ilango** [comment]
The patch "prov/verbs: Make fi_getinfo return -FI_ENODATA..." is empty.

**Comment by shefty** [comment]
Maybe it was already merged in?

**Comment by shefty** [comment]
Checking for changes in the working directory ... done
Importing commit 3d757e9092d04853f81bbdf9ee91654d8e090ae8 ... 
  Log was 66416c3261f5ab5e855a30ae032bb9e3a5476a7b
  Setting log to 66416c3261f5ab5e855a30ae032bb9e3a5476a7b

  Log is now 66416c3261f5ab5e855a30ae032bb9e3a5476a7b
done (empty patch)

**Comment by shefty** [comment]
It must already be there.  Let me drop it.

**Comment by shefty** [comment]
This is the only verbs provider commit then.  Can you provide a patch that updates the man page?

**Pull request merged**
