### PR TITLE
fabtests/rdm_tagged_peek: general code cleanup

### PR DESCRIPTION
**Pull request by shefty**

### CODE REVIEW

**Comment by shefty** [comment]
CI failures:
```
name:   fi_rdm_tagged_peek -p "net"
13:55:44    timestamp: 20221021-205544+0000
13:55:44    result: Fail
13:55:44    time:   2
13:55:44    server_cmd: /home/cstbuild/ofi-Install/libfabric/ofi_libfabric/PR-8142/2/dbg/bin/fi_rdm_tagged_peek -p "net"   -s ci5-eth2
13:55:44    server_stdout: |
13:55:44    client_cmd: /home/cstbuild/ofi-Install/libfabric/ofi_libfabric/PR-8142/2/dbg/bin/fi_rdm_tagged_peek -p "net"   -s ci6-eth2 ci5-eth2
13:55:44    client_stdout: |
13:55:44      free(): invalid pointer
```
That's a different failure from before.
```
name:   fi_recv_cancel -e rdm -V -p "net"
14:00:51    timestamp: 20221021-210045+0000
14:00:51    result: Fail
14:00:51    time:   301
14:00:51    server_cmd: /home/cstbuild/ofi-Install/libfabric/ofi_libfabric/PR-8142/2/dbg/bin/fi_recv_cancel -e rdm -V -p "net"   -s ci5-eth2
14:00:51    server_stdout: |
14:00:51      fi_endpoint(): common/shared.c:745, ret=-98 (Address already in use)
14:00:51    client_cmd: /home/cstbuild/ofi-Install/libfabric/ofi_libfabric/PR-8142/2/dbg/bin/fi_recv_cancel -e rdm -V -p "net"   -s ci6-eth2 ci5-eth2
14:00:51    client_stdout: |
```
This is the same failure.

**Comment by shefty** [comment]
New CI failure, which may help point to the issue:
```
name:   fi_rdm_tagged_peek -p "net"
16:50:57    timestamp: 20221021-235057+0000
16:50:57    result: Fail
16:50:57    time:   2
16:50:57    server_cmd: /home/cstbuild/ofi-Install/libfabric/ofi_libfabric/PR-8142/4/dbg/bin/fi_rdm_tagged_peek -p "net"   -s ci7-eth2
16:50:57    server_stdout: |
16:50:57    client_cmd: /home/cstbuild/ofi-Install/libfabric/ofi_libfabric/PR-8142/4/dbg/bin/fi_rdm_tagged_peek -p "net"   -s ci8-eth2 ci7-eth2
16:50:57    client_stdout: |
16:50:57      FI_PEEK | FI_DISCARD(): functional/rdm_tagged_peek.c:160, ret=-265 (Truncation error)
16:50:57      fi_rdm_tagged_peek: prov/util/src/util_buf.c:256: ofi_bufpool_destroy: Assertion `(pool->attr.flags & OFI_BUFPOOL_NO_TRACK) || !ofi_atomic_get32(&buf_region->use_cnt)' failed.
```
fi_recv_cancel failing same as before.

**Comment by shefty** [comment]
Added fix to rdm_tagged_peek to set the fi_addr correctly.

Added changes to prov/net to fix/improve xfer structure initialization.

**Comment by shefty** [comment]
CI failures were legit.  Changes exposed a missing lock in the srx cleanup.  Though I have no idea why the CI caught the error (hit an assert), but trying to reproduce locally did not.

**Comment by ooststep** [comment]
Good catch! I was able to reproduce this locally, but it took thousands of iterations - very rare. The hardware isn't that significantly different, but I wonder if the speed of the systems was different enough that it was that much more likely in the CI setup.

**Comment by shefty** [comment]
Most CI issues resolved.  Now back to the fi_rdm_tagged_peek assertion listed above.

**Pull request merged**
