### PR TITLE
usnic: fix compiler warnings

### PR DESCRIPTION
**Pull request by jsquyres**
Fix some compiler warnings about possible string truncation.

Signed-off-by: Jeff Squyres <jsquyres@cisco.com>

### CODE REVIEW

**Comment by jsquyres** [comment]
Finally got back after the holidays and have added the `asprintf()` return value check.  Running through CI now...

**Comment by jsquyres** [comment]
@shefty I see what appears to be an unrelated failure in the AWS build in the sockets provider (and the failure may have been a transient failure) -- is there a way to force it to run again?

**Comment by shefty** [comment]
I don't know how to force AWS to re-run without updating the PR.  Is this changed needed for 1.7, because I have the package for that done now and am testing.

**Comment by jsquyres** [comment]
Yes, it would be nice to have this for v1.7, if possible.  I'm happy to create another PR.

I'll force-push a meaningless change to this PR.

**Comment by rajachan** [comment]
bot:aws:retest

**Comment by rajachan** [comment]
Sorry, I've been following along on my phone and assumed it was the one transient sockets failure. For future reference, the keyword I used in the previous comment should retrigger the AWS build.

**Comment by shefty** [comment]
@jsquyres - I've pulled this patch into #4728 and will merge with that.  I'm re-creating the 1.7 package with this fix in.

**Comment by jsquyres** [comment]
Just to close the loop on this PR: there is no v1.7 branch yet.  Merging here on master will likely be good enough to get this in the v1.7.0 release.

**Comment by jsquyres** [comment]
@shefty This time I got different errors on the AWS run:

```
17:40:08 - name:   fi_av_xfer -e dgram -p "sockets"
17:40:08   result: Pass
17:40:08   time:   3
17:40:10 /home/ubuntu/workspace/single-node/PROVIDER/sockets/label/ubuntu/fabtests/install/bin/runfabtests.sh: line 379:  7756 Killed                  ${SERVER_CMD} "${EXPORT_ENV} $s_cmd" &> $s_outp
17:40:10 - name:   fi_cm_data -p "sockets"
17:40:10   result: Fail
17:40:10   time:   2
17:40:10   server_cmd: /home/ubuntu/workspace/single-node/PROVIDER/sockets/label/ubuntu/fabtests/install/bin/fi_cm_data -p "sockets" -s 127.0.0.1
17:40:10   server_stdout: |
17:40:10   client_cmd: /home/ubuntu/workspace/single-node/PROVIDER/sockets/label/ubuntu/fabtests/install/bin/fi_cm_data -p "sockets" -s 127.0.0.1 127.0.0.1
17:40:10   client_stdout: |
17:40:10     connect: Connection refused
17:42:11 - name:   fi_cq_data -e msg -p "sockets"
17:42:11   result: Fail
17:42:11   time:   121
17:42:11   server_cmd: /home/ubuntu/workspace/single-node/PROVIDER/sockets/label/ubuntu/fabtests/install/bin/fi_cq_data -e msg -p "sockets" -s 127.0.0.1
17:42:11   server_stdout: |
17:42:11     fi_listen(): common/shared.c:710, ret=-22 (Invalid argument)
17:42:11   client_cmd: /home/ubuntu/workspace/single-node/PROVIDER/sockets/label/ubuntu/fabtests/install/bin/fi_cq_data -e msg -p "sockets" -s 127.0.0.1 127.0.0.1
17:42:11   client_stdout: |
```

Arrgh.

**Comment by jsquyres** [comment]
bot:aws:retest

**Comment by jsquyres** [comment]
I triggered the AWS retest and then I saw @shefty's comment about him pulling this PR into #4728.

So this PR won't be merged, but we'll get another run in on AWS to see if there is some other sockets error that may need to be addressed...

**Pull request closed without merging**
