### PR TITLE
[v1.17.x] fabtests: Cherry-picked fixes for component tests

### PR DESCRIPTION
**Pull request by j-xiong**

### CODE REVIEW

**Comment by shefty** [comment]
Same as v1.16.x PR, guessing CI scripts must be updated

**Comment by j-xiong** [comment]
There are 20+ commits in main that are not in 1.17.x and many of them can't be cherry-picked easily.  I cherry-picked those with no conflict to see what will happen.

**Comment by shefty** [comment]
We may just need to create a new patch that copies the jenkins scripts

**Comment by j-xiong** [comment]
Hope that CI can pass after #8851 is merged.

**Comment by j-xiong** [comment]
Rebased for CI updates.

**Pull request merged**
