### PR TITLE
Add missing include due to S_IWUSR, etc. use

### PR DESCRIPTION
**Pull request by yurivict**

### CODE REVIEW

**Comment by shefty** [comment]
@yurivict - The commit message needs a signed-off-by line included with it.

**Comment by yurivict** [comment]
How should it look like?

**Comment by shefty** [comment]
As an example, mine would be:
```
Signed-off-by: Sean Hefty <sean.hefty@intel.com>
```
Your patch is trivial, but the signing generally means that you have the right to submit the change under the receiving code's license.

**Comment by shefty** [comment]
Replaced by same change in PR #4895

**Pull request closed without merging**
