### PR TITLE
Check for NULL provider in logging functions.

### PR DESCRIPTION
**Pull request by jimsnow**
Calling log functions in early startup could cause NULL dereference.

(I was unable to reproduce the bug that instigated this change,
but it seems better to err on the side of caution and protect against
this sort of thing anyways.)

Reviewed-by: Sayantan Sur <sayantan.sur@intel.com>
Reviewed-by: Miao Luo <miao.luo@intel.com>
Reviewed-by: Neil Spruit <neil.r.spruit@intel.com>
Reviewed-by: Andrew Friedley <andrew.friedley@intel.com>
Signed-off-by: Jim Snow <jim.m.snow@intel.com>

### CODE REVIEW

**Comment by shefty** [comment]
I would rather check for a NULL provider name when the provider structure is first obtained.  And either fail to handle that provider or point the provider name to a static string.  This avoids needing to have these checks every time a log message is written.

**Comment by jimsnow** [comment]
The bug we ran into was that we had a provider that emitted a log error before a certain global pointer had been set, which resulted in passing NULL into fi_log.  Running checks at some point during initialization might be too late for some arbitrarily early caller of fi_log, which could either pass a NULL provider or one that's not fully initialized.

A reasonable response to that may well be "don't do that then".  In the provider we're working on, I think we probably fixed whatever call to fi_log was causing the crash we were seeing, since I wasn't able to reproduce it.  However, it's possible that sooner or later someone else might trip over the same kind of bug we did, and it might be better for fi_log to be more paranoid about input validation.  I'm fine either way, we just thought it might be worth seeing whether or not you wanted this upstream.

**Comment by shefty** [comment]
IMO, a NULL provider name or NULL structure is a bug in the provider that the framework shouldn't _need_ to handle, especially if it impacts the ability to have logging available, but disabled.  Again, I would be okay with checks in fi_register_provider(), but I would rather not add checks that impact all providers wanting to do logging, some of which may be in fast path operations.

On a more technical level, a provider should not log anything prior to fi_register_provider() running, as that's where the logging filters get set.  Basically, the prov_ini() call shouldn't do anything.

This does raise a point that providers are needing to perform one time initialization in the first call to fi_getinfo().  The framework should help here.  We could add an 'initonce()' call to fi_provider that the framework would call the first time getinfo is invoked for that provider.

**Comment by jimsnow** [comment]
I think that's reasonable.

**Pull request closed without merging**
