### PR TITLE
fabtests/unexpected_msg: Changes to unexpected_msg test

### PR DESCRIPTION
**Pull request by sunkuamzn**
unexpected_msg test uses the `-v` option but is not a benchmark, so move the `-v` option from benchmark to shared options

Also allocate `tx_msg_buf` which is required for verification when using device buffers

### CODE REVIEW

**Comment by sunkuamzn** [comment]
bot:aws:retest

**Comment by lrbison** [comment]
Changes look good to me.  I'd like to see the motivation for moving the -v option in the commit message itself rather than just the PR.

CI error is in `rhel8.test_suites.libfabric.test_fabtests.test_fabtests_functional[single_node-debug].test_rdm_tagged_peek` which times out.

**Comment by sunkuamzn** [comment]
> Changes look good to me. I'd like to see the motivation for moving the -v option in the commit message itself rather than just the PR.
Fixed

**Review by aingerson — COMMENTED** [review]
The second patch looks fine (but could you update the commit title to say "fabtests/unexpected_msg" to indicate that it is only relevant to that test?

The first patch I think I would drop because not all tests that use the cs opts support data verification so I think it could lead into users thinking their test is doing data validation when it isn't. The tests that do add data verification (but aren't a benchmark) do this by manually parsing the -v argument within their arg parsing (see bw.c for example).  I would instead change the first patch to just manually check it for just the unexpected message test.

**Review by aingerson — APPROVED** [review]
Thanks!

**Review by shefty — APPROVED** [review]

**Comment by shefty** [comment]
Intel CI failure is known issue (now resolved) in tcp provider.

**Review by lrbison — APPROVED** [review]

**Pull request merged**
