### PR TITLE
rocr: fix issue introduced by 43e92bf82a

### PR DESCRIPTION
**Pull request by amirshehataornl**
43e92bf82a introduce a build breakage for earlier versions of rocm. The DMA buf defines were added to handle compatibility, but were not added around the callback functions. This led to compile error:

src/hmem_rocr.c:182:36:
  error: ‘hsa_amd_portable_export_dmabuf’ undeclared here (not in a function)
    .hsa_amd_portable_export_dmabuf = hsa_amd_portable_export_dmabuf,

Also made a few changes to clean up warnings and code style.

### CODE REVIEW

**Comment by j-xiong** [comment]
For the DCO error, did you commit from a machine with git email configured differently from the signed-off-by line?

Also please change the start of the title line to `hmem/rocr: `.

**Comment by amirshehataornl** [comment]
my account should have two e-mail associated with it. The one I signed off by is the primary one on my account. So not sure why DCO would have a problem. I made the other change you requested.

**Comment by j-xiong** [comment]
@amirshehataornl It's not about the github account. It's related to the local git configuration ("user.email") on your machine (check $HOME/.gitconfig). That information is encoded with the commit and the DCO check would check if the email matches with the signoff line.

From the detail of the DCO error:
`Commit sha: [2c2f75f](https://github.com/ofiwg/libfabric/pull/9698/commits/2c2f75f3ff59ddf9c715ba1f081b61af1a875618), Author: Amir Shehata, Committer: Amir Shehata; Expected "Amir Shehata [amir.shehata@gmail.com](mailto:amir.shehata@gmail.com)", but got "Amir Shehata [shehataa@ornl.gov](mailto:shehataa@ornl.gov)".`

**Comment by amirshehataornl** [comment]
Here is my configuration file:

```
cat ~/.gitconfig
[merge]
    tool = extMerge
[mergetool "extMerge"]
    cmd = extMerge "$BASE" "$LOCAL" "$REMOTE" "$MERGED"
    trustExitCode = false
#[diff]
#    external = extDiff
[core]
    editor = vim
#    excludesFile = ~/.gitignore
[user]
    #email = amir.shehata@gmail.com
    email = shehataa@ornl.gov
    name = Amir Shehata
[filter "lfs"]
    clean = git-lfs clean -- %f
    smudge = git-lfs smudge -- %f
    process = git-lfs filter-process
    required = true
#[status]
#   showUntrackedFiles = no
```

**Comment by amirshehataornl** [comment]
although I changed that after I cloned. Am I going to need to reclone for it to pick up the new email?

**Comment by j-xiong** [comment]
No, the setting just needs to be current when `git commit` is run. Also make sure this is not overridden by the per-repo config (`.git/config` within the repo). The setting in `~/.gitconfig` is global to the user account.

**Comment by amirshehataornl** [comment]
looks though that when you clone it inherits the email address in the git info in the repo you cloned:
```
./logs/refs/heads/main:0000000000000000000000000000000000000000 0a130b7d49dec6f26c06a3609bc1c1af1e80ea7f Amir Shehata <amir.shehata@gmail.com> 1704399999 -0800	clone: from github.com:amirshehataornl/libfabric.git
```
So I had to clone another repository after I updated my .gitconfig.

**Comment by j-xiong** [comment]
There was one failure in the udp test. Most likely transient. Restarted CI.

**Review by j-xiong — APPROVED** [review]

**Pull request merged**
