### PR TITLE
fabtests: cuda dmabuf: fix dlsym check

### PR DESCRIPTION
**Pull request by aws-nslick**
this meant to check whether or not dlsym succeeded in resolving cuMemGetHandleForAddressRange but instead checked cuPointerSetAttribute

### CODE REVIEW

**Comment by j-xiong** [comment]
There are several similar errors around this, please double check entire `ft_cuda_init()` and try to fix them alltogether.

**Comment by aws-nslick** [comment]
> There are several similar errors around this, please double check entire `ft_cuda_init()` and try to fix them alltogether.

Thank you, did not look nearby.

**Review by j-xiong — APPROVED** [review]
Thanks.

**Comment by zachdworkin** [comment]
Please rebase to pick up Intel CI Cuda changes from #9886

**Pull request merged**
