### PR TITLE
Revert "prov/efa: refactor hmem interface initialization"

### PR DESCRIPTION
**Pull request by wenduwan**
This reverts commit c8de604b86edcc9d88995471d984cce1c7fc125d.

### CODE REVIEW

**Comment by shijin-aws** [comment]
@j-xiong this needs to be part of 1.22 rc, thanks!

**Review by shijin-aws — APPROVED** [review]

**Comment by j-xiong** [comment]
@shijin-aws I will put into rc2. Will that work for you?

**Comment by shijin-aws** [comment]
@j-xiong if we have rc2, we cannot release next week, right?

**Comment by j-xiong** [comment]
@shijin-aws Correct. We have at least one other change (PR not out yet) that needs get into 1.22 but can't catch the rc1 deadline.

**Comment by shijin-aws** [comment]
Got it, thanks

**Pull request merged**
