### PR TITLE
prov/rxd: Refactor for cleanup_unexp_msg

### PR DESCRIPTION
**Pull request by nikitaxgusev**
Signed-off-by: Nikita Gusev <nikita.gusev@intel.com>

### CODE REVIEW

**Comment by nikitaxgusev** [comment]
@aingerson There is aome conflict. I need to resolve it, when [PR#5210](https://github.com/ofiwg/libfabric/pull/5210) will be merged.

**Comment by nikitaxgusev** [comment]
@aingerson I think, there is with cloning a repo on WinOS. Will we rerun it?

**Comment by aingerson** [comment]
@nikitaxgusev yeah both the Windows and Intel CI failures look unrelated but let's rerun it to be sure. Just force push to retrigger the CI

**Comment by nikitaxgusev** [comment]
@aingerson Done.

**Pull request merged**
