### PR TITLE
Updates to address several open issues

### LINKED ISSUE #778: valid range (and precise meaning) of signaling_vector is unclear
Looking at the fi_cq(3) man page (and others that I've checked so far), it's not clear what values are valid for `signaling_vector`:

```c
              struct fi_cq_attr {
                  size_t               size;      /* # entries for CQ */
                  uint64_t             flags;     /* operation flags */
                  enum fi_cq_format    format;    /* completion format */
                  enum fi_wait_obj     wait_obj;  /* requested wait object */
                  int                  signaling_vector; /* interrupt affinity */
                  enum fi_cq_wait_cond wait_cond; /* wait condition format */
                  struct fid_wait     *wait_set;  /* optional wait set */
              };
```

And further down the page:
```
       signaling_vector : Indicates which processor core interrupts associated
       with the EQ should target.
```

I didn't see another value in the other man pages that indicates what the valid range for this value is.  Is it intended to be something like verbs' 1..`context->num_comp_vectors`?  Or is a logical core number expected instead?  Are negative numbers allowed (e.g., to specify "choose the 'best' affinity for me")?

### LINKED ISSUE #1142: When are completion flags valid?
The CQ entries allow flags to convey the type of operation that completed.  The value of a provider setting these flags is unclear relative to their cost.  For example, in order to set the flags, a provider may need to run through a series of branches.

We need to understand which flags are important for an app.  For example, do apps only need to distinguish between transmits versus receives?  How do we handle providers that cannot supply all flags without tracking the original request?

### LINKED ISSUE #1550: man: fi_ep_bind flags FI_TRANSMIT vs FI_SEND
The v1.1.1 fi_endpoint(3) manpage states that the FI_TRANSMIT flag and FI_SEND flag may be used interchangeably:

> FI_TRANSMIT
>     Directs the completion of outbound data transfer requests to the specified completion queue. This includes send message, RMA, and atomic operations. The FI_SEND flag may be used interchangeably.

This generates confusion since the FI_SEND flag states that it only applies to messages, not RMA/atomic operations, and only applies to counters:

> FI_SEND
>     Increments the specified counter whenever a successful message is transferred over the endpoint. Sent messages include both tagged and normal message operations.

### PR DESCRIPTION
**Pull request by shefty**
Fixes #778.  Fixes #1142.  Fixes #1550.  (Fix is probably too strong of a word for these.)

Document range for signaling vector value.
Add mode bit to relax completion flag reporting.  *API UPDATE*
Document that long double is undocumented.  :)
Add checks to validate EP bind flags.

Please see individual commits for details.  This series includes changes to most providers, which have not been tested.  I wanted to get feedback on the proposed changes.  @goodell @j-xiong @a-ilango @hppritcha @sungeunchoi @jsquyres

### CODE REVIEW

**Comment by shefty** [comment]
Added Fix #2116

**Comment by j-xiong** [comment]
The signaling vector: if it is a single cpu number, isn't that usually starting from 0? Or should it be a bitmask like those used in affinity settings (0x1 for cpu#0, 0x3 for cpu#0 and cpu#1, etc)?

Other changes look fine to me.

**Comment by sungeunchoi** [comment]
👍 for gni provider changes.. Thx for head ups.

**Comment by bturrubiates** [comment]
> The signaling vector: if it is a single cpu number, isn't that usually starting from 0? Or should it be a bitmask like those used in affinity settings (0x1 for cpu#0, 0x3 for cpu#0 and cpu#1, etc)?
> 
> Other changes look fine to me.

I agree that it might be more intuitive to use an interface similar to `taskset -c` (e.g. start from 0), but that would mean that the default case would bind to `0` (default being after a call to `calloc`). I think the alternative would be to use a special value like `-1` to indicate that the provider should automagically select the cpu to run on, but that seems error prone.

**Comment by shefty** [comment]
The issue is that existing apps will have a value of 0, since that is what would have come back from the library (fi_allocinfo).  So, while I agree that it makes sense to have cpu numbers start at 0, I used that to indicate don't care.  I thought about adding a flag to indicate that affinity should be used, and without it set, this would be left to the provider.  But that changes the ABI.  On the other hand, nothing supports affinity yet from what I could tell, and the value for an app to use isn't defined anyway...  Long story short, this seemed like the least sucky solution, but I'm not sold on it.

**Comment by shefty** [comment]
Btw, I'm not sure a bitmask will work. Xeon Phi already has more than 64 cores.  The new Chinese CPU has something like 290 cores.  Maybe we'll need some sort of 'cpu group' at some point, though my hope is that apps just rely on the providers to "do the right thing" (tm).

**Comment by j-xiong** [comment]
That sounds a reasonable compromise to make, so keep it this way until a better solution comes up.

I also thought about the core count limitation of the bitmask.

**Comment by jsquyres** [comment]
@shefty If you put a knob there, *someone* will use it.  I don't think we can bury our heads in the sand on this one -- affinity is important, and there's nominally a knob there to control it.  We need to make it work, even for arbitrarily-large core counts.  Integrating with something like hwloc would certainly be nice (@bgoglin), but that might be a bit much here (i.e., making hwloc an explicit dependency).  ...wouldn't it?

**Comment by shefty** [comment]
We have a knob there now.  The problem is defining how it can be used.  :)  The current definition for signaling_vector is an int.  So a bitmask doesn't work.  We can at least reserve the negative values for something more interesting, such as treating signaling_vector as some sort of bit mask.  Anyway, these are the reasonable choices I can think of (feel free to add more):

1. sv = 0 don't care, sv > 0 specific cpu core
2. sv >= 0 specific cpu core, add a flag FI_AFFINITY to indicate when sv is valid
3. treat sv as bit fields, accessed using macros.  E.g. add fields for: starting core number, core count

Anyway, let me drop this patch from the series and open it in a separate PR, so we can continue the discussion there.  There haven't been comments on the other changes.

**Comment by bturrubiates** [comment]
The usNIC provider doesn't seem to have been updated with the new `ofi_ep_bind_valid` function, but I could do that after this is merged if it's easier.

**Comment by goodell** [comment]
with the signal vector patch dropped, 👍 

I think the signal vector bit was pretty close, but breaking it out for separate discussion is a good idea.

**Comment by j-xiong** [comment]
👍

**Comment by a-ilango** [comment]
:+1: for verbs provider changes.

**Pull request merged**
