### PR TITLE
prov/psm2: Fix a bug in the connection clean-up protocol

### PR DESCRIPTION
**Pull request by j-xiong**
Remove disconnected addresses from the list of connected peers. This
eliminates intermittent segfault or assertion failure at finalization
time due to disconnection requests being issued to addresses that have
already been disconnected.

Signed-off-by: Jianxin Xiong <jianxin.xiong@intel.com>

### CODE REVIEW

**Comment by shefty** [comment]
Is this v1.5.3 material?

**Comment by j-xiong** [comment]
@shefty No.

**Comment by shefty** [comment]
That's the best news I've heard all day. :)

**Comment by j-xiong** [comment]
:)

**Pull request merged**
