### PR TITLE
[v1.14.x] fabtests: disable inject when FI_HMEM is enabled

### PR DESCRIPTION
**Pull request by shijin-aws**
This PR is a backport of https://github.com/ofiwg/libfabric/pull/7334/commits/65fa2adcb3ff1d70b54d2f593b53a68edc869a1d to v1.14.x branch

### CODE REVIEW

**Comment by shijin-aws** [comment]
```
configure: WARNING: level_zero/ze_api.h: present but cannot be compiled
configure: WARNING: level_zero/ze_api.h:     check for missing prerequisite headers?
configure: WARNING: level_zero/ze_api.h: see the Autoconf documentation
configure: WARNING: level_zero/ze_api.h:     section "Present But Cannot Be Compiled"
configure: WARNING: level_zero/ze_api.h: proceeding with the compiler's result
configure: WARNING:     ## ------------------------------------------ ##
configure: WARNING:     ## Report this to ofiwg@lists.openfabrics.org ##
configure: WARNING:     ## ------------------------------------------ ##
checking for level_zero/ze_api.h... no
configure: error: ZE support requested but ZE runtime not available.
Error: Process completed with exit code 1.
```

Is this an issue in the infrastructure?

**Comment by aingerson** [comment]
@shijin-aws There is a bug in the distro for ze 1.6.2. I added a work around to manually build the version where it was fixed. You'll have to cherry-pick commit 52f35998c2a93c37ce527641bfb43580501f8737 to get that build check to pass

**Comment by shijin-aws** [comment]
@aingerson Thank you! Cherry-picked that commit in the PR.

**Review by wzamazon — APPROVED** [review]

**Comment by aingerson** [comment]
@shijin-aws @wzamazon Disregard the Jenkins failure which is due to our recent switch of the cluster and will need some cherry-picked commits to get it working for 1.14.x. I'll work on cherry-picking all necessary CI commits.

**Comment by aingerson** [comment]
@shijin-aws Yup!

**Review by shefty — APPROVED** [review]

**Pull request merged**
