### PR TITLE
prov/efa: fix a bug and enable RNR support

### PR DESCRIPTION
**Pull request by wzamazon**
This PR contains 2 commits:

First one fixed a bug in RNR support.

With this bug fix, all known issues of RNR support will be fixed. Thus 2nd commit enable RNR support.

### CODE REVIEW

**Comment by wzamazon** [comment]
This need to wait after https://github.com/ofiwg/libfabric/pull/6903 is merged

**Comment by wzamazon** [comment]
bot:aws:retest

**Comment by wzamazon** [comment]
bot:aws:retest

**Comment by wzamazon** [comment]
#6903 is merged, ready for review.

**Review by bwbarrett — CHANGES_REQUESTED** [review]
I'm fine with the code changes, but the title of the first commit needs work.  Rather than "prov/efa: fix a bug...", how about "prov/efa: Remove peer backoff entries" or something that indicates what the patch does.

Likewise, the description is to follow.  A bit more on why these are the right actions to take would be nice.

**Comment by wzamazon** [comment]
@bwbarrett Fixed the commit message for the 1st commit in new revision.

**Review by bwbarrett — APPROVED** [review]

**Comment by wzamazon** [comment]
bot:aws:retest

**Comment by wzamazon** [comment]
bot:aws:retest

**Comment by wzamazon** [comment]
bot:aws:retest

**Comment by wzamazon** [comment]
bot:aws:retest

**Comment by zhngaj** [comment]
So after enabling RNR support, all one-sided tests can pass?

**Review by zhngaj — COMMENTED** [review]
Nit:
1. wzamazon authored and **`AWS ParallelCluster user`** committed?
2. address->addresses
3. funcationality->functionality

**Comment by wzamazon** [comment]
@zhngaj Yes, they passed during my manual test of the PR.

**Comment by wzamazon** [comment]
@zhngaj Thank you! fixed in new revision.

**Review by zhngaj — APPROVED** [review]

**Pull request merged**
