### PR TITLE
Add Cray Libfabric Jenkins pipeline file

### PR DESCRIPTION
**Pull request by jswaro**
This commit introduces a Jenkins pipeline file for testing the
verbs provider. This is a first iteration of the pipeline.

Signed-off-by: James Swaro <jswaro@cray.com>

### CODE REVIEW

**Comment by jswaro** [comment]
@shefty I've been giving this some thought. Does this belong in the contrib folder? I'm thinking that maybe it does, but I'd like to know what you think.

**Comment by shefty** [comment]
Moving this under contrib or contrib/ci makes sense.  I'll let you decide. :)

**Comment by jswaro** [comment]
Do you have a preference?

**Comment by shefty** [comment]
Maybe just contrib/cray?

**Comment by jswaro** [comment]
> Maybe just contrib/cray?

Sounds fine to me. I'll update the PR and merge.

**Pull request merged**
