### PR TITLE
Include process ID in log messages

### PR DESCRIPTION
**Pull request by chrisdolan**
Signed-off-by: Chris Dolan <chrisdolan@google.com>

### CODE REVIEW

**Comment by chrisdolan** [comment]
Hmm, failing in MSVC. Does it not like the "static" in "static pid_t pid;"? Or does it not define pid_t? I don't have a Windows machine at hand to test this myself, so I'd welcome any suggestions.

**Comment by shefty** [comment]
I'll go with pid_t is undefined, but I didn't pull the changes down and try to build it.  fabtests has solved this through fabtests/include/windows/osd.h.  We need a similar set of defines in include/windows/osd.h.

**Comment by chrisdolan** [comment]
Got it. I implemented that change in include/windows/osd.h but have not tested it (I've done a lot of Windows dev in the past but not recently). Hopefully you all don't mind me using your CI server for my own smoke testing! That said, this is by far the least important of the patches I plan to submit so if you'd rather just reject the change I'm fine with that.

**Comment by shefty** [comment]
I use appveyor to test my windows changes 99% of the time.  :)  It's just easier than pulling the changes over from linux and running the windows build myself.

**Pull request merged**
