### PR TITLE
usnic: Return the correct completion length.

### PR DESCRIPTION
**Pull request by bturrubiates**
The completion lengths are determined by the amount sent/received. There
are two cases to handle when setting the completion length:

- Prefix Mode
  The app gives send/recv a length value that includes usnics advertised
  header size. For performance reasons the reported header size is
  slightly larger than it actually is. Internally the usnic provider
  sends starting at the header offset. This means that the returned
  completion length omits the length of the padding. This addresses the
  issue by adding the length of the padding to all completions generated
  on endpoints in prefix mode.
- Non-Prefix Mode
  The app gives send/recv a length value that reflects the size of the
  payload. The app is not aware of headers. Internally the usnic
  provider allocates a header to perform the send/recv and it ends up
  being included in the completion length size. This addresses the issue
  by removing the length of the header from all completions generated on
  endpoints not in prefix mode.

@rfaucett @goodell @jsquyres 

Signed-off-by: Ben Turrubiates <bturrubi@cisco.com>

### CODE REVIEW

**Comment by bturrubiates** [comment]
Actually, hold off on this for a bit. Need to see how it affects inject.

**Comment by goodell** [comment]
Ignoring for the moment the possible inject ramifications you are investigating, this change looks good to me.

**Comment by bturrubiates** [comment]
Actually we don't currently support FI_INJECT, so that's a non-problem for now.

**Comment by goodell** [comment]
Heh, true, not supported for `EP_DGRAM` right now.  So this looks ready for me to merge, right?

**Comment by goodell** [comment]
Ben confirmed out-of-band that he isn't planning any further changes, merging.

**Pull request merged**
