### PR TITLE
prov/psm3: Add PACK_SUFFIX define to missing header

### PR DESCRIPTION
**Pull request by acgoldma**
https://github.com/ofiwg/libfabric/issues/6614

Reviewed-by: Goldman, Adam <adam.goldman@intel.com>
Signed-off-by: Todd Rimmer <todd.rimmer@intel.com>

### CODE REVIEW

**Comment by shefty** [comment]
Were you able to reproduce the build issue?

**Comment by acgoldma** [comment]
> Were you able to reproduce the build issue?

Not the exact build issue, but @ToddRimmer was able to discover the PACK_SUFFIX issue by investigating the object files. It looks like because it was not defined, the header was treating it as a variable name.
```
$ nm psm3/opa/libopa_la-opa_syslog.o | grep PACK
0000000000000008 C PACK_SUFFIX
```
Once this patch is in, this output no longer shows PACK_SUFFIX as a variable.

**Comment by acgoldma** [comment]
Should we cherry-pick this v12.x branch?

**Comment by shefty** [comment]
Yes, we will need to create 1.12.1 with all build fixes.

**Pull request merged**
