### PR TITLE
1.0 release prep for spec file.

### PR DESCRIPTION
**Pull request by pmmccorm**
Update version to work with rpmbuild.
Add buildrequires for src.rpm
Build all in-tree providers for release.

Signed-off-by: pmmccorm <patrick.m.mccormick@intel.com>

### CODE REVIEW

**Comment by pmmccorm** [comment]
Addresses nits from merge #571 

@jsquyres Does the rpm build and look OK?

**Comment by shefty** [comment]
As just a note, rc1 has already been tagged, so this change wouldn't technically show up until we spin off an rc2 package, or through a nightly build package.

**Comment by jsquyres** [comment]
:+1:

**Comment by jsquyres** [comment]
Actually, I lied, sorry.  With these changes, I can't build the RPM.

Notes:

* usnic requires either libnl-devel or libnl3-devel (at least, that's what they're called on RHEL -- I don't know what they're called on other distros offhand).
* are there any systems that can build *all four* providers?  E.g., does RHEL ship with libinfinipath-psm-devel?  These changes basically make it such that you can't build the RPM unless you can build all four providers (I can only build three, since I don't have the infinipath libraries).

**Comment by shefty** [comment]
I can build all 4 providers on one of my test systems.  Though I manually installed the necessary libraries just for this purpose.  I can't run all of them, however.

**Comment by jsquyres** [comment]
I guess a better way to phrase my question is: do we want to force people who want an RPM to build all four providers?

FWIW, in RHEL 6.5, I see infinipath-psm-3.0.1-115.1015_open.2.el6.x86_64.rpm, but I don't see a -devel version...?

**Comment by raffenet** [comment]
FWIW, I see the devel package in both RHEL and CentOS. Same version as the library.

```
-bash-4.1$ yum info infinipath-psm-devel
Loaded plugins: priorities, security
216 packages excluded due to repository priority protections
Available Packages
Name        : infinipath-psm-devel
Arch        : x86_64
Version     : 3.0.1
Release     : 115.1015_open.2.el6
Size        : 22 k
Repo        : optional
Summary     : Development files for QLogic PSM
URL         : git://git.qlogic.com/InfiniPath-PSM
License     : BSD or GPLv2
Description : Development files for the libpsm_infinipath library
```

**Comment by jsquyres** [comment]
Huh.  Ok.  Disregard my comment, then.

> On Feb 2, 2015, at 3:58 PM, raffenet <notifications@github.com> wrote:
> 
> FWIW, I see the devel package in both RHEL and CentOS. Same version as the library.
> 
> -bash-4.1$ yum info infinipath-psm-devel
> Loaded plugins: priorities, security
> 216 packages excluded due to repository priority protections
> Available Packages
> Name        : infinipath-psm-devel
> Arch        : x86_64
> Version     : 3.0.1
> Release     : 115.1015_open.2.el6
> Size        : 22 k
> Repo        : optional
> Summary     : Development files for QLogic PSM
> URL         : git://git.qlogic.com/InfiniPath-PSM
> License     : BSD or GPLv2
> Description : Development files for the libpsm_infinipath library
> 
> —
> Reply to this email directly or view it on GitHub.
> 


-- 
Jeff Squyres
jsquyres@cisco.com
For corporate legal information go to: http://www.cisco.com/web/about/doing_business/legal/cri/

**Comment by pmmccorm** [comment]
I built all four on my local system. The psm and verbs deps came from an ofed 3.12-1 install, libnl3{-devel} came from rhel repo.

For the RPM I think this is what we want: all in-tree providers built and packaged with explicit build requires.

**Pull request merged**
