### PR TITLE
RFC: build system: move provider-specific Makefilery to their dirs

### PR DESCRIPTION
**Pull request by jsquyres**
Continue the trend started by the gni provider: move all the provider-specific Makefile.am bits into prov/PROVIDER/Makefile.include, and then just include those files in the top-level Makefile.am.

Also rename the gni Makefile.am to Makefile.include (like the rest of the included Makefiles) so that it's clear from the filename that this is not a normal Makefile.am file -- it must be included to be used.

Signed-off-by: Jeff Squyres <jsquyres@cisco.com>

This is largely stylistic; the intent is just to centralize provider-specific stuff in the provider directories.  But it does change one minor piece of the installation logic: fi_PROVIDER.7 man pages are no longer installed unless the provider itself is installed.  I think this is a good change -- e.g., if fi_PROVIDER.7 is installed, it might be a reasonable assumption to think that PROVIDER is installed, too.

Comments?

(do not merge this PR yet; it will undoubtedly have conflicts with #1546 and #1545 -- I can fix the problems here after those 2 PRs are merged)

### CODE REVIEW

**Comment by j-xiong** [comment]
:+1: 
The psm provider and the psm2 provider share the same real man page so we need to also have fi_psm.7 included if the psm2 provider is built but the psm provider is not.

**Comment by jsquyres** [comment]
@j-xiong Mmm.  This could be tricky.  We can't list the same man page twice in `$real_man_pages` (because Automake will barf during `make install`).  Is there any way these two can be split into 2 different man pages?

**Comment by j-xiong** [comment]
Yes, this seems to be the reason I have been looking for to get the pages separated :)

**Comment by hppritcha** [comment]
This approach works for the gni crew.

**Comment by shefty** [comment]
:+1:

**Comment by jsquyres** [comment]
@hppritcha Can you comment on #1546?  I'd like to merge that before merging this one.

**Pull request merged**
