### PR TITLE
fabtests,efa,tcp,rxm: increase coverage of fi_cq_data to fi_writedata and verify "len" in cq entry

### PR DESCRIPTION
**Pull request by wzamazon**
verify the "len" field of fi_cq_data_entry.

verify whether `fi_writedata` pass the test.

Enable the test for EFA.

### CODE REVIEW

**Review by shefty — COMMENTED** [review]
Can you add the new testing to runfabtests.sh?  Also, I think it was the 2nd or 3rd patch in this series (the one that adds the new op), can you add more details to the commit message?  There weren't any.

Other changes look okay.

**Comment by shefty** [comment]
Ci failure:
```
name:   fi_cq_data -e rdm -o writedata -p "verbs;ofi_rxm"
16:32:29    timestamp: 20230303-003229+0000
16:32:29    result: Fail
16:32:29    time:   1
16:32:29    server_cmd:  /home/cstbuild/ofi-Install/libfabric/ofi_libfabric/PR-8596/5/reg/bin/fi_cq_data -e rdm -o writedata -p "verbs;ofi_rxm"   -s ci3-ib0
16:32:29    server_stdout: |
16:32:29      Waiting for CQ data from client
16:32:29      remote_cq_data: success
16:32:29      error, Expected len:1000, Received len:0
```
Verbs needs a similar update.

**Comment by wzamazon** [comment]
> Verbs needs a similar update.

From code inspection, verbs wrote the len, but rxm did not pass it to app.

I added a fix of rxm, which I have no way to test. 

Hopefully it fixed the issue.

**Comment by wzamazon** [comment]
@shefty 

Looks like `verbs;ofi_rxm` passed. Can you confirm?

The windows test failure should not be related this PR.

**Review by shefty — APPROVED** [review]
It's hard for me to tell given the complexity of the providers, but both opx and psm3 may be reporting the len already.  This is based on searching their code bases for FI_REMOTE_CQ_DATA flag and noting that a len value is being set nearby.

**Pull request merged**
