### PR TITLE
v1.9.0rc2

### PR DESCRIPTION
**Pull request by shefty**
CI testing - will be pushed directly.

### CODE REVIEW

**Comment by nikhilnanal** [comment]
Can one of the admins verify this patch?

**Comment by shefty** [comment]
@nikhilnanal - is that a real comment or some auto-generated comment?  If it's the latter, which I assume, since it's appeared on other PRs and its 7 PM on Friday, we need to remove it.

**Comment by shefty** [comment]
Intel CI failed with a bunch of ENODATA.  It looks like the fabtests being used to validate libfabric are not from the same version.  E.g. it's building libfabric and fabtests, but running with fabtests from an older version already installed on the systems (or vice-versa).  Forced updated PR to re-run CI, but I expect the same result.

**Comment by shefty** [comment]
@rajachan - I believe this EFA failure on alinux is unrelated
```
10:43:58 172.31.22.62 - name:   fi_recv_cancel -e rdm -V -p "efa"
10:43:58 172.31.22.62   result: Fail
```

**Comment by rajachan** [comment]
That's a race we have seen in CI before but have not been able to reproduce it outside the CI environment. We will take a close look at that one, but I don't think it has to block this merge.

**Comment by rajachan** [comment]
bot:aws:retest

**Pull request merged**
