### PR TITLE
util/pingpong: Fix out of scope addrinfo memory leak

### PR DESCRIPTION
**Pull request by zachdworkin**
Fixes coverity 424710

### CODE REVIEW

**Review by chien-intel — APPROVED** [review]
Looks good

**Review by shijin-aws — APPROVED** [review]

**Comment by zachdworkin** [comment]
@shijin-aws are there new commands to tell the different AWS CI's to replay?

**Comment by shijin-aws** [comment]
@zachdworkin new AWS CI is still in beta. The current CI failure is irrelevant

**Comment by shijin-aws** [comment]
bot:aws:retest

**Review by j-xiong — APPROVED** [review]

**Pull request merged**
