### PR TITLE
v1.22.0

### PR DESCRIPTION
**Pull request by j-xiong**
For CI only. Do not merge. Will be pushed directly.

### CODE REVIEW

**Comment by belynam** [comment]
Hi @j-xiong ,

Looking at the release candidate downloads [here](https://github.com/ofiwg/libfabric/releases/tag/v1.22.0rc2), specifically **libfabric-1.22.0rc2.tar.bz2**, I find that [prov/opx/provider_FABRIC_1.0.map](https://github.com/ofiwg/libfabric/blob/main/prov/opx/provider_FABRIC_1.0.map) is **not** included. This causes an error when running `configure` and specifying `--enable-direct=opx`. What would we need to do to make sure that file is included in official release tarballs?

**Comment by j-xiong** [comment]
@belynam Have you ever been able to do it before? The same issue exists for opx, psm2 and sockets. I can fix it but want to double check that it's not a regression.

**Comment by j-xiong** [comment]
@belynam I have included a fix here.

**Comment by belynam** [comment]
> @belynam Have you ever been able to do it before? The same issue exists for opx, psm2 and sockets. I can fix it but want to double check that it's not a regression.

I don't think this is a regression, I see the same issue on previous release tarballs. Historically when testing, I've only downloaded the source itself or pulled down the branch to test the build. I'm not aware of any of our users running into this issue, so maybe most don't use that option.

> @belynam I have included a fix here.

Thank you!

**Comment by shijin-aws** [comment]
bot:aws:retest

**Comment by shijin-aws** [comment]
bot:aws:retest

**Pull request merged**
