### PR TITLE
[v1.21.x] prov/efa: Remove unconditional assignment of err_entry

### PR DESCRIPTION
**Pull request by shijin-aws**
backport https://github.com/ofiwg/libfabric/pull/9942

### CODE REVIEW

**Review by darrylabbate — APPROVED** [review]

**Review by wenduwan — APPROVED** [review]

**Comment by j-xiong** [comment]
@shijin-aws It's a little bit late for 1.21.0. Are you fine with getting it merged after 1.21.0?

**Comment by shijin-aws** [comment]
@j-xiong It's to fix a perf regression introduced by the earlier commits in 1.21. It will greatly appreciated if we can include this. But it's acceptable for us to merge it the OFIWG 1.21.0 release.

**Comment by j-xiong** [comment]
@shijin-aws Ok, I can get it in. Just need to restart packaging and testing.

**Comment by shijin-aws** [comment]
@j-xiong Thanks a lot!

**Pull request merged**
