### PR TITLE
collectives: Rework collective APIs to add gather / reduce support

### PR DESCRIPTION
**Pull request by shefty**
Update the collective APIs to support gather and reduce
operations.  These were missing from the initial collective
calls.  Adding these exposed an issue with the existing calls
providing the 'root' of broadcast calls, which are also
needed for gather and reduce.

To support the new calls, and make it easier to extend support
for other collective ops, modify the calls into the provider.
Instead of using a single writeread() atomic style call, define
separate entry points for each collective.

Signed-off-by: Sean Hefty <sean.hefty@intel.com>

### CODE REVIEW

**Comment by shefty** [comment]
@ooststep - These are proposed changes to the collective APIs interfacing with the provider.

**Comment by shefty** [comment]
@AMcKinley15 @rajachan  - AWS CI is failing with multinode test that was just merged.  The test worked okay locally for me.  It's not obvious to me from the logs what the issue might be.

**Comment by rajachan** [comment]
I did not follow along with the multinode fabtest PR assuming that had to be invoked with a custom flag/script, did not realize it will run by default against all providers. From the logs, the EFA failure seems to be related to the addressing format. EFA does not support `FI_SOCKADDR`/`FI_SOCKADDR_IN` and the custom address format would have to be exchanged out of band. Not able to tell why UDP failed. 

For now, I'll push up a PR to add this to the EFA exclude list. @AMcKinley15 can possibly use UDP to test the failure and choose to do the same if the fix is going to take a while.

**Comment by shefty** [comment]
I agree that we need OOB address exchange for multinode.  We can remove it from the runfabtests.sh script until we can confirm that it works in all test environments.  It did pass all CI prior to merging.

**Comment by AMcKinley15** [comment]
The time out error had occurred a couple of times in testing, but I had thought I had fixed it. I guess I had just made it occur less. I'm really not sure why this is happening, but I'll take a closer look.

**Comment by shefty** [comment]
bot:aws:retest

**Pull request merged**
