### PR TITLE
[v1.7.x] core, prov/rxm: enable FI_PROVIDER with utility providers + rxm getinfo fix

### PR DESCRIPTION
**Pull request by aingerson**

### CODE REVIEW

**Comment by aingerson** [comment]
@shefty @a-ilango 
This should pass our CI this time. I'm not exactly sure why that second patch is needed because by the sound of it, it's supposed to be a redundant fix, but it was failing the second getinfo after it had already established a connection.

**Comment by a-ilango** [comment]
@aingerson thanks for finding the needle (the extra patch) in the haystack!

The reason why FI_PROVIDER="verbs;ofi_rxm" doesn't work with only the "FI_PROVIDER patch" is because the extra fi_getinfo call in `rxm_conn_connect` doesn't pass the flag `OFI_GETINFO_INTERNAL` without which the core filters out a valid fi_info from the verbs provider (`ofi_filter_info` compares the filter `verbs;ofi_rxm` with provider name `verbs` and considers it not a match) thus ultimately returning a -FI_ENODATA to the app.

@j-xiong Is `OFI_GETINFO_INTERNAL` mandatory for any internal getinfo calls? Is there a reason why `ofi_filter_info` doesn't consider `verbs;ofi_rxm` and `verbs` a match?

**Comment by j-xiong** [comment]
The purpose of ofi_filter_info() is to get exact match of the base provider. For example. if user asks for "verbs;ofi_rxm" the actual provider needs to have "verbs;ofi_rxm" as the base in order to match. That means "verbs;ofi_rxm;ofi_mrail" matches but and "verbs" doesn't.

The OFI_GETINFO_INTERNAL flag is used to bypass the filter when OFI_CORE_PROV_ONLY can't be used. For utility providers, most of the time OFI_CORE_PROV_ONLY is used so the new flag is not needed. mrail needs this flag because its base is not core provider only. For the case of rxm_conn_connect(), adding the flag should help (if you want to keep the call).

**Comment by a-ilango** [comment]
@j-xiong Thanks for the clarification!

**Pull request merged**
