### PR TITLE
prov/psm3 Updates the PSM3 provider to match the IEFS 11.3 release

### PR DESCRIPTION
**Pull request by mwheinz**
- Improved compatibility for PSM3 communication library with NCCL via
  OFI NCCL plugin
- Support for multiple IP addresses per NIC
- Increased the default value of PSM3_GPUDIRECT_RDMA_SEND_LIMIT to
  "always on".
- OneAPI GPU support.
- Renaming of psm2 functions to psm3.
- Allow runtime selection of verbs or sockets.
- Allow runtime selection of UDP/TCP mode
- Additional code cleanup.
- Various performance improvements.
- Various bug fixes.

Signed-off-by: Michael Heinz <michael.heinz@intel.com>

### CODE REVIEW

**Comment by mwheinz** [comment]
@j-xiong , @shefty - can you let me know why continuous-integration/appveyor/branch failed?

**Comment by j-xiong** [comment]
```
Build started
git clone -q --branch=iefs_11_3 https://github.com/ofiwg/libfabric.git C:\projects\libfabric
fatal: Remote branch iefs_11_3 not found in upstream origin
Command exited with code 1[2](https://ci.appveyor.com/project/ofiwg/libfabric/builds/43771800/job/px73ittbkoq4v8bg#L2)8
```

**Comment by j-xiong** [comment]
I can't think of any reason other than appveyor server misbehavior/misconfiguration. I checked previous successful runs, the "--branch" parameter should not be there.

**Comment by j-xiong** [comment]
Restarted the test to see if it will resolve by itself.

**Comment by j-xiong** [comment]
Intel CI failure seems to be due to abnoraml shm performance:
```
10:46:05  - name:   fi_rma_bw -e rdm -o read -I 5 -p "shm"
10:46:05    timestamp: 20220606-174604+0000
10:46:05    result: Fail
10:46:05    time:   15
10:46:05    server_cmd:  /home/cstbuild/ofi-Install/libfabric/ofi_libfabric/PR-7804/3/reg/bin/fi_rma_bw -e rdm -o read -I 5 -p "shm"  -D ze -i 0  -s ci10
10:46:05    server_stdout: |
10:46:05      bytes   iters   total       time     MB/sec    usec/xfer   Mxfers/sec
10:46:05      64      5       320         0.03s      0.01    5671.60       0.00
10:46:05      256     5       1.2k        2.85s      0.00  569850.00       0.00
10:46:05      1k      5       5k          0.05s      0.10   10191.20       0.00
10:46:05      4k      5       20k         0.04s      0.52    7846.60       0.00
10:46:05      64k     5       320k        0.04s      8.80    7446.20       0.00
10:46:05      1m      5       5m          2.77s      1.89  554034.62       0.00
10:46:05    client_cmd:  /home/cstbuild/ofi-Install/libfabric/ofi_libfabric/PR-7804/3/reg/bin/fi_rma_bw -e rdm -o read -I 5 -p "shm"  -D ze -i 1  -s ci10 ci10
10:46:05    client_stdout: |
10:46:05      bytes   iters   total       time     MB/sec    usec/xfer   Mxfers/sec
10:46:05      64      5       320         0.03s      0.01    5670.80       0.00
10:46:05      256     5       1.2k        2.85s      0.00  569851.00       0.00
10:46:05      1k      5       5k          0.05s      0.10   10190.40       0.00
10:46:05      4k      5       20k         0.04s      0.52    7846.00       0.00
10:46:05      64k     5       320k        0.04s      8.80    7446.00       0.00
10:46:05      1m      5       5m          2.76s      1.90  552833.38       0.00
```

**Comment by mwheinz** [comment]
bot:retest

**Comment by mwheinz** [comment]
> Intel CI failure seems to be due to abnoraml shm performance:

That shouldn't have anything to do with this patch - it only changes files inside prov/psm3.

**Pull request merged**
