### PR TITLE
Wrong array boundaries check

### PR DESCRIPTION
**Pull request by p91paul**

### CODE REVIEW

**Comment by shefty** [comment]
thanks

**Comment by patrickmacarthur** [comment]
@shefty I noticed that this commit didn't have a `Signed-off-by:`, as required by the [contributor's agreement](https://github.com/ofiwg/libfabric/blob/master/CONTRIBUTORS) and discussed in the OFIWG meeting a couple of weeks ago.  Are we actually enforcing this?

**Comment by shefty** [comment]
Yes, this should be enforced.

**Comment by shefty** [comment]
I reverted this change.  @p91paul, can you please resubmit the patch with a signed-off-by line included in the commit message?  Just add:

Signed-off-by: your name <your email>

Thanks

**Comment by p91paul** [comment]
Of course, sorry, I should have read that.

**Pull request merged**
