### PR TITLE
v2.0.0 alpha

### PR DESCRIPTION
**Pull request by j-xiong**
For CI only, do not merge. Will be pushed directly.

### CODE REVIEW

**Comment by j-xiong** [comment]
bot:aws:retest

**Comment by j-xiong** [comment]
bot:aws:retest

**Comment by j-xiong** [comment]
@shijin-aws I have started the third AWS CI run. Can you see what went wrong for the previous runs? Was it still the CI stability issue as we saw yesterday?

**Comment by shijin-aws** [comment]
@j-xiong the AWS CI is currently unstable for some fi_writedata/fi_write test. It shouldn't be related to this PR. I will try to stabelize it  ASAP

**Comment by j-xiong** [comment]
Updated the PR due to unplanned merge of the LPP provider patch.

**Pull request merged**
