### PR TITLE
Re-open PR for variable length message, Add rbtree for AV address lookup

### PR DESCRIPTION
**Pull request by shefty**

### CODE REVIEW

**Comment by shefty** [comment]
@aingerson - See ofi_tree.h.  That contains a modified rbtree that can be used to lookup addresses that are stored someplace separate from the rbtree itself.

**Comment by aingerson** [comment]
Since you're calling it an rbmap, can we rename them to include/ofi_rbmap and src/rbmap?
#HighMaintenance

**Comment by shefty** [comment]
I anticipate someday adding the rbtree to this as well, so that we can remove the chance of initialization failure.  That will remove src/rbtree.c and include/rbtree.h from the source tree.  I don't know if we'll ever need support for a normal binary tree, but that would go here as well.

**Comment by aingerson** [comment]
Gotcha gotcha. Well cool. Thanks!

**Pull request merged**
