### PR TITLE
prov/efa: migrate pktpool, cmd type_base from rxr to efa_rdm

### PR DESCRIPTION
**Pull request by wzamazon**
Continue move away from the deprecated term RxR

### CODE REVIEW

**Comment by wenduwan** [comment]
bot:aws:retest

**Review by wenduwan — APPROVED** [review]
Approving assuming AWS CI windows failure is expected.

**Comment by wenduwan** [comment]
Failure
```
12:46:56        "C:\9071_1687548571\libfabric\libfabric.sln" (Build target) (1) ->
12:46:56        "C:\9071_1687548571\libfabric\libfabric.vcxproj" (default target) (5) ->
12:46:56        (ClCompile target) -> 
12:46:56          C:\9071_1687548571\libfabric\prov\efa\src\efa_av.c(43,10): fatal error C1083: Cannot open include file: 'efa_rdm_pke_utils.h': No such file or directory [C:\9071_1687548571\libfabric\libfabric.vcxproj]
12:46:56          c1 : fatal error C1083: Cannot open source file: 'prov\efa\src\rdm\rxr_pkt_cmd.c': No such file or directory [C:\9071_1687548571\libfabric\libfabric.vcxproj]
```

**Comment by wenduwan** [comment]
@wzamazon windows issue is real. Could you fix that?

**Comment by wzamazon** [comment]
> @wzamazon windows issue is real. Could you fix that?

Yes. will do

**Comment by wzamazon** [comment]
Windows test failure fixed

**Review by wenduwan — APPROVED** [review]

**Pull request merged**
