### PR TITLE
prov/hook_hmem: fix Makefile.include error

### LINKED ISSUE #7280: hmem fails to compile when fabric direct mode is used.
I did a rebase today of my internal development branch and I can no longer enable fabric direct mode. I haven't identified the commit that introduces the problem, but normal builds build correctly.

The exact error is:

```
/bin/sh ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.  -I./include -D_GNU_SOURCE -D__USE_XOPEN2K8 -DSYSCONFDIR=\"/usr/local/ofi-opx/etc\" -DRDMADIR=\"@rdmadir@\" -DPROVDLDIR=\"/usr/local/ofi-opx/lib/libfabric\"        -I./prov/hook/include   -I./prov/hook/hook_hmem/include  -I./prov/psm2/include   -Wall -O2 -DNDEBUG -g -O3 -MT prov/psm2/src/libpsmx2_la-psmx2_trx_ctxt.lo -MD -MP -MF prov/psm2/src/.deps/libpsmx2_la-psmx2_trx_ctxt.Tpo -c -o prov/psm2/src/libpsmx2_la-psmx2_trx_ctxt.lo `test -f 'prov/psm2/src/psmx2_trx_ctxt.c' || echo './'`prov/psm2/src/psmx2_trx_ctxt.c
prov/hook/hook_hmem/src/hook_hmem.c:1894:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘{’ token
 {
 ^
```

I've attached a sample configuration log as an example, it uses psm2 but I believe the same problem would occur for any use of fabric direct. [config.log](https://github.com/ofiwg/libfabric/files/7644891/config.log)

### PR DESCRIPTION
**Pull request by aingerson**
Fixes #7280 

Signed-off-by: aingerson <alexia.ingerson@intel.com>

### CODE REVIEW

**Comment by mwheinz** [comment]
I'll give it a try.

**Review by shefty — APPROVED** [review]

**Review by mwheinz — APPROVED** [review]
Looks good to me.

**Comment by shefty** [comment]
Merge conflict between the lock rename and introduction of hmem -- I'm working on the fix.

**Comment by shefty** [comment]
Pulled change into #7282

**Pull request closed without merging**
