### PR TITLE
verbs/RDM improvements

### PR DESCRIPTION
**Pull request by evgeny-leksikov**
1) Enabled RMA caps
2) Aligned inject size with eager buffer size
3) Fixed leak of requests

### CODE REVIEW

**Comment by shefty** [comment]
@a-ilango - any discussion on this series?  It looks reasonable to me at a first glance.

**Comment by a-ilango** [comment]
Just a few comments. Other changes look okay.

**Comment by evgeny-leksikov** [comment]
@a-ilango, thanks for reviewing. Currently verbs/RDM generates completion events right after processing of local completions (or even after post_send in case of buffered tsend/tinject)
I know it is not quite accurately for RMA ops and I plan to rework them with dedicated QP for remote completions support.
BTW, Is there a possibility to ask FI_RX_CQ_DATA requirement only for RMA calls? Otherwise, I cant require it explicitly because it will kill latency of tagged operations.
I think assertion after post_send is useful for debugging and does not affect release build, here just -errno will be returned.

**Comment by a-ilango** [comment]
Yes, we need FI_RX_CQ_DATA mode only for RMA calls. That's what I meant in my comment. :)
Regarding the assert, I don't see it wrapped by ENABLE_DEBUG #defines. Are you sure it would not be in release build?

**Comment by shefty** [comment]
The assert() statement itself is stripped out in release builds.

**Comment by shefty** [comment]
Is this series good to merge?

**Comment by evgeny-leksikov** [comment]
@shefty from my point of view it is good because verbs/rdm really doesn't support remote completions right now. Addition of requirement for this flag is questionable.

@a-ilango Sorry for my misunderstanding regarding the meaning of this flag, but it is still not obvious (from man page) why and when this flag must be requested? I do not find any other reference on that inside libfabric excepting verbs/msg.

**Comment by shefty** [comment]
In verbs terms, FI_RX_CQ_DATA means that an RDMA write with immediate data consumes a receive buffer at the remote side.  Because RDM support is emulated, I don't know that this is true from the viewpoint of the application.  So, I think we're actually okay with this series as-is.

**Comment by a-ilango** [comment]
That makes sense. :+1:

**Comment by evgeny-leksikov** [comment]
@shefty Thank you! Now that is clear!

**Pull request merged**
