### PR TITLE
prov/rxd: CQ overflow fix

### PR DESCRIPTION
**Pull request by aingerson**
Fixes hfi issue when CQ was overflowed with extra ACKs

### CODE REVIEW

**Comment by shefty** [comment]
Does rxd ask for RM_ENABLED?

**Comment by aingerson** [comment]
Negatory, capt'n

**Comment by shefty** [comment]
Basically, I'm wondering if this fix should move down into the verbs provider.

**Comment by aingerson** [comment]
Hmm, probably. Want me to move it?

**Comment by shefty** [comment]
I'm not sure if it should be moved.  Without RM_ENABLED set, the rxd provider is responsible for avoiding overflow. So, the patch makes sense in that case.

You can try to enable RM and see if verbs handles this correctly or not.

**Comment by aingerson** [comment]
Tried dropping the patch and turning on RM_ENABLED instead but it still hangs on verbs hfi

**Comment by shefty** [comment]
All righty then...  I'm inclined to keep this patch as-is, since it's now passed CI, merge it, and go with it for 1.7.  I'm still not sure if rxd should require RM_ENABLED or not.  With RM, we push the change down, but at the cost of now adding a new requirement to the DGRAM providers.

**Pull request merged**
