### PR TITLE
util: Update to cirque, addition of freestack, plus man page tweak

### PR DESCRIPTION
**Pull request by shefty**
2 of these commits are from PR #1793, which are helper functionality that will be used by at least the shared memory provider.

### CODE REVIEW

**Comment by bturrubiates** [comment]
nit: it looks like a couple of the line continuations in the macros are not aligned

**Comment by shefty** [comment]
The alignment looks fine in my editor.  They are tabbed out.

**Comment by bturrubiates** [comment]
> The alignment looks fine in my editor. They are tabbed out.

Once again it's the Github file viewer failing me. I checked out your branch locally and can see that it is indeed fine. 

Does [this](https://github.com/shefty/libfabric/blob/master/include/fi_mem.h) also render wrong for you?

**Comment by shefty** [comment]
That link looks fine to me.  I'm viewing from firefox.

**Comment by bturrubiates** [comment]
> That link looks fine to me. I'm viewing from firefox.

Just tried Safari. Looks like it's just Chrome rendering it wrong....

**Comment by jithinjosepkl** [comment]
:+1:

**Pull request merged**
