### PR TITLE
verbs RDM. fix of debug build + refactoring send/recv part + rma read/write/inject

### PR DESCRIPTION
**Pull request by evgeny-leksikov**
1) Commit #3c27306 fixes debug build
Others are nice to have
2) Refactoring send/recv paths + request structure
3) Implementation of rma read/write/inject

### CODE REVIEW

**Comment by evgeny-leksikov** [comment]
Not signed-off. Closed.

**Comment by shefty** [comment]
Note that you don't have to close the PR.  You can just update the commits and re-push.  Github will automatically update the PR with the updated commits.

**Comment by evgeny-leksikov** [comment]
Thanks.

**Comment by evgeny-leksikov** [comment]
See #1605

**Pull request closed without merging**
