### PR TITLE
fabtests/pytest/efa: add mr test

### PR DESCRIPTION
**Pull request by wzamazon**
add test cases for memory registration for both host memory and cuda memory

### CODE REVIEW

**Review by shijin-aws — APPROVED** [review]

**Comment by wzamazon** [comment]
@aingerson @shefty 

Do we need to look into the "continuous-integration/jenkins/pr-head" failure for this PR?

**Comment by aingerson** [comment]
@wzamazon No, they are unrelated. Ignore. Sorry about all the failures. We are working on them!

**Comment by aingerson** [comment]
Btw, none of our CI runs any of the pytest code so anything restricted to that section should never trigger a real jenkins failure on our end.

**Comment by wzamazon** [comment]
Thank you!

**Pull request merged**
