### PR TITLE
Fix mlx warnings

### PR DESCRIPTION
**Pull request by jeffhammond**
@alexander-sannikov @gladkovdmitry17 please apply this tiny fix to your PR, as it is required to compiler with `-Werror` using Clang.

### CODE REVIEW

**Comment by shefty** [comment]
Changes part of PR #3255

**Comment by shefty** [comment]
#3255 is pulling in all mlx/ucx testing changes.  Keeping this PR open for tracking purposes.

**Comment by gladkovdmitry17** [comment]
@jeffhammond Can we close this PR? Seems these changes is a part of the master branch.
Thanks

**Comment by jeffhammond** [comment]
Sure. Please close.
-- 
Jeff Hammond
jeff.science@gmail.com
http://jeffhammond.github.io/

**Comment by shefty** [comment]
Sorry - I missed that these were merged separately.

**Pull request closed without merging**
