### PR TITLE
core + tcp: Optimizations to tcp progress handling

### PR DESCRIPTION
**Pull request by shefty**
- Update pollfds to use a sparse array of fd's, rather than trying to compact it. This allows us to reference an entry in the pollfds using the fd as an index, eliminating linear searches for a matching entry.
- Optimize handling of epoll_mod in pollfds equivalent. When modifying an fd, handle this directly in the call. This replaces a memory allocation and the queuing of the modification for asynchronous processing.
- Update epoll/pollfds abstractions to return the events which were signaled. This update impacts the sockets provider.
- Update the tcp progress handling to act based on which events were set and to skip trying to progress send or receives if the corresponding event is not set.

PR updated with lost changes to verbs, smr, and usnic from 1st submission.  All updated to new epoll API.

### CODE REVIEW

**Comment by shefty** [comment]
AWS failure is known issue.  Intel CI failure is an issue with the CI itself -- not sure what's wrong, but the tests didn't run.  And Travis CI is related to this PR.  The epoll changes break on OS X, which I'm going to guess is because the epoll_event struct there differs from Linux.

**Comment by wzamazon** [comment]
bot:aws:retest

**Comment by wzamazon** [comment]
Testing the fix to AWS CI.

**Comment by shefty** [comment]
AWS CI issues are fixed.  Failure now is different (an EFA related test).

**Comment by wzamazon** [comment]
This error looks like a transient GPU hardware issue. we have seen this happen before

**Comment by wzamazon** [comment]
bot:aws:retest

**Pull request merged**
