### PR TITLE
verbs: Refactor verbs provider

### PR DESCRIPTION
**Pull request by shefty**
This series moves the verbs provider code from fi_verbs.c into several source files.  This change is a pre-cursor to adding support for RDM endpoints.  The code itself is nearly unchanged.  Static is removed from some function declarations, and a few one-line functions are added to set function pointers.

The only notable changes are the removal of an unneeded function call (is a separate commit), and the merging of 3 small functions that only call each other into one function (handled as part of the re-factoring).  All other changes simply move existing code into new files. The 'additional' lines shown as part of the change request are a result of duplicating the license in each new file.

### CODE REVIEW

**Comment by a-ilango** [comment]
> merging of 3 small functions that only call each other into one function
Which patch has this change? Can you please mention this in the corresponding patch?

**Comment by shefty** [comment]
This is 'Move base message endpoint support into separate file'

**Comment by shefty** [comment]
Updated commit message regarding the merging of the 3 functions done as part of the refactoring.  The merging happened rather innocently as part of creating the patch.  I had originally moved the fi_ibv_msg_ep_enable function, but left the others.  When the build complained, I noticed that I needed fi_ibv_msg_ep_create_qp, but it was only called from one place.  Since the create_qp call was only 2 lines, I just folded it into enable.  The build then complained about fi_ibv_msg_ep_qp_init_attr, resulting in a similar solution.

**Comment by a-ilango** [comment]
Thanks, the rest of changes look good.

**Pull request merged**
