### PR TITLE
Efa 3 new refactors v2

### PR DESCRIPTION
**Pull request by wzamazon**
3 refactors:
1. refactor rxr_cq_process_rts() and related functions
2. refactor rxr_tx() and related functions
3. refactor rxr_inline_mr_reg()

### CODE REVIEW

**Comment by wzamazon** [comment]
aws error is : 
multi-node.sh: line 124: /var/lib/jenkins/workspace/multi-node/PROVIDER/efa/label/rhel/libfabric-ci-scripts/172.31.4.129_execute_runfabtests.sh: No such file or directory

**Comment by shefty** [comment]
Can this PR be deferred until after 1.9?

**Comment by wzamazon** [comment]
Hi Sean,

This change is self contained to the EFA provider therefore should not block RC1, if that's what you are  worried abut. Moreover, it also forms the basis of one protocol change that we want to get in before 1.9-GA.

**Comment by shefty** [comment]
The Intel CI failure is unrelated

**Comment by shefty** [comment]
If this is ready, I can create rc1 after merging.  I had to delay rc1 because of some CI related issues that I wanted to have resolved prior to creating the package.  I believe everything else is ready now.

**Comment by wzamazon** [comment]
This patch has already passed our internal review. I have asked Robert or Raghu to approve it here.

**Pull request merged**
