### PR TITLE
v1.11.1rc1

### PR DESCRIPTION
**Pull request by shefty**
Prepare for v1.11.1 release.

Signed-off-by: Sean Hefty <sean.hefty@intel.com>

### CODE REVIEW

**Comment by jswaro** [comment]
`git cherry-pick  4dfae6d8e 6d10aeac4 fecfa3a93 78c1c5de9 6f0db77bc 85842741f`

For the changes discussed in the contrib/cray PR.

**Comment by shefty** [comment]
@rwespetal - I don't need you to restart AWS CI, but can you tell me what the failures are?  Are we just unable to allocate resources for CI at the moment?

**Comment by rwespetal** [comment]
> @rwespetal - I don't need you to restart AWS CI, but can you tell me what the failures are? Are we just unable to allocate resources for CI at the moment?

Yes, we've been having trouble allocating resources for the NCCL tests the past few days. Now it appears that another bug has caused the NCCL tests to fail consistently that we will have to look into.

For now the nccl-single-node and nccl-multi-node tests can be ignored. I'll have to go run those tests manually against the release candidate.

**Comment by shefty** [comment]
I plan on publishing the official rc1 package later today, as soon as the other CI's complete.

**Comment by rwespetal** [comment]
I ran one of the NCCL tests against this PR and it passed.

**Pull request merged**
