### PR TITLE
Enable dl builds for Travis.

### LINKED ISSUE #2108: add dl build to Travis
Adding a dl build to Travis would ensure that problems would be caught before merging the problematic code.

### PR DESCRIPTION
**Pull request by bturrubiates**
Closes #2108.

Signed-off-by: Ben Turrubiates <bturrubi@cisco.com>

### CODE REVIEW

**Comment by jsquyres** [comment]
👍

**Comment by bturrubiates** [comment]
Travis should fail.

**Comment by hppritcha** [comment]
NERSC had issues this weekend.
bot:retest

**Comment by hppritcha** [comment]
sorry.  Ignore LANL-cray for today.  I need to enable testing on edison since cori will be down for next week or so.

**Comment by bturrubiates** [comment]
> sorry. Ignore LANL-cray for today. I need to enable testing on edison since cori will be down for next week or so.

Okay, merging this.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Pull request merged**
