### PR TITLE
prov/psm3: update code to match IEFS 11.1.0.0.178 release

### PR DESCRIPTION
**Pull request by acgoldma**
https://github.com/intel/eth-psm3-fi/releases/tag/v11.1.0.0

### CODE REVIEW

**Comment by acgoldma** [comment]
bot:aws:restest

**Comment by acgoldma** [comment]
bot:aws:retest

**Comment by acgoldma** [comment]
@ofiwg/aws-efa-maintainers, Just want to confirm AWS issues is unrelated to my changes which are isolated to psm3 provider, so that I can merge?

**Comment by wckzhang** [comment]
I looked at the errors, seems completely unrelated, go ahead

**Comment by acgoldma** [comment]
@wckzhang, Thank you for looking into it.

**Pull request merged**
