### PR TITLE
[v1.19.x] contrib/aws: add jenkinsfile

### PR DESCRIPTION
**Pull request by a-szegel**
Signed-off-by: Seth Zegelstein <szegel@amazon.com>
(cherry picked from commit 7175ff6e6f0d8feb9d41c761c600a3e91eb00c48)

### CODE REVIEW

**Review by j-xiong — APPROVED** [review]

**Comment by a-szegel** [comment]
bot:aws:retest

**Comment by a-szegel** [comment]
aws CI timed out... bot:aws:retest

**Comment by a-szegel** [comment]
looks like real failures in ompi5 tests for all branches before v1.20.x

**Comment by shijin-aws** [comment]
@zachdworkin is it safe to ignore Intel CI failure for this PR?

**Comment by zachdworkin** [comment]
@shijin-aws yes and for the future you can ignore intel ci failures for your changes that only touch aws ci things.

**Pull request merged**
