### PR TITLE
.github/workflows: add make distcheck

### PR DESCRIPTION
**Pull request by aingerson**
Signed-off-by: Alexia Ingerson <alexia.ingerson@intel.com>

### CODE REVIEW

**Comment by aingerson** [comment]
Opening this separately to make sure this fails without #8084

**Review by wzamazon — APPROVED** [review]

**Comment by aingerson** [comment]
Had to include some extra edits because it couldn't find rdma-core but now it is properly catching the missing header

**Comment by aingerson** [comment]
Will rebase to verify fix once #8084 is merged

**Comment by aingerson** [comment]
Rebased to pull in missing header to make sure that resolves the failures

**Comment by aingerson** [comment]
Workflow action successfully ran distcheck and passed after #8084 
Other 2 CIs are still running/waiting for resources but they should be unrelated. Can be merged whenever.

**Comment by shefty** [comment]
Thanks!

**Pull request merged**
