### PR TITLE
contrib/buildrpm: Add source build option

### PR DESCRIPTION
**Pull request by jswaro**
This commit adds the option to build binary and source
packages using the existing build script.

Signed-off-by: James Swaro <james.swaro@hpe.com>

### CODE REVIEW

**Comment by shefty** [comment]
Do we need the option to build source, versus just always building it.

**Comment by jswaro** [comment]
> Do we need the option to build source, versus just always building it.

I think there is value in providing a source RPM for redistribution. I intend to provide SRPMs in addition to the binaries that are provided today. This PR provides this functionality to the community.

**Comment by shefty** [comment]
My question wasn't whether or not to have a SRPM, but whether we shouldn't just always build it.

**Comment by jswaro** [comment]
> My question wasn't whether or not to have a SRPM, but whether we shouldn't just always build it.

I see. I did not want to change the prior behavior since this is used by more than just me. I would be fine with making source RPMs by default.

**Review by shefty — APPROVED** [review]
I'm fine adding the option or making SRPM build also the default

**Comment by jswaro** [comment]
> I'm fine adding the option or making SRPM build also the default

Ok, I'll make it the default. I'd prefer it that way

**Pull request merged**
