### PR TITLE
contrib/intel/jenkins: Migrate multinode tests to use new CI

### PR DESCRIPTION
**Pull request by zachdworkin**

### CODE REVIEW

**Comment by zachdworkin** [comment]
@j-xiong this can be merged next week after the release

**Review by j-xiong — APPROVED** [review]

**Comment by j-xiong** [comment]
@zachdworkin The release is done.

**Comment by zachdworkin** [comment]
> @zachdworkin The release is done.

In that case we can merge this today :)

**Comment by zachdworkin** [comment]
no need to wait for AWS CI since this change is to Intel CI jenkinsfile

**Pull request merged**
