### PR TITLE
[v1.17.x] contrib/intel/jenkins: Update with files from main

### PR DESCRIPTION
**Pull request by j-xiong**
Old files don't work properly with current CI infrastructure. The difference between the branch and main is too big to cherry-pick.

The 'net' provider is no long tested since it has been renamed to 'tcp' in main.

### CODE REVIEW

**Comment by j-xiong** [comment]
Change to Jenkinsfile won't take effect until merged. @shefty Any way to test this before merging? The updated files are exactly the same as main.

**Comment by shefty** [comment]
@zachdworkin can force test the changes through some manual intervention

**Comment by zachdworkin** [comment]
@shefty jenkins is testing them now. The jenkinsfile is replaced with the one in this PR and it won't run the upstream scripts in the contrib/intel/jenkins folder but will instead run this PR's scripts.

**Comment by shefty** [comment]
Passed Intel CI

**Pull request merged**
