### PR TITLE
prov/psm: eliminate the complains from gcc 4.9.2

### PR DESCRIPTION
**Pull request by j-xiong**

### CODE REVIEW

**Comment by j-xiong** [comment]
the majority of the changes are within the psm provider. @shefty: there are trivia changes to two lines in "fi_list.h". gcc 4.9.2 complains about the return value being ignored. adding the cast eliminate the complain, but maybe we need actually check the return value?

**Comment by shefty** [comment]
@jithinjosepkl - These calls are used by the sockets provider.  Jithin, can you see what would happen if we checked the return values in the calls that Jianxin has updated?  We really should be checking the return values.

**Comment by shefty** [comment]
Opened issue #620 to track this.  Merging this request, as it doesn't make it worse.

**Comment by jithinjosepkl** [comment]
Yes, return value check for read/write in reset/signal calls should be fine. 
It will not affect sockets provider.
Btw, similar checks are also needed in fi_rbuf signal/reset calls.

**Pull request merged**
