### PR TITLE
v1.14.x: cherry picked fixes from main

### PR DESCRIPTION
**Pull request by shefty**
prep for v1.14.1rc2

@ofiwg/aws-efa-team if there are EFA changes needed for v1.14.1 not yet in the branch, please add.

### CODE REVIEW

**Comment by shefty** [comment]
bot:aws:retest

**Comment by shijin-aws** [comment]
@shefty seems there is some issue with AWS CI right now. We will let you know when it get fixed.

**Comment by shijin-aws** [comment]
bot:retest:aws

**Comment by shijin-aws** [comment]
@shefty The issue is fixed. I retriggered the CI.

**Comment by shefty** [comment]
@shijin-aws - thanks

**Review by j-xiong — APPROVED** [review]

**Comment by shefty** [comment]
Rebased - there was a patch included in the PR that was already in the branch.

**Comment by j-xiong** [comment]
Tried twice, got the same error from Intel ci:
```
14:29:42  /home/cstbuild/ofi-Install/libfabric/ofi_libfabric/PR-7568/4/dbg/bin/runfabtests.sh: line 582: kill: (3329544) - No such process
14:29:42  fi_ubertest:                                      Server returns 124, client returns 124
14:29:42  - name:   fi_ubertest
14:29:42    result: Fail [/]
14:29:42    time:   301
```

**Comment by shefty** [comment]
Yes, I've reproduced locally.  Debugging.

**Comment by aingerson** [comment]
Me too

**Comment by j-xiong** [comment]
The error code 124 may seem weird. It's the return code of the "timeout" command.

**Comment by aingerson** [comment]
@jianxin The writedata+counter test is hanging causing a timeout

**Comment by aingerson** [comment]
@shefty commit 618160a0377f40d48a7706128c26a8553493688d is the problem

**Comment by shefty** [comment]
@aingerson - is the commit wrong, or is there another change that's needed?

**Comment by aingerson** [comment]
@shefty I'm trying to figure that out... Based on the commit and the upstream diff everything looks ok... Did we decide it was correct to say a cq with selective completion would not report a completion even for cq data?

**Comment by shefty** [comment]
I think we decided that the app was dumb to set it that way, but ended up with selective completion as the default.

**Comment by shefty** [comment]
Removed commit Alexia pointed out above.  We don't know why it's causing issues in this branch and not main.  Still investigating.

**Pull request merged**
