### PR TITLE
prov/sockets: Fix an incorrect default filling of the cntr attr

### PR DESCRIPTION
**Pull request by gladkovdmitry17**
Separated changes from #3497

Signed-off-by: Dmitry Gladkov <dmitry.gladkov@intel.com>

### CODE REVIEW

**Comment by shefty** [comment]
Can you update the commit comment please?  calling this a typo doesn't indicate the severity of the issue.

**Comment by gladkovdmitry17** [comment]
> Can you update the commit comment please? calling this a typo doesn't indicate the severity of the issue.

Sure. Done

**Comment by gladkovdmitry17** [comment]
> shefty added for-1.5.x for-1.4.x labels 18 hours ago

@shefty  Should I prepare the fixes against the v1.5.x and v1.4.x branches?

**Comment by shefty** [comment]
I'll handle the backports.  Thanks though.

**Pull request merged**
