### PR TITLE
prov/verbs: Select max inline size possible

### PR DESCRIPTION
**Pull request by a-ilango**
- prov/verbs: Select highest possible inject size for verbs/MSG as well
- prov/rxm: Always do progress when fi_send from MSG provider returns -FI_EAGAIN

### CODE REVIEW

**Comment by shefty** [comment]
IIRC, increasing the max inline size used to have a negative affect on throughput. Does the actual size that is used drop based on user hints?

**Comment by a-ilango** [comment]
> IIRC, increasing the max inline size used to have a negative affect on throughput. Does the actual size that is used drop based on user hints?

Good catch. It does seem to have a negative effect on BW. But higher inline size improves the latency 
 for small messages considerably.

The man pages define this attribute as maximum inject size allowed by the provider so it doesn't drop based on user hints. However there is an env variable that can be used to limit the inject size.

**Comment by shefty** [comment]
I would reduce the max inline size based on the user's inject_size hint if it's non-zero.  The man pages indicate that this is the max size associated with an inject operation, not necessarily the largest value supportable by a provider.  Keeping the env var is fine, but it would be better to use the API to control this, since it's available.

**Comment by a-ilango** [comment]
> The man pages indicate that this is the max size associated with an inject operation, not necessarily the largest value supportable by a provider

Got it. Thanks.
>I would reduce the max inline size based on the user's inject_size hint if it's non-zero.

It seems ofi_alter_info already handles this case so I think we're good.

**Comment by a-ilango** [comment]
@shefty are there any more comments on this PR?

**Comment by shefty** [comment]
nope - good here

**Comment by gladkovdmitry17** [comment]
@a-ilango @shefty 
I'm attaching chart that proves performance improvements can be achieved with this patch. 
It works just fine! Thanks to you all!
image

```
bytes | RxM/verbs   old | RxM/verbs   master | verbs/RDM   master
0 | 2.03 | 1.6 | 1.13
1 | 2.03 | 1.62 | 1.13
2 | 2.04 | 1.61 | 1.13
4 | 2.04 | 1.61 | 1.13
8 | 2.05 | 1.61 | 1.13
16 | 2.05 | 1.61 | 1.16
32 | 2.06 | 1.61 | 1.2
64 | 2.08 | 1.64 | 1.21
128 | 2.12 | 1.69 | 1.26
256 | 2.18 | 2.15 | 1.74
512 | 2.3 | 2.64 | 2.19
1024 | 2.5 | 2.48 | 1.99
2048 | 2.93 | 2.96 | 2.4
4096 | 3.93 | 3.96 | 3.34
8192 | 5.59 | 5.7 | 5.02
16384 | 8.89 | 8.23 | 6.62

```

**Pull request merged**
