### PR TITLE
verbs/RDM: Update Readme, news and man pages.

### PR DESCRIPTION
**Pull request by a-ilango**
Can these changes make into 1.3?

### CODE REVIEW

**Comment by a-ilango** [comment]
@evgeny-leksikov Let me know if these look good.

**Comment by shefty** [comment]
:+1:  - yes, let's get this into 1.3, as they are documentation updates only

**Comment by evgeny-leksikov** [comment]
One more limitation versus ep_msg is ep_rdm doesn't support iWarp yet.

**Comment by a-ilango** [comment]
> One more limitation versus ep_msg is ep_rdm doesn't support iWarp yet.

Added a bullet for this.

**Comment by evgeny-leksikov** [comment]
:+1:

**Comment by lanl-ompi** [comment]
bot:retest

**Comment by lanl-ompi** [comment]
Test succeeded

**Comment by lanl-ompi** [comment]
Test succeeded

**Pull request merged**
