### PR TITLE
 prov/psm2, sockets: Adjust maximum message sizes

### PR DESCRIPTION
**Pull request by dmitrygladkov**
- prov/sockets: Increase maximum message size
- prov/psm2: Adjust psm2 maximum message size to consider libpsm2 headers

### CODE REVIEW

**Comment by shefty** [comment]
Can you enhance the commit messages by describing why the sizes are being increased?  I.e. larger sizes are supported and this works around a bug in the MPICH CH4 layer.

**Comment by j-xiong** [comment]
Per my past experience, achievable PSM2 message size was not reduced by 8192. Notice that large size message uses a difference protocol from small messages.

**Comment by shefty** [comment]
@j-xiong -- are you saying the psm changes should be dropped?

**Comment by j-xiong** [comment]
@shefty Yes that's what I mean.

**Comment by j-xiong** [comment]
And I just verified that's still the case. There was a PSM2 library bug that reduced the usable size by one page, but that has been fixed.

**Comment by hajimefu** [comment]
@shefty @dmitrygladkov do you have a pointer to the CH4 bug mentioned here?

**Comment by shefty** [comment]
@hajimefu - I do not, only some internal emails that vaguely describe the problem.  There's some issue with large message transfers over 8 MB when using the socket provider.  (The socket provider arbitrarily limits messages to 8 MB).

**Comment by shefty** [comment]
socket changes merged through #4347 and cherry picked for v1.6.x.  closing since psm changes aren't needed.

**Pull request closed without merging**
