### PR TITLE
[v1.11.x] EFA fork and cache fixes for 1.11.x

### PR DESCRIPTION
**Pull request by rwespetal**
Cherry-pick the patches to handle detecting fork and to disable the cache for applications that do not require a cache but require fork (NCCL).

### CODE REVIEW

**Review by bwbarrett — APPROVED** [review]

**Comment by rwespetal** [comment]
@shefty - anything of note from the Intel CI failure?

**Comment by shefty** [comment]
@rwespetal - I was just reading the logs.  The failure was in fi_ubertest with the shm provider. It's not clear to me what exactly failed in that test.

**Review by shefty — APPROVED** [review]

**Comment by aingerson** [comment]
Looks unrelated to these changes but I'll look into it to see what happened.

**Comment by rwespetal** [comment]
Thank you.

**Comment by shefty** [comment]
Is this the last PR from the AWS side needed for 1.11.1?

**Comment by rwespetal** [comment]
I thought so but one of our devs found a hang running an MPI one-sided test over EFA last night. Disabling the SHM medium message protocol fixes the issue. Perhaps #6323 fixes it?

**Comment by shefty** [comment]
We're seeing the shm hang as well.  #6323 prevents the hang, maybe.  But we're not sure why we're seeing the hang to understand if adding a lock fixes it.

**Comment by aingerson** [comment]
It sounds like a different hang though. Are you talking about the inject protocol or the SAR protocol? I'm seeing it with the SAR protocol.

**Comment by shefty** [comment]
It called out the medium message protocol, which is SAR.

**Comment by rwespetal** [comment]
Yes, the SAR protocol. Here is what we are running to reproduce the bug, note the change in `FI_EFA_SHM_MAX_MEDIUM_SIZE`.

Fails:
```
mpirun -n 96 -N 48 -hostfile /home/ec2-user/hfile -x FI_EFA_ENABLE_SHM_TRANSFER=1 -x FI_LOG_LEVEL=warn -x FI_EFA_SHM_MAX_MEDIUM_SIZE=4096  IMB-RMA -npmin 96 -iter 200 -msglog 11:12  All_put_all
```
Passes:
```
mpirun -n 96 -N 48 -hostfile /home/ec2-user/hfile -x FI_EFA_ENABLE_SHM_TRANSFER=1 -x FI_LOG_LEVEL=warn -x FI_EFA_SHM_MAX_MEDIUM_SIZE=8192 IMB-RMA -npmin 96 -iter 200 -msglog 11:12  All_put_all
```

**Comment by rwespetal** [comment]
Or, perhaps not. Now that I write that out this could be an EFA bug in our medium message protocol. We'll continue to investigate.

**Comment by aingerson** [comment]
@rwespetal Thanks for the info. What does the FI_EFA_SHM_MAX_MEDIUM_SIZE define? I can't find the variable used anywhere in the EFA provider but maybe I'm missing something?

**Comment by rwespetal** [comment]
It'll show up in the code as `shm_max_medium_size`. It is the message switchover point where EFA will use its eager protocol (`fi_send()` to SHM) versus its read protocol (send an RMA iov and have the SHM receiver call `fi_read()`).

**Comment by aingerson** [comment]
Yeah, I see it defined and initialized but I never see the value actually used.

**Comment by shefty** [comment]
search for rxr_env.shm_max_medium_size.  It is used in rxr_pkt_req_max_data_size()

**Comment by aingerson** [comment]
Oh sorry, it blended in with the next line on my search. I see it now.

**Pull request merged**
