### PR TITLE
usnic: change of fabric/domain naming

### PR DESCRIPTION
**Pull request by piroux**
Fixes ofiwg/libfabric#2052

Signed-off-by: Pierre Roux <piroux@cisco.com>

### CODE REVIEW

**Comment by lanl-ompi** [comment]
bot:retest

**Comment by jsquyres** [comment]
👍

**Comment by bturrubiates** [comment]
👍

**Comment by jsquyres** [comment]
Checks out against https://github.com/open-mpi/ompi/pull/1989.

Travis seems to be heavily backed up right now; when it finishes, we can merge.

**Pull request merged**
