### PR TITLE
v1.18.x

### PR DESCRIPTION
**Pull request by shefty**

### CODE REVIEW

**Comment by wzamazon** [comment]
bot:aws:retest

**Comment by shefty** [comment]
rebased to pick up latest changes

**Comment by shefty** [comment]
Intel CI failures are DAOS (unsure if that's running), and repeated failures with fi_rdm_tagged_bw, which is a known failure (unsure if related to provider or test itself).

**Comment by shefty** [comment]
bot:aws:retest

**Comment by wzamazon** [comment]
Sorry to bother you! We just discovered a bug which will affect v1.18.x. The main branch fix is in  https://github.com/ofiwg/libfabric/pull/9093. Is it too late to include for 1.18.1?

**Comment by wzamazon** [comment]
bot:aws:retest

**Pull request merged**
