### PR TITLE
hmem_neuron.c: Use nrt_memcpy_to_device to copy from host to dev.

### PR DESCRIPTION
**Pull request by shijin-aws**
neuron added a memcpy function and neuron_copy_to_dev()
should use it to copy data from host to device.

Signed-off-by: Shi Jin <sjina@amazon.com>

### CODE REVIEW

**Comment by shefty** [comment]
Is this needed for v1.15.2?

**Review by bwbarrett — CHANGES_REQUESTED** [review]
The commit message background on write combining is irrelevant.  We should have a memcpy in the NRT runtime because it's a path to optimizing memcpys from host to device memory (rather than memcpy(), which is really designed for host to host copies).  This otherwise looks good, but please update the commit message.

**Comment by shijin-aws** [comment]
@bwbarrett Thanks, updated the commit message.

**Review by bwbarrett — APPROVED** [review]

**Comment by shijin-aws** [comment]
@shefty 

> Is this needed for v1.15.2?

I think it needs to be backported to v1.15.x. Will do it today and update the EFA news

**Comment by shijin-aws** [comment]
Will merge after CI passes. Will backport to v1.15.x

**Comment by shijin-aws** [comment]
bot:aws:retest

**Pull request merged**
