### PR TITLE
NEWS.md: first version

### PR DESCRIPTION
**Pull request by jsquyres**
Add sections for 1.0.0, 1.1.0, 1.1.1, and 1.2.0.  Use markdown to make it look pretty in web browsers, yet still be readable by humans.

In each section >=v1.1.0, have a subsection for:

- general notes
- each provider

Signed-off-by: Jeff Squyres <jsquyres@cisco.com>

### CODE REVIEW

**Comment by patrickmacarthur** [comment]
Is it possible to get GitHub to format the file as markdown without giving it a .md extension?

I only ask because the autotools assumes that the file is specifically named `NEWS` (it gets automatically distributed in the tarball if it exists and you can add "check-news" to the automake options and it will verify that the current release number appears in the NEWS file).

If we decide not to rename it, then it needs to be added to `Makefile.am` so it gets included in the tarballs.

**Comment by jsquyres** [comment]
@patrickmacarthur Github-without-.md: not that I'm aware of...  I did neglect to list NEWS.md in Makefile.am; thanks.  Fixed.

**Comment by jsquyres** [comment]
The idea here is that this is a first cut.  All the other provider authors can PR in their own content for the 1.1.0, 1.1.1, and if they have anything yet, the 1.2.0 sections.

Once we have it filled out nicely, we can PR the NEWS.md file (without the 1.2.0 section) over to the v1.1.x branch.

**Comment by shefty** [comment]
:+1:

**Pull request merged**
