### PR TITLE
[v1.13.x] prov/efa: only set FI_HMEM hint for SHM getinfo when requested

### PR DESCRIPTION
**Pull request by rwespetal**
The SHM provider disables CMA when FI_HMEM is set so we should only pass
that hint when the app asks for FI_HMEM.

Signed-off-by: Robert Wespetal <wesper@amazon.com>
(cherry picked from commit a429ef69d12459a219f5178014da1f02b887c4d4)

### CODE REVIEW

**Review by wzamazon — APPROVED** [review]

**Comment by wzamazon** [comment]
bot:lanl:retest

**Comment by wzamazon** [comment]
@rajachan Can you help retrigger the lanl CI?

**Comment by rajachan** [comment]
You had the right incantation, looks like it reran and passed.

**Comment by wzamazon** [comment]
@rajachan  Thank you!

**Pull request merged**
