### PR TITLE
prov/psm3: Fix building chksum with different builddir

### PR DESCRIPTION
**Pull request by acgoldma**
Update timestamp only when checksum changes.

Fixes: #6630
Signed-off-by: Goldman, Adam <adam.goldman@intel.com>

### CODE REVIEW

**Comment by acgoldma** [comment]
AWS failure unrelated.

**Comment by acgoldma** [comment]
bot:aws:retest

**Comment by jsquyres** [comment]
The VPATH fixes are needed, but you should probably consolidate all these PSM3 build fixes in to a single PR.  Otherwise, you're just going to have conflicts and have to resolve them in whichever PRs are not merged first.

Indeed, there should be no fixing of the `all-local` rule, anyway, because that rule should not be used in a provider.

**Comment by shefty** [comment]
@acgoldma - I agree with Jeff here.  Please use a single PR to collect all build fixes.  That will also make it easier to identify the fixes to pull in v1.12.x.

**Comment by acgoldma** [comment]
> @acgoldma - I agree with Jeff here. Please use a single PR to collect all build fixes. That will also make it easier to identify the fixes to pull in v1.12.x.

Makes sense to me, I have a few that are already merged into master, I am guessing this is just for new PRs (unmerged) and I can add links to the ones already merged for tracking into v1.12.x?

**Comment by shefty** [comment]
This is only for new PRs.  For v1.12.x, please open a separate PR with all cherry picked fixes that are needed.  You can delay creating the v1.12.x PR until all fixes are ready, or pick what's available today and add others later.  Your choice.

**Comment by jsquyres** [comment]
It would be good to have a single PR, and address all the issues:

- Do not re-invent Make or Automake or Autoconf mechanisms
- Do not hijack global rules
- If you're going to only do the checksum thing once, do it during configure. Otherwise, do it properly during the build.
- Uplevel the checksum thing.

This is all I recall offhand; I don't remember if there were more.

**Comment by acgoldma** [comment]
I plan to merge this to fix the small bug in the linked issue. I will create a larger PR for further fixes.

**Pull request merged**
