### PR TITLE
pingpong: Add support of FI_MSG_PREFIX mode

### PR DESCRIPTION
**Pull request by shefty**
Signed-off-by: Dmitry Gladkov <dmitry.gladkov@intel.com>

### CODE REVIEW

**Comment by shefty** [comment]
@bturrubiates @jsquyres - Can someone at Cisco verify that this works with usnic?  I don't know of any other way to verify these changes.

**Comment by gladkovdmitry17** [comment]
@shefty Thanks!

**Comment by bturrubiates** [comment]
> @bturrubiates @jsquyres - Can someone at Cisco verify that this works with usnic? I don't know of any other way to verify these changes.

Sure, can do

**Comment by bturrubiates** [comment]
@shefty works after this fix: 

```diff
diff --git a/util/pingpong.c b/util/pingpong.c
index fca8cf3b..9651e62f 100644
--- a/util/pingpong.c
+++ b/util/pingpong.c
@@ -1854,7 +1854,7 @@ static int pp_finalize(struct ct_pingpong *ct)

        strcpy(ct->tx_buf, "fin");
        iov.iov_base = ct->tx_buf;
-       iov.iov_len = 4;
+       iov.iov_len = 4 + ct->msg_prefix_size;

        if (!(ct->fi->caps & FI_TAGGED)) {
                memset(&msg, 0, sizeof(msg));
```

**Comment by shefty** [comment]
@bturrubiates - thanks - I've updated the PR with the proposed changes.

**Pull request merged**
