### PR TITLE
prov/verbs: add postponed inject implementation for ep rdm

### PR DESCRIPTION
**Pull request by evgeny-leksikov**
Add postponed inject implementation to prevent blocking of sender (by FI_EAGAIN err code) when busy network resources should be released by receiver but it's out of OFI stack.

See also conversation to PR https://github.com/ofiwg/fabtests/pull/494

@a-ilango @shefty

### CODE REVIEW

**Comment by shefty** [comment]
I need to be convinced that adding an additional layer of software queuing is beneficial.  This is not the way other providers, including the utility providers will work.  If the underlying resources are not ready or the queues are full, the provider will return EAGAIN and ask the app to return/queue operations.

**Comment by sayantansur** [comment]
software queueing impacts the progress model too, so do it with care. imho, if you have a software queue, you can never have auto_progress.

**Comment by evgeny-leksikov** [comment]
@shefty All my pros&cons are listed by link from the description. I just clarify it again with links,(probably) all MPI over OFI implementations have MPI_Isend implementation according to [OFI libfabric Tutorial](http://www.slideshare.net/dgoodell/ofi-libfabric-tutorial), foils 98-99 and [-FI_EAGAIN err handling](https://ofiwg.github.io/libfabric/master/man/fi_msg.3.html), and this makes its blocking in corner cases. Obviously, "normal app" should not lead to this scenario and postponed queue will not be used, but this is erroneous behavior of MPI.

@sayantansur I have to implement auto_progress model to support such things as truly passive remote completion for RMA, immediate for TAGGED, etc, over ib_verbs. So, I think there are enough reasons to have auto_progress model.

**Comment by sayantansur** [comment]
@evgeny-leksikov - correct. we need auto_progress model. I was saying that if you have a software send queue, how do you intend to drain that without the application calling into OFI again?

**Comment by evgeny-leksikov** [comment]
@sayantansur untill auto_progress is not implemented, send queue is drained by internal poll function which is called by any other OFI function. Note, receiver frees sender's buffers by rdma write operation. So, no need do OFI call on sender for this, it's needed only for processing of postponed queue. But with implemented auto_progress, I'll be able to process it in background.

**Comment by sayantansur** [comment]
that's exactly what I was trying to hint at. you will need a progress thread even for operations that should not require it (i.e. non-tagged messages) that verbs hardware is typically able to provide auto_progress for. complicates your design a bit, but I guess you're planning to have that thread regardless?

**Comment by evgeny-leksikov** [comment]
Of cause, at least for reasons that I mentioned above. And I'm not sure it's possible to implement without progress thread. I just trying to say, these 2 features completes each other but not exclude.

**Comment by shefty** [comment]
To be clear, I view this as an API level discussion - not a verbs implementation discussion.  The question is whether applications should expect that FI_INJECT operations will queue the data when network resources are full.  Before committing to changing how a given provider works, the behavior at the API level needs to be agreed upon.

**Comment by sayantansur** [comment]
Good point. Yes, I agree that this is an API level discussion.

**Pull request closed without merging**
