### PR TITLE
spec: Abstract version with symbolic link

### PR DESCRIPTION
**Pull request by patrickbueb**
Create a symbolic link to abstract the version named directory. This will
assist the automated test process.

Signed-off-by: Patrick Bueb <patrick.bueb@hpe.com>

### CODE REVIEW

**Comment by patrickbueb** [comment]
This change facilitates automated testing by creating symbolic link to the newly installed version using a well known name ('default'). Additionally, since the link creation is controlled by an optional flag, prototype versions can be tested while retaining the previous known good version.

**Comment by shefty** [comment]
aws:bot:retest

**Comment by patrickbueb** [comment]
aws:bot:retest

**Comment by patrickbueb** [comment]
@ofiwg/aws-efa-team - It looks like this was failing prior to my pull request.  Is anyone looking at this?

@shefty - This test looks like it it timing out on Mac.  I there anything I should do?

**Comment by rwespetal** [comment]
AWS CI failure is a known issue so it's unrelated to this PR. An issue for that unrelated failure should be posted soon.

**Comment by shefty** [comment]
I don't understand the OS X issue.  I am looking into the issues with the master.  There was at least a problem with the changes that added rxm_mr and the tcp provider optimizations, which were written without those changes included.

**Comment by patrickbueb** [comment]
aws:bot:retest

**Comment by jswaro** [comment]
@shefty I don't see any issues with this PR related to the failures. Do you mind if we merge it while the other issues get resolved?

**Comment by shefty** [comment]
No issues merging

**Pull request merged**
