### PR TITLE
prov/verbs: connections to self don't need CM private data

### PR DESCRIPTION
**Pull request by fzago-cray**
When a connection is local, don't prepare private data in
fi_ibv_rdm_pack_cm_params(), and don't access private data in
fi_ibv_rdm_unpack_cm_params().

Signed-off-by: Frank Zago <fzago@cray.com>

### CODE REVIEW

**Comment by fzago-cray** [comment]
Untested as I didn't find a test for that code path, but the change is pretty straightforward.

**Comment by gladkovdmitry17** [comment]
I'm okay
But keep it open, I'm going to tests these changes

**Comment by gladkovdmitry17** [comment]
Unfortunately, it breaks something:

```
mpirun -gdb -n 2 test/mpi/coll/alltoallw1
mpigdb: np = 2
mpigdb: attaching to 211645 test/mpi/coll/alltoallw1 nnlmpicl430.inn.intel.com
mpigdb: attaching to 211646 test/mpi/coll/alltoallw1 nnlmpicl430.inn.intel.com
[0,1] (mpigdb) r
[0,1]   Continuing.

[1]     [New Thread 0x2b73d92aa700 (LWP 211696)]
[0]     [New Thread 0x2b83ed77a700 (LWP 211708)]
[1]
[0]
[1]     Program received signal SIGABRT, Aborted.
[0]     Program received signal SIGABRT, Aborted.
[1]     [Switching to Thread 0x2b73d92aa700 (LWP 211696)]
[0]     [Switching to Thread 0x2b83ed77a700 (LWP 211708)]
[1]     0x00002b73d74fc1d7 in raise () from /lib64/libc.so.6
[0]     0x00002b83eb9cc1d7 in raise () from /lib64/libc.so.6
[1]     Missing separate debuginfos, use: debuginfo-install libhfi1-0.5-23.el7.x86_64 libi40iw-0.5.227-2.el7.x86_64 libibverbs-41mlnx1-OFED.4.1.0.1.1.41102.x86_64 libmlx4-41mlnx1-OFED.4.1.0.1.0.41102.x86_64 libmlx5-41mlnx1-OFED.4.1.0.1.5.41102.x86_64 libnl-1.1.4-3.el7.x86_64 librdmacm-41mlnx1-OFED.4.1.0.1.0.41102.x86_64 librxe-41mlnx1-OFED.4.1.0.1.7.41102.x86_64
[0]     Missing separate debuginfos, use: debuginfo-install libhfi1-0.5-23.el7.x86_64 libi40iw-0.5.227-2.el7.x86_64 libibverbs-41mlnx1-OFED.4.1.0.1.1.41102.x86_64 libmlx4-41mlnx1-OFED.4.1.0.1.0.41102.x86_64 libmlx5-41mlnx1-OFED.4.1.0.1.5.41102.x86_64 libnl-1.1.4-3.el7.x86_64 librdmacm-41mlnx1-OFED.4.1.0.1.0.41102.x86_64 librxe-41mlnx1-OFED.4.1.0.1.7.41102.x86_64
[0,1] (mpigdb) bt
[0]     #0  0x00002b83eb9cc1d7 in raise () from /lib64/libc.so.6
[1]     #0  0x00002b73d74fc1d7 in raise () from /lib64/libc.so.6
[0]     #1  0x00002b83eb9cd8c8 in abort () from /lib64/libc.so.6
[1]     #1  0x00002b73d74fd8c8 in abort () from /lib64/libc.so.6
[0]     #2  0x00002b83ebfd2673 in fi_ibv_rdm_cm_progress_thread (dom=0xc35730)
[1]     #2  0x00002b73d7b02673 in fi_ibv_rdm_cm_progress_thread (dom=0xe9a730)
[0,1]       at prov/verbs/src/verbs_domain.c:219
[0]     #3  0x00002b83eb26adc5 in start_thread () from /lib64/libpthread.so.0
[1]     #3  0x00002b73d6d9adc5 in start_thread () from /lib64/libpthread.so.0
[0]     #4  0x00002b83eba8e73d in clone () from /lib64/libc.so.6
[1]     #4  0x00002b73d75be73d in clone () from /lib64/libc.so.6
```
The `alltoallw1` is the MPICH test. You may try it

**Comment by gladkovdmitry17** [comment]
Sorry, I need to go home. I'll take a look tomorrow and provide feedback.
Thanks for preparing this patch!

**Comment by fzago-cray** [comment]
I ran the same test under slurm, and the process only connect to each other, not to themselves which would set cm_role to FI_VERBS_CM_SELF.
So I can't reproduce.

Maybe you're hitting #3458.

**Comment by gladkovdmitry17** [comment]
@fzago-cray I've checked it again and I don't see any errors. Seems something was wrong with my environment. Sorry for misunderstanding. Please, proceed with these changes. It's OK for me

**Comment by gladkovdmitry17** [comment]
The packed address is used [here](https://github.com/ofiwg/libfabric/blob/f7cbf8d88408251be8a711b1348c5d782175d967/prov/verbs/src/ep_rdm/verbs_rdm_cm.c#L366). It adds to the Address Vector and we defines CM role using this address.
Sorry it was my bad, I confused you. Seems only addr is needed for us and the logic was right to pack it into connection's private data.
Thanks

**Comment by fzago-cray** [comment]
No problem. PR not needed then.

**Pull request closed without merging**
