### PR TITLE
Opx upstream 2024 07 17

### PR DESCRIPTION
**Pull request by charlesshereda**
Cornelis Networks upstream for July 2024.

Changes include:
-TID cache debug improvements;
-Detection of driver lack of support for TID;
-Multi-CTS support for TID;
-Removal of statement that TID is not supported;
-OPX Tracer improvements;
-Improvements to OPX shared memory cleanup;
-H to H performance improvements for build that supports HMEM;
-Bug fix for a threshold check;
-Bug fix for FI_SELECTIVE_COMPLETION;
-CN5000 fixes;
-Parameterization of various thresholds.

Added 7/19:
-Fix performance issue caused by not setting ACK bit in the single SDMA packet case;
-Fix assert.

### CODE REVIEW

**Comment by charlesshereda** [comment]
rerun ci

**Comment by charlesshereda** [comment]
I'm not sure why this failed the AWS CI but the PR that I opened against v1.22.x with the same commits passed it. Trying to rerun the AWS CI here.

**Comment by shijin-aws** [comment]
@charlesshereda I think it's a github jitter...

```
using GIT_ASKPASS to set credentials 

 > git fetch --no-tags --force --progress -- https://github.com/ofiwg/libfabric.git +refs/pull/10192/head:refs/remotes/origin/PR-10192 # timeout=10

ERROR: Error cloning remote repo 'origin'

hudson.plugins.git.GitException: Command "git fetch --no-tags --force --progress -- https://github.com/ofiwg/libfabric.git +refs/pull/10192/head:refs/remotes/origin/PR-10192" returned status code 128:

stdout: 

stderr: remote: Enumerating objects: 124436, done.        

remote: Counting objects:   0% (1/2053)        
remote: Counting objects:   1% (21/2053)        
remote: Counting objects:   2% (42/2053)        
remote: Counting objects:   3% (62/2053)        
remote: Counting objects:   4% (83/2053)        
remote: Counting objects:   5% (103/2053)        
remote: Counting objects:   6% (124/2053)        
remote: Counting objects:   7% (144/2053)        
remote: Counting objects:   8% (165/2053)        
remote: Counting objects:   9% (185/2053)        
remote: Counting objects:  10% (206/2053)        
remote: Counting objects:  11% (226/2053)        
remote: Counting objects:  12% (247/2053)        
remote: Counting objects:  13% (267/2053)        
remote: Counting objects:  14% (288/2053)        
remote: Counting objects:  15% (308/2053)        
remote: Counting objects:  16% (329/2053)        
remote: Counting objects:  17% (350/2053)        
remote: Counting objects:  18% (370/2053)        
remote: Counting objects:  19% (391/2053)        
remote: Counting objects:  20% (411/2053)        
remote: Counting objects:  21% (432/2053)        
remote: Counting objects:  22% (452/2053)        
remote: Counting objects:  23% (473/2053)        
remote: Counting objects:  24% (493/2053)        
remote: Counting objects:  25% (514/2053)        
remote: Counting objects:  26% (534/2053)        
remote: Counting objects:  27% (555/2053)        
remote: Counting o
```

**Comment by shijin-aws** [comment]
bot:aws:retest

**Comment by charlesshereda** [comment]
new commit incoming

**Comment by j-xiong** [comment]
@charlesshereda Could you provide me a summary of changes for this PR as well as #10090 (to be put in NEWS.md)? That would be better than me trying to summarize the 50+ commits.

**Comment by charlesshereda** [comment]
> @charlesshereda Could you provide me a summary of changes for this PR as well as #10090 (to be put in NEWS.md)? That would be better than me trying to summarize the 50+ commits.

@j-xiong Sure, do you want more detail than what I put in the change summary when I opened the PRs, or is that sufficient? And, do you want a PR against NEWS.md, or just an inline comment?

**Comment by j-xiong** [comment]
@charlesshereda Oh yes, the summary in the PR description would work for me. You are all set. Thanks!

**Comment by j-xiong** [comment]
BTW, do you want today's addition in 1.22.0, too?

**Review by j-xiong — APPROVED** [review]

**Pull request merged**
