### PR TITLE
sockets: Try find addr again when it is -1

### PR DESCRIPTION
**Pull request by hzhou**
When the first couple messages are received in a single poll, the last a few
messages' addr field may be set to FI_ADDR_NOTAVAIL since the
connection table has not been established yet -- the connection message is in
the same batch yet to be processed. Message with FI_ADDR_NOTAVAIL will
have trouble matching as it skips the checking of source, resulting in
message mismatch.

This patch trys to look up the addr_index again in the case of addr was
FI_ADDR_NOTAVAIL.

We found this issue when testing on FreeBSD. It must have something to do with how the kernel accumulates messages between the poll.

### CODE REVIEW

**Comment by hzhou** [comment]
CI failed. I guess I can't always call `sock_av_get_addr_index` on a `pe_entry`. Any suggestion?

**Comment by hzhou** [comment]
Second try. I'll clean up the commits once it passes the CI.

**Comment by hzhou** [comment]
Third try.

**Comment by shefty** [comment]
There are 5 commits here for a single line change, which I don't understand.

**Comment by hzhou** [comment]
> 
> 
> There are 5 commits here for a single line change, which I don't understand.

In the end we'll pick a single commit and delete the rest. But I would like some discussion as I am not sure which fix is the right approach.

The symptom is when first few messages from a single host arrive in a batch, current sockets code first creates `pe_entry` , resolving address if possible, then in a *separate* iteration tries to process the entries. Because during the first iteration the address cannot be resolved, it is left as `FI_ADDR_UNAVAIL`, resulting in message mismatching later.

The first fix, commit 1, simply tries to look up unresolved address again at message processing time. It works in our (MPICH) testing, but fails some of the CI. Is it because some of the tests don't use `index` so ` sock_av_get_addr_index` segfaults? Potentially some tweak can make this fix work?

Commit 2 simply reverts the previous commit. Both will disappear if squashed.

The second fix, commit 3, tries to move the message processing into the first iteration so it processes one message at a time. But apparently I am missing some complexity as the fix resulted in some deadlocks.

The last commit, which is finally cleared both CI tests and MPICH tests, simply forces getting one message at a time by overwriting the maximum count to 1. While works, this appears to be a hacky solution as it defeats the design choice, which I am not sure how critical it is.

Would you help me decide which of the 3 fixes seems preferable? If one of the first two is preferred, I'll spend more effort to make it work -- with the help of discussions.

**Comment by shefty** [comment]
It will take me some time to look into this problem in detail.  Of what you mentioned above, the first option seems like the right approach, but that's without knowing the implementation details.

**Comment by shefty** [comment]
I will open a PR that I'll open shortly that will try to address this.  It's aligned with the first patch in this set.

**Comment by shefty** [comment]
See if PR ##6217 fixes the issue for you.

**Pull request closed without merging**
