### PR TITLE
hmem/cuda: Fallback to CUDA calls when NVML call fails.

### PR DESCRIPTION
**Pull request by shijin-aws**
The NVML calls to verify nvidia devices are nice-to-have features that allow a cheaper check and earlier exit when cuda devices are not present. When NVML call fails, we shouldn't fail the whole cuda hmem init but should fall back to the normal cuda api calls.

It is observed that users may use an NVML libraries that only contain stub functions for build purpose.

### CODE REVIEW

**Review by j-xiong — APPROVED** [review]

**Review by wenduwan — APPROVED** [review]

**Comment by shijin-aws** [comment]
Need to investigate the AWS CI failure

**Comment by shijin-aws** [comment]
bot:aws:retest

**Comment by j-xiong** [comment]
@shijin-aws Any update for this?

**Comment by shijin-aws** [comment]
@j-xiong we are now inclined to close this PR as it will cause CUDA calls made on non-GPU platforms, which we aimed to avoid.

**Pull request closed without merging**
