### PR TITLE
add a few more fi_no_cq function prototypes

### PR DESCRIPTION
**Pull request by sayantansur**
Signed-off-by: Sayantan Sur <sayantan.sur@intel.com>

### CODE REVIEW

**Comment by shefty** [comment]
The reason these aren't defined is because they must be implemented if the user can create the CQ.

**Comment by sayantansur** [comment]
I thought these were missing from the enosys.h file since they are present in the enosys.c file.

But if that's no the intent, i'll close.

**Comment by shefty** [comment]
Hmm... we either need to merge your changes or remove them from enosys.c then.

**Comment by sayantansur** [comment]
Let me know what we should do here, and I'll update the PR either way.

**Comment by shefty** [comment]
Merging this as it's simply exposing calls that are already defined.  We can look at removing unnecessary calls later, or leave these for providers under development.  Thanks

**Pull request merged**
