### PR TITLE
Multi-user permission fix

### PR DESCRIPTION
**Pull request by zhngaj**

### CODE REVIEW

**Comment by rajachan** [comment]
Tagging Alexia and @shefty to review the shm commit.

**Comment by aingerson** [comment]
Oh, I read this as FI_NAME_MAX which is 64, not NAME_MAX which is 255. Why does it need to be this big?

**Comment by zhngaj** [comment]
We need to involve GID and QPN when setting the shared memory filename, 64 is not enough. 
Also feel it does not hurt to allow name_max to be more open for other uses.

**Comment by aingerson** [comment]
Ok, fair enough. It will increase the size of the shared memory region roughly 224 bytes per peer. Best to confirm all this with Sean.

**Comment by shefty** [comment]
The increase seems okay with me, since we have to bump it up over 64 anyway.  Going from 96 bytes to 255 adds about 12k on a 72-core system, but this isn't memory that we need to touch beyond startup.

**Comment by zhngaj** [comment]
Cool. Thanks for the confirmation.

**Comment by aingerson** [comment]
Intel CI is failing for real this time
fi_bw -e rdm -v -T 1 -p shm 
  [error] fabtests:common/shared.c:2382: cq_readerr (Provider errno: 5) : Unknown error -5

**Comment by zhngaj** [comment]
@aingerson I was not able to reproduce the same error.

I tried both master (e38ec41) and this PR #538, I got the a different error:
libfabric:10847:shm:av:smr_map_to_region():161<warn> shm_open error

Could you send me the the c/s command used in the failed fi_bw test?

**Comment by jswaro** [comment]
Ignore the Cray CI on this build.

**Comment by aingerson** [comment]
Server:
fi_bw -e rdm -v -T 1 -p "shm"  -s server_name
Client:
fi_bw -e rdm -v -T 1 -p "shm"  -s client_name server_name

Where server_name/client_name are endpoint names. Because the shm provider artificially creates endpoint names and the way fabtests works, both are needed.
Theoretically, they should be able to be anything (you could even use "server_name" and "client_name") but because of an rxm bug that I'm fixing right now, they need to at least by real node names.

**Comment by zhngaj** [comment]
@aingerson I have a patch to fix the fi_bw failure in Intel CI. Running fabtests with shm provider, I saw test `fi_rdm g00n13s -p "shm"` failed. Just want to double check if this is a known issue.
```
- name:   fi_rdm g00n13s -p "shm"
  result: Fail
  time:   120
  server_cmd: /home/ec2-user/ofiwg-libfabric/fabtests/fabtests.install/bin/fi_rdm g00n13s -p "shm"
  server_stdout: |
    Killed by signal 15.
```

**Comment by rajachan** [comment]
@zhngaj check out https://github.com/ofiwg/libfabric/issues/5182 for context on the fi_rdm shm failure.

**Comment by zhngaj** [comment]
Thanks for the context, @rajachan. The timeout is expected and we can ignore it then.

**Comment by zhngaj** [comment]
@aingerson Could you please review the changes to fix the fi_bw failure.
e7371e6349962435b92ff7c8f40c5254cf50cd62
6aabbab3e772445744c0f4467e0b08c32d8eaec5

**Comment by aingerson** [comment]
Changes look good. Thanks for debugging!

**Pull request merged**
