### PR TITLE
[v1.20.x] util/memhooks: Fix a bug when calculating mprotect region

### PR DESCRIPTION
**Pull request by shijin-aws**
backport https://github.com/ofiwg/libfabric/pull/9552

### CODE REVIEW

**Comment by j-xiong** [comment]
@shijin-aws Any insight into the AWS CI failing?

**Comment by shijin-aws** [comment]
bot:aws:retest

**Comment by shijin-aws** [comment]
@j-xiong it's a bug in the infrastructure, restarted the test after fixing it.

**Comment by shijin-aws** [comment]
CI passed, ready for merge

**Review by j-xiong — APPROVED** [review]

**Pull request merged**
