### PR TITLE
De-allocate fi_info structures if any provider has an error.

### PR DESCRIPTION
**Pull request by pmmccorm**
Moved fi_freeinfo_ to before getinfo to avoid forward declaration

Signed-off-by: pmmccorm <patrick.m.mccormick@intel.com>

### CODE REVIEW

**Comment by jsquyres** [comment]
Hmm.  Wasn't this approach tried before, and shown to be problematic?

E.g., the verbs provider will see usnic devices and think, "ah ha! I have some verbs devices!" But then the usnic devices will fail to pass muster with RDMACM, return a failure, and then the (valid) usnic devices never get returned from fi_getinfo().

**Comment by pmmccorm** [comment]
This patch just frees the provider-malloc'd fi_info structures on any provider error, it should not affect anything else.

**Comment by jsquyres** [comment]
You're returning out of the loop early.

This could effect the scenario I mentioned above -- verbs provider runs first, fails, and then the usnic provider is never queried.

**Comment by pmmccorm** [comment]
I see now, yeah that is not good. It works now because of the ordering that the providers were initialized (subtle and fragile).

getinfo can do 1 of three things:

1)
continue iterating on any provider error and return whatever was successful (silently ignoring providers that returned errors?)

2)
Old behavior: stop iterating through providers on first error, return partial list and successful.

3)
Return nothing on any provider error (proposed patch).

@shefty , @jsquyres  what do you think is best?

**Comment by jsquyres** [comment]
On Jan 9, 2015, at 4:22 PM, Patrick McCormick <notifications@github.com> wrote:

> getinfo can do 1 of three things:
> 
> 1)
> continue iterating on any provider error and return whatever was successful (silently ignoring providers that returned errors?)
> 
> 2)
> Old behavior: stop iterating through providers on first error, return partial list and successful.
> 
> 3)
> Return nothing on any provider error (proposed patch).

3 is no good; it can hose usnic.

This came up before (there might even still be an issue open on it...?).  One workaround was to have the verbs provider skip usnic devices.  But verbs is using rdmacm, and it's not easy to tell offhand that a device is usnic before it fails.

Perhaps another option might be:

4) continue iterating; return successful data and also return a list of providers that failed

Then the app can decide what to do / if it cares about the failed providers.

That being said, I think we still would like the verbs provider to always skip usnic devices.  That is: we never want usnic devices to be returned through the verbs provider.  Also, usnic devices will never support RDMACM.

That being said, I think there might be an open action item for us (Cisco) to figure out exactly what is failing in RDMACM's polling of the usnic device...?

-- 
Jeff Squyres
jsquyres@cisco.com
For corporate legal information go to: http://www.cisco.com/web/about/doing_business/legal/cri/

**Comment by shefty** [comment]
This is my opinion.  I don't want to hide unexpected errors from the application.  I would rather fail fi_getinfo if ANY provider returns anything other than success or ENODATA.  Otherwise, the app will get something (like the socket provider), attempt to use it, the performance will suck, the end-users will end up trying to debug the issue, but never see the error, we'll get pinged endlessly on the mailing list about libfabric not working and how it sucks.

In practice, it's unlikely that a single node will ever have more than one provider's hardware installed.  But the sockets provider should always be there and work.  If we hit an unexpected error, there's a good chance that the provider hardware that the app actually wants to use is not working properly.

**Comment by shefty** [comment]
In short, I like this patch.  :)

**Comment by jsquyres** [comment]
It's actually not uncommon to have more than one type of NIC installed for competitive analysis.

I do not like this patch because there is no way for the app (or end user) to a) know what provider failed, and b) be able to work around the failed provider if it wants to.

**Comment by shefty** [comment]
Hopefully the provider prints some useful message regarding the failure.

An app can use the fi_info hints to specify a provider directly.  There is no run time facility for disabling built-in providers.  That is something that we could look at adding.

**Comment by goodell** [comment]
Sean, do you really want libfabric to be emitting stdout/stderr messages?  I always thought of libfabric as being low enough level (like the sockets API) that such output would be undesirable.

**Comment by shefty** [comment]
Ideally?  No.  This change is in reference to a situation that "should" never happen.  Or we need to rethink how to report errors from fi_getinfo and expect that these errors will actually occur somewhat frequently.  If you look at libibverbs, it actually does direct messages to stderr.

The structure of the current code results in somewhat undetermined behavior.  If provider 1 fails, the call fails and nothing happens.  Provider 2 is skipped.  If provider 2 fails, provider 1's data is returned, along with a call failure.  The app will detect the failure, but must know to free the data returned by provider 1.

So a provider will only be called if all earlier providers succeed.  The first failure results in subsequent providers from being skipped.  This patch is an improvement over the current code, in that it at least makes the behavior consistent and cleans up after a failure.

I don't want to mask real errors from the app.  And error reporting becomes more complex when looking at 3 providers, where multiple providers may fail.

**Comment by jsquyres** [comment]
Found it: #229 is the still-open issue where we need to investigate what exactly is going wrong with RDMACM+usnic.

**Comment by pmmccorm** [comment]
Thanks for finding that Jeff. We can just not return error in verbs provider (in addition to this PR):

diff --git a/prov/verbs/src/fi_verbs.c b/prov/verbs/src/fi_verbs.c
index d5c2d47..40bd80a 100644
--- a/prov/verbs/src/fi_verbs.c
+++ b/prov/verbs/src/fi_verbs.c
@@ -629,7 +629,8 @@ fi_ibv_getepinfo(const char *node, const char *service,

        ret = rdma_create_ep(id, rai, NULL, NULL);
        if (ret) {
-               ret = -errno;
+               /* ignore errno, treat this as no device */
+               ret = -FI_ENODATA;
                goto err2;
        }

I think this is more sane than always returning provider error and masking providers from getinfo (current case).

**Comment by jsquyres** [comment]
@pmmccorm Sidenote: If you past a patch in a github comment, surround it by triple-single-backticks for verbatim mode.  For extra bonus points, put "patch" after the first one for nice context highlighting (I took the liberty of editing your comment to add that in so that it makes it much easier to read).  Thanks!

**Comment by shefty** [comment]
Are we sure that this change won't mask a real error?

**Comment by rfaucett** [comment]
Not 100% sure, but if it does then I would call that a bug in the verbs provider and that said error needs to be detected in some other way that does not confuse "RDMA not supported" with "internal error opening RDMA endpoint."

**Comment by pmmccorm** [comment]
It is wrong (but unavoidable) for the verbs provider to create an ep on just an existence query, I think this change papers over that.

I think it is a better solution than having the verbs provider skip usnic devices.

**Comment by pmmccorm** [comment]
The patch I proposed above is too simple and will break other places as Sean thought. I reworked the same idea and improved verbs-providers handling of fi_getinfo in #495

**Comment by shefty** [comment]
While we continue to debate how to handle errors from fi_getinfo, I'm going to merge this patch as an improvement over the existing code.  It cleans up after errors.

**Pull request merged**
