### PR TITLE
[WIP] Fix typo in license notice

### PR DESCRIPTION
**Pull request by pombredanne**
Signed-off-by: Philippe Ombredanne <pombredanne@nexb.com>

### CODE REVIEW

**Comment by pombredanne** [comment]
FWIW, my pombredanne@nexb.com email is also on file with GH. So your DCO bot should be able to accept this too. If this is an an issue, I can amend with pombredanne@gmail.com

**Comment by pombredanne** [comment]
And for context, this is based on a review of licensing I am doing for this library as well ass rdma-core and the corresponding code in the kernel following this discussion thread https://www.spinics.net/lists/linux-rdma/index.html#61713  started by @jgunthorpe

**Comment by pombredanne** [comment]
Note that if you prefer a patch on list instead, I can do this too!

**Comment by jsquyres** [comment]
@pombredanne I believe our DCO checker just checks to ensure that the committer email address is the same as the signed off address.  So you can use whatever address you want -- just please make the 2 addresses match.

Thanks!

**Comment by pombredanne** [comment]
I will resubmit anyway: these files also have the same typo:
util/info.c
util/pingpong.c
util/strerror.c
util/windows/getopt/getopt.cpp

**Comment by pombredanne** [comment]
re
> I believe our DCO checker just checks to ensure that the committer email address is the same as the signed off address

It does alright but only check against the primary GH address, not any other one on file.

**Comment by jgunthorpe** [comment]
Thanks Philippe!

**Comment by pombredanne** [comment]
Closing in favor of #3934

**Pull request closed without merging**
