### PR TITLE
common/util: Fix mismatch of reference counter in NS functionality

### PR DESCRIPTION
**Pull request by gladkovdmitry17**
Fix for issue #3236
The implemented reference counting for NS functionality in the commit [bd7db0a](https://github.com/ofiwg/libfabric/commit/bd7db0a5ad37c1070e7fb479c175591e9f5086f7) breaks NS functionality (start of NS thread).

### CODE REVIEW

**Comment by gladkovdmitry17** [comment]
@aingerson Can I ask you to check fabtests with the changes from the PR? psm/psm2 providers should be healthy with these changes in fabtests. Thank you so much!

**Comment by aingerson** [comment]
Manually tested psm/psm2 and it's back to normal. Thanks so much!

**Comment by gladkovdmitry17** [comment]
@aingerson Sorry for my bad for the commit [bd7db0a](https://github.com/ofiwg/libfabric/commit/bd7db0a5ad37c1070e7fb479c175591e9f5086f7). Thank you!

**Comment by shefty** [comment]
thanks for the quick response

**Pull request merged**
