### PR TITLE
Pr/sockets

### LINKED ISSUE #966: sockets provider: Issues with fi_setname()
There are at least two issues with the `fi_setname()` implementation in the sockets provider:

1. If I pass an address containing a port number of 0, I should get assigned an ephemeral port number and receive the ephemeral port number back if I immediately call `fi_getname()`.
2. There is a crash in the sockets provider in a simple test I was writing to try to track down the cause of the previous issue.  It's on the `setname-test` branch of my fabtests fork.  The server crashes when a client connects and these are the last log messages printed out:

```
libfabric:core:core:fi_register_provider():121<info> registering provider: sockets (1.0)
libfabric:sockets:fabric:sock_ep_getinfo():463<info> src_addr: 10.1.0.32
libfabric:sockets:fabric:sock_ep_getinfo():465<info> dest_addr: 172.16.10.90
libfabric:sockets:ep_ctrl:sock_pep_create_listener_thread():1110<info> Listener thread bound to 10.1.0.32:9228
libfabric:sockets:ep_ctrl:sock_pep_listener_thread():941<info> Starting listener thread for PEP: 0x19b4950
libfabric:sockets:ep_ctrl:sock_pep_listener_thread():991<info> Total received: 544
libfabric:sockets:ep_ctrl:sock_pep_listener_thread():996<info> CM msg received: 544
libfabric:sockets:ep_ctrl:sock_ep_cm_send_ack():439<info> Total Sent: 16
libfabric:sockets:ep_ctrl:sock_pep_listener_thread():1009<info> Received SOCK_CONN_REQ
libfabric:sockets:fabric:sock_verify_info():264<info> no matching fabric
libfabric:sockets:ep_ctrl:sock_ep_msg_process_info():919<info> incoming conn_req not supported
```

@jithinjosepkl

### PR DESCRIPTION
**Pull request by jithinjosepkl**
Fixes #966

### CODE REVIEW

**Comment by shefty** [comment]
@patrickmacarthur -- Patrick, can you test that this change works for you?  I'd like to get this into the 1.0 release, so if you could verify this by the end of the week, that would be ideal.  The earlier the better, obviously, so we can respond to any problems.

**Comment by patrickmacarthur** [comment]
@shefty Yes I hope to get to this by the end of today

**Comment by patrickmacarthur** [comment]
I now get an ephemeral port number assigned after fi_setname().  However, the assigned port number changes after fi_connect() completes.

Additionally, after fi_accept() is called on a new endpoint, fi_getname() returns a different port number than the port number on which the connection was accepted.  Maybe this is just a quirk of the way the sockets provider is implemented.

**Comment by goodell** [comment]
Related but somewhat OT: I'm currently trying to implement `fi_setname` in the usnic provider.  Is it valid for an application to call `fi_setname` twice on the same PEP?  I assume not, since we don't have a good use case for this.  Basically, I need to bind(2) the underlying socket at `fi_setname`-time in order to get the kernel to allocate an ephemeral port for me.  But a subsequent call to `fi_setname` would require me to tear down the whole socket and rebuild it from scratch, which will lead to some fairly clunky code...

**Comment by shefty** [comment]
My thinking on this is... support is provider specific and not guaranteed.

**Comment by patrickmacarthur** [comment]
@goodell I don't know of any good use case for calling `fi_setname()` twice.  At the very least, UNH EXS will never call `fi_setname()` more than once on an endpoint/PEP (except in the case of a bug).

**Comment by jithinjosepkl** [comment]
@patrickmacarthur - In sockets provider, bind is called in fi_setname (inside sock_conn_listen for EP, and inside sock_pep_create_listener. So, I wonder why the port number should change after connect, since there is a check.  Is this a new test in your branch?

@shefty - Just to be clear, we are not expecting the EPs to have the same portnumber, which was set for PEP, am i right?

**Comment by patrickmacarthur** [comment]
@jithinjosepkl The port number change actually happens before `fi_connect()`; the client-side endpoint is not inheriting the port number from the passive endpoint given in `info->handle`.

I updated my `setname-test` fabtests branch to print a message if the sockaddr changes unexpectedly.  Note that it's not perfect and might fail in a couple of scenarios where it should pass (e.g., if the client binds to a wildcard address), but it does demonstrate the issue.

**Comment by jithinjosepkl** [comment]
Thanks @patrickmacarthur. Sean and I had a brief discussion too.
Yeah, currently the active side endpoint do not inherit the endpoint address from PEP.
I will handle this case.

Btw, do you expect this for the passive side endpoint too?

**Comment by patrickmacarthur** [comment]
The active (client) side EP properly inheriting the ephemeral port number is the case that really matters for EXS.

Right now, my EXS test case fails because the server side endpoint doesn't inherit the same port number.  However, I can handle the server-side case in EXS itself if need be.

**Comment by jithinjosepkl** [comment]
I have updated the PR so that active side EPs inherit src_address from PEP.
Test also runs fine.

@shefty, @patrickmacarthur  - Please review.

With this PR, the ud_pingpong test fails.
Unlike other RDM/DGRAM tests, this test uses info->src_addr after fi_getinfo().
Client sends info->src_address to server and server inserts this into AV.
But, the port might not have been assigned at fi_getinfo call.
Looks like this test needs to be fixed (either use fi_getname, or set hints->src_addr properly in fi_getinfo).

**Comment by patrickmacarthur** [comment]
This fixes the issue in my `fi_msg_setname` program but not in my EXS test case.  I'll have to look into the EXS test case later today.

**Comment by shefty** [comment]
I opened a PR to fix ud_pingpong to call fi_getname instead of using the return value from fi_getinfo.

**Comment by patrickmacarthur** [comment]
Looking at the EXS test case again, I was mistaken and it did pass for the client side.  So this PR is good to merge as far as I am concerned.

**Pull request merged**
