### PR TITLE
news: updated for psm3 provider

### PR DESCRIPTION
**Pull request by acgoldma**
Signed-off-by: Adam Goldman <adam.goldman@intel.com>
(cherry picked from commit be8d2aa6e386269b0c6eb174a8da7954223868fc)

### CODE REVIEW

**Comment by acgoldma** [comment]
@shefty , I noticed that the generated man pages may be out of sync on the branch.
It appears that the md file change for psm3 is in the branch, but the nroff-generated commit (dddee18c308b512bb79fd7d9eee90a847de92a91) is not

**Comment by shefty** [comment]
Hmm... something is off with the man pages.

**Review by j-xiong — APPROVED** [review]

**Comment by shefty** [comment]
Gimli was right, we never should have trusted an elf.

**Comment by shefty** [comment]
gh-man.yaml only looks at main branch.  That needs updating

**Comment by j-xiong** [comment]
Read some documents. It appears the github only runs `cron` scheduled action on the default branch (main).

**Comment by shefty** [comment]
Opening an issue for this.

**Pull request merged**
