### PR TITLE
Opx upstream September

### PR DESCRIPTION
**Pull request by timothom64**

### CODE REVIEW

**Comment by timothom64** [comment]
Please add the [for-v1.16.x](https://github.com/ofiwg/libfabric/labels/for-v1.16.x) label

**Comment by shefty** [comment]
Please open against v1.16.x to merge prior to rc3.  Thanks!

**Comment by timothom64** [comment]
> Please open against v1.16.x to merge prior to rc3. Thanks!

Oh, I'm fine with this commit going into main and rc3 and not being patched into the previous RCs, which I think is what will happen if we just proceed as is.  

There's no need to port this to other branches/older RCs.

**Comment by shefty** [comment]
I already created the v1.16.x branch.  So, if you want the changes in the v1.16.0 release, it needs to be picked into that branch.

**Pull request merged**
