### PR TITLE
[v1.9.x] prov/efa: fix efa mem leaks

### PR DESCRIPTION
**Pull request by wzamazon**
This PR fix memory leaks in EFA provider v1.9.x

### CODE REVIEW

**Comment by wzamazon** [comment]
bot:aws:retest

**Comment by rajachan** [comment]
bot:lanl:retest

**Comment by wzamazon** [comment]
The AWS CI failure is because CI did not turn off ptrace protection on Ubuntu system, which is necessary for shm provider in v1.9.x. A change has been made to the CI system to address the issue.

**Comment by wzamazon** [comment]
bot:aws:retest

**Comment by wzamazon** [comment]
bot:aws:retest

**Comment by wzamazon** [comment]
The nccl-multi-node failure is an instance issue.

**Pull request merged**
