### PR TITLE
[v1.15.x] cherry-picked fixes from main

### PR DESCRIPTION
**Pull request by shefty**

### CODE REVIEW

**Comment by raffenet** [comment]
@shefty can you also pickup e40039839fe88a432f1e42ec7c3d7628a0439bdf?

**Comment by shefty** [comment]
@raffenet - I'll add in the opx changes.  Picking just that change hit a conflict, so some other updates are needed.  @timothom64 - Can you please either pick opx changes for v1.15.x from main or point me to the commits to pick up, specifically to pull in the build fixes?

**Comment by shefty** [comment]
I think I picked up the changes from https://github.com/ofiwg/libfabric/commit/e40039839fe88a432f1e42ec7c3d7628a0439bdf and resolve the conflicts correctly.

**Comment by shefty** [comment]
Intel CI failures:
```
fi_rdm_multi_client -C 10 -I 5 -p "verbs;ofi_rxd"
fi_rdm_multi_client -C 10 -I 5 -U -p "verbs;ofi_rxd"
```
Re-run twice, with same failures both times.  Need to check manually.  All changes are cherry picked from master and aren't obviously related to verbs rxd.

**Comment by shefty** [comment]
The fi_rdm_multi_client test hangs when run manually.  But it also hangs running with main.  udp/rxd does work.  This could be an issue with the verbs drivers on the CI systems.  We've hit into a problem with it reporting an incorrect qpn before.

**Pull request merged**
