### PR TITLE
ci/travis: Enable tcp provider in CI testing

### PR DESCRIPTION
**Pull request by dmitrygladkov**
Signed-off-by: Dmitry Gladkov <dmitry.gladkov@intel.com>

### CODE REVIEW

**Comment by dmitrygladkov** [comment]
There are failures over `tcp;ofi_rxm` on OSX:
```
- name:   fi_cq_data -e rdm -p "tcp;ofi_rxm"
  result: Fail
  time:   2
  server_cmd: fi_cq_data -e rdm -p "tcp;ofi_rxm" -s 127.0.0.1
  server_stdout: |
    fi_ep_bind(): common/shared.c:932, ret=-78 (Function not implemented)
    ./scripts/runfabtests.sh: line 366: 45643 Segmentation fault: 11  fi_cq_data -e rdm -p "tcp;ofi_rxm" -s 127.0.0.1
  client_cmd: fi_cq_data -e rdm -p "tcp;ofi_rxm" -s 127.0.0.1 127.0.0.1
  client_stdout: |
    fi_ep_bind(): common/shared.c:932, ret=-78 (Function not implemented)
    ./scripts/runfabtests.sh: line 371: 45646 Segmentation fault: 11  fi_cq_data -e rdm -p "tcp;ofi_rxm" -s 127.0.0.1 127.0.0.1

- name:   fi_rdm_tagged_peek -p "tcp;ofi_rxm"
  result: Fail
  time:   1
  server_cmd: fi_rdm_tagged_peek -p "tcp;ofi_rxm" -s 127.0.0.1
  server_stdout: |
    fi_ep_bind(): common/shared.c:932, ret=-78 (Function not implemented)
    ./scripts/runfabtests.sh: line 366: 45854 Segmentation fault: 11  fi_rdm_tagged_peek -p "tcp;ofi_rxm" -s 127.0.0.1
  client_cmd: fi_rdm_tagged_peek -p "tcp;ofi_rxm" -s 127.0.0.1 127.0.0.1
  client_stdout: |
    fi_ep_bind(): common/shared.c:932, ret=-78 (Function not implemented)
    ./scripts/runfabtests.sh: line 371: 45856 Segmentation fault: 11  fi_rdm_tagged_peek -p "tcp;ofi_rxm" -s 127.0.0.1 127.0.0.1

- name:   fi_unexpected_msg -e rdm -S -i 10 -p "tcp;ofi_rxm"
  result: Fail
  time:   1
  server_cmd: fi_unexpected_msg -e rdm -S -i 10 -p "tcp;ofi_rxm" -s 127.0.0.1
  server_stdout: |
    fi_ep_bind(): common/shared.c:932, ret=-78 (Function not implemented)
    ./scripts/runfabtests.sh: line 366: 45945 Segmentation fault: 11  fi_unexpected_msg -e rdm -S -i 10 -p "tcp;ofi_rxm" -s 127.0.0.1
  client_cmd: fi_unexpected_msg -e rdm -S -i 10 -p "tcp;ofi_rxm" -s 127.0.0.1 127.0.0.1
  client_stdout: |
    fi_ep_bind(): common/shared.c:932, ret=-78 (Function not implemented)
    ./scripts/runfabtests.sh: line 371: 45947 Segmentation fault: 11  fi_unexpected_msg -e rdm -S -i 10 -p "tcp;ofi_rxm" -s 127.0.0.1 127.0.0.1


- name:   fi_rdm_cntr_pingpong -I 5 -p "tcp;ofi_rxm"
  result: Fail
  time:   1
  server_cmd: fi_rdm_cntr_pingpong -I 5 -p "tcp;ofi_rxm" -s 127.0.0.1
  server_stdout: |
    fi_ep_bind(): common/shared.c:932, ret=-78 (Function not implemented)
    ./scripts/runfabtests.sh: line 366: 46125 Segmentation fault: 11  fi_rdm_cntr_pingpong -I 5 -p "tcp;ofi_rxm" -s 127.0.0.1
  client_cmd: fi_rdm_cntr_pingpong -I 5 -p "tcp;ofi_rxm" -s 127.0.0.1 127.0.0.1
  client_stdout: |
    fi_ep_bind(): common/shared.c:932, ret=-78 (Function not implemented)
    ./scripts/runfabtests.sh: line 371: 46127 Segmentation fault: 11  fi_rdm_cntr_pingpong -I 5 -p "tcp;ofi_rxm" -s 127.0.0.1 127.0.0.1
```

It seems that this is related to lack of `epoll` on OSX.

So, while it is not fixed, enable CI testing for Linux only

**Comment by dmitrygladkov** [comment]
@shefty @vkrishna What about to use `kqueue` on OSX?

**Comment by dmitrygladkov** [comment]
This is more correct way to enable `tcp;ofi_rxm` in CI testing - https://github.com/ofiwg/fabtests/pull/832
Could you check that PR, please?
This PR can be closed.

**Comment by shefty** [comment]
I don't think OS X is important enough as a target platform that we care about implementing kqueue support.  I don't oppose it, I just don't think it's worth the time to pursue.

**Pull request closed without merging**
