### PR TITLE
[v1.7.x] prov/verbs, rxm: fix for FI_RX_CQ_DATA and default buffered min

### PR DESCRIPTION
**Pull request by a-ilango**
- prov/verbs: fix FI_RX_CQ_DATA not being set in info->mode on return from fi_getinfo
- prov/rxm: fix setting default buffered min limit

### CODE REVIEW

**Comment by shefty** [comment]
@a-ilango - Intel CI doesn't handle branches, correct?  Or do I need to look into the failure?

**Comment by a-ilango** [comment]
It does handle branches for pull requests. It seems there are some test failures. Let me check.

**Comment by a-ilango** [comment]
I see a segfault in OMPI osu_alltoall test over RxM/tcp but I can't reproduce it when I ran the same binary manually a few times. Let me restart the CI by updating the PR to see if it shows up again.

**Comment by a-ilango** [comment]
So there were some hanging processes on test nodes which were probably interfering.

**Pull request merged**
