### PR TITLE
Remove unimplemented features

### PR DESCRIPTION
**Pull request by j-xiong**
This is the second batch of commits from #9384. They either remove features that have never been implemented or remove definitions for internal use only from the public headers.  Technically these changes break API compatibility. However, since the removed items could have never been used by applications, these changes have no practical impact on the API.

### CODE REVIEW

**Comment by j-xiong** [comment]
@ofiwg/intel-middleware

**Comment by j-xiong** [comment]
bot:aws:retest

**Comment by j-xiong** [comment]
bot:aws:retest

**Comment by shijin-aws** [comment]
@j-xiong this test break the backward compatibility test in AWS CI... which involves building a fabtests in libfabric v1.10.x branch with the tested libfabric on one node, and libfabric 1.10 on the other node, and run some ping-pong ...

The error happens when building fabtests 1.10 with the libfabric in this PR:

```
2024-03-02 20:02:02,315 - INFO - utils - Executing command: ./configure --prefix=/home/ec2-user/PortaFiducia/libraries/libfabric/bct/install/fabtests --with-libfabric=/home/ec2-user/PortaFiducia/build/libraries/libfabric/pr9852/install/libfabric --with-cuda=/usr/local/cuda
2024-03-02 20:02:03,848 - INFO - utils - Executing command: make -j
2024-03-02 20:02:05,120 - ERROR - utils - Command make -j failed with error:
unit/getinfo_test.c: In function ‘check_no_extra_caps’:
unit/getinfo_test.c:211:24: error: ‘FI_VARIABLE_MSG’ undeclared (first use in this function)
     FI_DIRECTED_RECV | FI_VARIABLE_MSG | \
                        ^
unit/getinfo_test.c:214:41: note: in expansion of macro ‘PRIMARY_RX_CAPS’
 #define PRIMARY_CAPS (PRIMARY_TX_CAPS | PRIMARY_RX_CAPS)
                                         ^~~~~~~~~~~~~~~
unit/getinfo_test.c:237:12: note: in expansion of macro ‘PRIMARY_CAPS’
     caps & PRIMARY_CAPS, info->caps & ~OPT_CAPS);
            ^~~~~~~~~~~~
unit/getinfo_test.c:211:24: note: each undeclared identifier is reported only once for each function it appears in
     FI_DIRECTED_RECV | FI_VARIABLE_MSG | \
                        ^
unit/getinfo_test.c:214:41: note: in expansion of macro ‘PRIMARY_RX_CAPS’
 #define PRIMARY_CAPS (PRIMARY_TX_CAPS | PRIMARY_RX_CAPS)
                                         ^~~~~~~~~~~~~~~
unit/getinfo_test.c:237:12: note: in expansion of macro ‘PRIMARY_CAPS’
     caps & PRIMARY_CAPS, info->caps & ~OPT_CAPS);
            ^~~~~~~~~~~~
unit/getinfo_test.c: In function ‘check_caps’:
unit/getinfo_test.c:211:24: error: ‘FI_VARIABLE_MSG’ undeclared (first use in this function)
     FI_DIRECTED_RECV | FI_VARIABLE_MSG | \
                        ^
unit/getinfo_test.c:214:41: note: in expansion of macro ‘PRIMARY_RX_CAPS’
 #define PRIMARY_CAPS (PRIMARY_TX_CAPS | PRIMARY_RX_CAPS)
                                         ^~~~~~~~~~~~~~~
unit/getinfo_test.c:278:12: note: in expansion of macro ‘PRIMARY_CAPS’
     caps & PRIMARY_CAPS, info->caps & ~OPT_CAPS);
            ^~~~~~~~~~~~
unit/getinfo_test.c: In function ‘validate_primary_caps’:
unit/getinfo_test.c:211:24: error: ‘FI_VARIABLE_MSG’ undeclared (first use in this function)
     FI_DIRECTED_RECV | FI_VARIABLE_MSG | \
                        ^
unit/getinfo_test.c:301:26: note: in expansion of macro ‘PRIMARY_RX_CAPS’
        PRIMARY_TX_CAPS | PRIMARY_RX_CAPS,
                          ^~~~~~~~~~~~~~~
unit/getinfo_test.c:303:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
make[1]: *** [unit/getinfo_test.o] Error 1
make[1]: *** Waiting for unfinished jobs....
unit/eq_test.c: In function ‘main’:
unit/eq_test.c:613:19: error: ‘FI_NOTIFY_FLAGS_ONLY’ undeclared (first use in this function)
   FI_RX_CQ_DATA | FI_NOTIFY_FLAGS_ONLY | FI_RESTRICTED_COMP |
                   ^~~~~~~~~~~~~~~~~~~~
unit/eq_test.c:613:19: note: each undeclared identifier is reported only once for each function it appears in
unit/eq_test.c:613:42: error: ‘FI_RESTRICTED_COMP’ undeclared (first use in this function); did you mean ‘FI_REMOTE_COMM’?
   FI_RX_CQ_DATA | FI_NOTIFY_FLAGS_ONLY | FI_RESTRICTED_COMP |
                                          ^~~~~~~~~~~~~~~~~~
                                          FI_REMOTE_COMM
make[1]: *** [unit/eq_test.o] Error 1
functional/stream_msg.c: In function ‘set_stream_hints’:
functional/stream_msg.c:210:26: error: ‘FI_EP_SOCK_STREAM’ undeclared (first use in this function); did you mean ‘FI_PROTO_RSTREAM’?
  hints->ep_attr->type  = FI_EP_SOCK_STREAM;
                          ^~~~~~~~~~~~~~~~~
                          FI_PROTO_RSTREAM
functional/stream_msg.c:210:26: note: each undeclared identifier is reported only once for each function it appears in
make[1]: *** [functional/stream_msg.o] Error 1
make: *** [all] Error 2

and output:
make  all-am
make[1]: Entering directory `/home/ec2-user/PortaFiducia/libraries/libfabric/bct/source/libfabric/fabtests'
```

**Comment by shijin-aws** [comment]
I think it's an CI issue ... we need to build 1.10 fabtests + libfabric 1.10 on one node and tested fabtests + tested libfabric on the other node.... A caveat of this method could be different versions of fabtests may have different behavior...but I didn't see it happens for the basic testing functionalities... 

we currently tests the following

```
"sendrecv": "fi_rdm_tagged_bw -S all -p efa -E",
        "read": "fi_rma_bw -o read -S all -p efa -E",
        "write": "fi_rma_bw -o write -S all -p efa -E",
        "atomic": "fi_rdm_atomic -p efa -E",
```

which should be identical across fabtests versions


I will fix it on monday

**Review by shefty — APPROVED** [review]

**Comment by shefty** [comment]
If you want to avoid breaking the build with older fabtests that use the definitions, I think you could redefine the values to 0, but keep them in the header file.  They could then be removed completely with the 2.0 jump.

**Comment by shijin-aws** [comment]
I don't have strong opinion on this. IIUC these symbols are not used beyond fabtests (which are not real applications). We have to break this build compability anyway for ofi 2.0, so fixing this in AWS CI early is not bad. I will retrigger the CI when it's ready

**Comment by shijin-aws** [comment]
@j-xiong I tried to modify our test to ping-pong between fabtests 1.10 + libfabric 1.10 and fabtests pr9852 + libfabric pr9852. I got a hang and the backtrace shows it was stuck at the OOB addr exchange... Need to dig it further but maybe I shouldn't let two sides use different fabtests versions.

**Comment by j-xiong** [comment]
The OOB settings may have changed between the two versions. I added a commit to define dummy values. Let's see if that can get the CI to pass.

**Review by shijin-aws — APPROVED** [review]

**Comment by shijin-aws** [comment]
@j-xiong is it ready for merge?

**Pull request merged**
