### PR TITLE
prov/verbs: Fix AV functionality in verbs/DGRAM

### LINKED ISSUE #3967: prov/verbs: subsequent fi_av_insert creates a new address that is not supposed to be created
The following plot works for 'udp' (and other providers) but not for 'verbs':

1. Start server, get address with fi_getname()
2. Start client, pass the server address to.
3. Client calls fi_av_insert() first time with server address, gets server's fi_addr
4. Client gets his address with fi_getname() and sends it to fi_addr, while server receives it from FI_ADDR_UNSPEC
5. Server calls (once) fi_av_insert() on the two addresses.
6. Client removes fi_addr and calls fi_av_insert() the second time on the two addresses, gets new fi_addr.
7. Now fi_addr in the new table appears to broken and the server can't be communicated no more by this address.

### PR DESCRIPTION
**Pull request by gladkovdmitry17**
Fixes #3967

Signed-off-by: Dmitry Gladkov <dmitry.gladkov@intel.com>

### CODE REVIEW

**Comment by shefty** [comment]
See Travis CI build failures.

**Comment by gladkovdmitry17** [comment]
> See Travis CI build failures.

Linux/clang complains about usage of `abs()` for unsigned value. Removed `abs()`.

OSX/gcc fails due to unsuccessful fi_poll -t counter for sockets proider.r

**Comment by gladkovdmitry17** [comment]
> Is the rbtree not needed anymore?

Yes, rbtree was used as a hash and there is no need to use this anymore. I offloaded storing `addr-slot` combination into AV functionality by setting `OFI_AV_HASH`.

**Comment by gladkovdmitry17** [comment]
CI testing is successful. So, merging this PR

**Pull request merged**
