### PR TITLE
fabtests: Replace jsmn with latest version

### PR DESCRIPTION
**Pull request by jlbyrne-hpe**
Existing version caused memory corruption; updated with:
https://github.com/zserge/jsmn.git commit 053d3cd29

Signed-off-by: John Byrne <john.l.byrne@hpe.com>

### CODE REVIEW

**Comment by rajachan** [comment]
Is it possible to pull in a released version of the header with the necessary bugfix instead of a git ref?

**Comment by jlbyrne-hpe** [comment]
Good point. The project isn't terribly active and I just grabbed top-op-tree. (April 2, 2020), but since v1.1.0 (April 19, 2019) there are only a couple of typing tweaks for compiler warnings which I'm not seeing with gcc-9 or clang-7. I missed changing the project files for the Windows build,  so I will fix that and grab the last release.

**Comment by rajachan** [comment]
Thanks! If the project is not maintained anymore but still has outstanding bugs, we might be better off using cjson / libjansson or the like in the future. Those packages are available in standard OS package repositories so we won't have to ingest files from arbitrary git refs. I haven't really looked at how we use the tokenizer though, so perhaps this single-header is good enough for our use.

**Comment by jlbyrne-hpe** [comment]
Unless I missed something, jsmn is currently just used for parsing ubertest config files. I assume it was chosen as a way to avoid more build dependencies for the project. Given the limited use, my inclination would be to let it be unless another memory corruption issue turns up in the future.

**Review by rajachan — APPROVED** [review]
Looks good to me. Might want to get @j-xiong's sign off too.

**Pull request merged**
