### PR TITLE
core/mr_cache: Force flush 1 LRU entry when flush requested

### PR DESCRIPTION
**Pull request by shefty**
Commit 5169390 changed the cache LRU flushing logic by moving
the flush check to the start of the loop.  The result is that
flushing is not performed as long as the cache is below its
threshhold.  This results in cleanup failing to run when the
cache is being destroyed.

The fi_mr_test will report an assertion that there are
outstanding registrations without the cleanup occurring.
Modify the LRU loop, so that we always flush at least 1
entry when flushing is requested and there are entries
to flush.

Signed-off-by: Sean Hefty <sean.hefty@intel.com>

### CODE REVIEW

**Comment by shefty** [comment]
Fixes #6806

**Comment by wckzhang** [comment]
I'm not convinced this is exactly what we want.

The code segment here:

```
                if ((cache->cached_cnt >= cache_params.max_cnt) ||              
                    (cache->cached_size >= cache_params.max_size) ||            
                    (!dlist_empty(&cache->dead_region_list))) {                 
                        pthread_mutex_unlock(&mm_lock);                         
                        ofi_mr_cache_flush(cache, true);                        
                        pthread_mutex_lock(&mm_lock);                           
                } 
```

would imply that if we have any dead entries, we will kick out an entry from the LRU every time we call mr cache search.

**Comment by wckzhang** [comment]
The likely answer is we change that code segment to something like:
```
		flush_lru = (cache->cached_cnt >= cache_params.max_cnt) ||
			    (cache->cached_size >= cache_params.max_size);
                 if (flush_lru || (!dlist_empty(&cache->dead_region_list))) {                 
                        pthread_mutex_unlock(&mm_lock);                         
                        ofi_mr_cache_flush(cache, flush_lru);
                        pthread_mutex_lock(&mm_lock);                           
                } 
```

**Comment by wzamazon** [comment]
No, cannot do that. `flush_lru` is an argument of this function, when caller call this function with `flush_lru` set to `false`, they do not want the LRU to be flushed at all.

**Comment by wckzhang** [comment]
That's the point, we don't flush the LRU in ofi_mr_cache_search unless we need to.

**Comment by wckzhang** [comment]
Sorry if I am unclear, the code segment I want to change is in the ofi_mr_cache_search function from lines 344-350

**Comment by wzamazon** [comment]
I see. I though you want to change `ofi_mr_cache_flush`

**Comment by shefty** [comment]
@wckzhang - I agree.  The calling site is incorrect, and I believe your suggested change would work.  I would go a little further and rename the flush_lru parameter (*not* the variable you proposed) to 'force_lru_flush' to better describe what exactly that parameter does.

Sorry, I merged this change quickly because all CI was failing

**Comment by shefty** [comment]
See #6808.  There may still be a less change-proof way of handling this, but hopefully we're almost to the point of correctness.  :)

**Pull request merged**
