### PR TITLE
[v1.21.x] Cherry-picked fixes

### PR DESCRIPTION
**Pull request by j-xiong**

### CODE REVIEW

**Review by aingerson — APPROVED** [review]

**Comment by j-xiong** [comment]
bot:aws:retest

**Comment by aingerson** [comment]
@j-xiong Since this has changes to Jenkins, I'm going to replay to pick up the changes coming into this branch but if you already did, feel free to ignore the re-run

**Comment by j-xiong** [comment]
@shijin-aws Any details on the AWS CI failure?

**Comment by shijin-aws** [comment]
@j-xiong Our CI on Ubuntu 20.04 is not stable now due to the OS repo issue, please ignore the failure

**Pull request merged**
