### PR TITLE
Pr/sockets

### PR DESCRIPTION
**Pull request by jithinjosepkl**
- Bind conn-socket to src_addr before connect()
- Reset rx and tx connections while releasing progress table entry
- Add error-reporting for RMA operations
- Implement fi_setname in sockets provider
- Add check for fabric service entry before accessing it

### CODE REVIEW

**Comment by patrickmacarthur** [comment]
@shefty The intent was that `fi_setname()` would be called on a passive endpoint, correct?

@jithinjosepkl Right now (independent of this PR) `fi_setname()` on a passive endpoint causes a segfault, since it isn't filled in in the sock_pep_cm_ops structure.

**Comment by shefty** [comment]
Yes, the intent was that fi_setname() could be called on any endpoint, but the app use model is on the passive ep.

**Comment by goodell** [comment]
> Right now (independent of this PR) fi_setname() on a passive endpoint causes a segfault, since it isn't filled in in the sock_pep_cm_ops structure.

Looks like usnic has this same bug.  Too bad we don't have a test for this functionality yet :disappointed: I'll file the `-FI_ENOSYS` fix soon.

**Comment by jithinjosepkl** [comment]
Yeah, would be good if we have tests to verify this.
@patrickmacarthur  - I had missed to set the function pointer for passive EP. I will submit the fix.

**Pull request merged**
