### PR TITLE
prov/efa: Merge rxr_av and efa_av

### PR DESCRIPTION
**Pull request by dipti-kothari**
Move code from rxr_av to efa_av. Use util_av for efa provider. Rename
function/data struct names from rxr to efa. Defined separate paths for rdm
and dgram endpoints. Deleted rxr_av.

Signed-off-by: Dipti Kothari <dkothar@amazon.com>

### CODE REVIEW

**Comment by shefty** [comment]
The changes are contained to the EFA provider, but this is a sizeable patch.  Is there no way to break up the changes into separate patches?  For example, make the code movement one patch.  Switch to util_av as a separate change.  Separate dgram and rdm code as two patches.  etc.

**Comment by dipti-kothari** [comment]
> The changes are contained to the EFA provider, but this is a sizeable patch. Is there no way to break up the changes into separate patches? For example, make the code movement one patch. Switch to util_av as a separate change. Separate dgram and rdm code as two patches. etc.

Thank you for your suggestion. I have opened a new PR with separate patches, https://github.com/ofiwg/libfabric/pull/5549
Closing this one.

**Comment by rajachan** [comment]
For future reference, you can modify history and force push to the same branch in your fork to update a PR (that will preserve comment history and context).

**Comment by dipti-kothari** [comment]
Yeah, I accidentally deleted my PR branch. For now, I have referenced this PR in the new one

**Comment by jsquyres** [comment]
@dipti-kothari Github pro tip: even if you delete the branch on your Github fork, I _think_ you can just re-push to that same branch name on your fork (i.e., re-create that branch on your fork), and that would have made this PR be ok.  Specifically: Github is just looking at the PR source repo name and branch name.  If that branch changes a dozen times over the life of the PR, that's cool -- Github always just shows the current status of that source repo+branch.

**Comment by dipti-kothari** [comment]
Thank you for the tip @jsquyres @rajachan, I'll be more careful next time.

**Pull request closed without merging**
