### PR TITLE
v1.6.0rc1 prep

### PR DESCRIPTION
**Pull request by shefty**
I was planning on this being 1.6.0rc1, but make checkdist fails for a reason that eludes me (fi_info returns enodata).

@jsquyres - please confirm the libtool versioning.  I think the general rules that we are using is:

1. For a 1.X.0 release, C:A:R -> C+1 : 0 : R+1
2. For a 1.x.Y release, C:A:R -> C : A + 1 : R

The master branch basically leaves A = 0.

### CODE REVIEW

**Comment by j-xiong** [comment]
Could the failure be caused by changing the version to 1.6 while all providers are still at 1.5?

**Comment by shefty** [comment]
@j-xiong - that's probably it -- thanks!

**Comment by shefty** [comment]
That was the issue. Since there have been no API behavior changes between 1.5 and 1.6, I've updated all providers to indicate support for 1.6. @j-xiong @a-ilango @aingerson @bturrubiates @jswaro -- please confirm that this is okay.  This PR is ready  as 1.6.0rc1.

**Comment by j-xiong** [comment]
good for psm, psm2

**Comment by a-ilango** [comment]
👍

**Comment by jsquyres** [comment]
@shefty The libtool versioning scheme you mention isn't *quite* what you stated.  The official rules are here: https://www.gnu.org/software/libtool/manual/libtool.html#Updating-version-info

1. For a 1.X.0 release, C:A:R -> C+1 : 0 : R+1: this is true only if you're guaranteeing backwards compatibility (both in terms of ABI and behavior) to all previous versions that (R+1) spans back to.  This *should* be true for `1.X.0`, for all Libfabric versions of `X`.
1. For a 1.x.Y release, C:A:R -> C : A + 1 : R: this is true only if you're not adding any new interfaces (I'm assuming we're not removing any interfaces in a `1.x.y` release) compared to `1.x.y-1`.  This *should* be true for `1.x.Y`, for all Libfabric values of `Y` (for a constant value of `x`).

I'm only quibbling because of the *should* statements.  In reality, we probably always abide by those 2 conditions for Libfabric releases, but it's worth checking to make sure that they're true for each release.

**Comment by shefty** [comment]
@jsquyres - I did check the official set of rules.  I was only listing what _should_ be the case for our standard release process.  The official rules don't clearly seem to state how to handle stable releases (1.x.y) relative to minor releases (1.x.0).  For example, 1.6.0 doesn't change the API relative to 1.5.3, which the rules suggests that we only bump revision.  I don't think that works, hence the creation of my 'rule' #2.

**Comment by shefty** [comment]
Added commit 81685c9c3aff49309e1810a370e6d02d38c48988 - Fixes #3778

**Comment by jsquyres** [comment]
I think the rules do cover this case, and it's exactly what you said: if no interfaces changed, but the library still changed (e.g., the internals changed), then R->R+1 and nothing else changes (that's rule 3).

**Comment by shefty** [comment]
Sorry, I referenced the wrong rule -- I meant rule 1.  :P   I want to ensure that 1.6.0 doesn't conflict with a possible 1.5.4 release.

**Comment by jsquyres** [comment]
Oh!  I see what you're asking now.

What we've done in this case in Open MPI is just increase R by about 10 or so.  Hence, 1.6.0 can be C.R+10.A, and 1.5.4 can be C.R+1.A, 1.5.5 can be C.R+2.A, ...etc.  I.e., they'll be kept in numerical order -- we just have a gap of unused R numbers (assuming we don't have more than 9 more 1.5.x releases).

Make sense?

**Comment by shefty** [comment]
That makes sense.  I'm not sure which way is better in general.  What I get now (using the current patch), produces libfabric.so.1.9.3 for 1.5.3 and libfabric.so.1.10.0 for v1.6.0.  I have no idea if libfabric.so.1.9.10 would be more or less abusive.  :)

**Comment by jsquyres** [comment]
Heh.  I have come to completely ignore the x.y.z values that show up in the Linux shared library filenames.  I don't think that they mean what most people think that they mean, anyway.  

I try to only think about the C, R, A values -- I think that most people care about is whether the library will link to their application or not.  And the being true to the meaning of the C, R, and A values will ensure that libfabric will link (or not) as decided by the libfabric maintainers.

**Comment by shefty** [comment]
I updated my PR to C : R + 10 : A (or 10:10:9).  I'll update the release process wiki page based on this discussion.  Thanks

**Comment by jsquyres** [comment]
Should it actually be `10.13.9`?

I ask because 1.5.3 is `10.3.9`.

**Comment by shefty** [comment]
Yes, bumped version to 10:13:9.  All initial tests are passing.  Closing this PR and pushing directly with tag for v1.6.0rc1.  Let the testing commence!

**Pull request merged**
