### PR TITLE
[v1.7.x] test_cofigs/shm: cherry-pick shm testing updates

### PR DESCRIPTION
**Pull request by aingerson**
Cherry pick testing updates for shm to avoid failures on the CI when testing 1.7.x PRs

Signed-off-by: aingerson <alexia.ingerson@intel.com>

### CODE REVIEW

**Comment by shefty** [comment]
Will this fix the issues reported in PR #4886?

**Comment by aingerson** [comment]
Affirmative, captain

**Comment by aingerson** [comment]
Ok I lied. I think it also needs the exclude file and maybe something else. Working on it

**Comment by aingerson** [comment]
@shefty ok this should pass now

**Pull request merged**
