### PR TITLE
man: remove misleading MR text in fi_endpoint(3)

### PR DESCRIPTION
**Pull request by goodell**
This change was prompted by a question on the libfabric-users@ list from
Jintack Lim:

http://lists.openfabrics.org/pipermail/libfabric-users/2016-July/000093.html

Signed-off-by: Dave Goodell <dgoodell@cisco.com>

### CODE REVIEW

**Comment by lanl-ompi** [comment]
bot:retest

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by goodell** [comment]
@hppritcha looks like something's gone wonky in the "LANL-Cray" CI setup (unrelated to this change), can you take a look?

**Comment by sayantansur** [comment]
@goodell looks good to me. i'm not sure what else i can do? @j-xiong should merge if it looks good to him too.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Pull request merged**
