### PR TITLE
prov/efa: log hmem iface name instead of enum

### PR DESCRIPTION
**Pull request by wenduwan**
Logging improvement

### CODE REVIEW

**Comment by wenduwan** [comment]
Hey @zachdworkin do you know the reason for appveyor failure?

**Comment by zachdworkin** [comment]
@shijin-aws It doesn't look like appveyor ran anything. There is no job in the history for this PR either. I think it has to do with this: "Appveyor continually checks for branch mergablility for 10 seconds after a PR is opened before running". Since this PR is still checking for ability to merge automatically I suspect that it stopped trying and reported this " AppVeyor was unable to build non-mergeable pull request" failure. I have noticed that github has been lagging recently with things like this so its possible that its just a quirk that needs to get ironed out. I am about to merge an update for Intel CI with #10133. I would rebase to grab those changes and then repush to see if that can trigger appveyor to re-run.

**Comment by zachdworkin** [comment]
@shijin-aws I just merged it. Can you rebase and try again to re-trigger appveyor? I also aborted your Intel-CI job so that it saves time on our resource since you will repush shortly.

**Review by darrylabbate — APPROVED** [review]

**Comment by shijin-aws** [comment]
bot:aws:retest

**Review by shijin-aws — APPROVED** [review]

**Comment by shijin-aws** [comment]
AWS CI failure seems right, but it's not clear to me now how it's related to your change

**Comment by shijin-aws** [comment]
need to rebase on https://github.com/ofiwg/libfabric/pull/10144

**Comment by shijin-aws** [comment]
> AWS CI failure seems real, but it's not clear to me now how it's related to your change

Figured out the bug, need to rebase on https://github.com/ofiwg/libfabric/pull/10144

**Comment by shijin-aws** [comment]
bot:aws:retest

**Comment by wenduwan** [comment]
AWS CI passed. Should be good to go.

**Pull request merged**
