### PR TITLE
prov/efa: Q Key related changes

### PR DESCRIPTION
**Pull request by wzamazon**
This PR contain 2 commits:

1. prov/efa: assign random Q-Key to EFA ep
2. src/common: update EFA address in ofi_straddr() and ofi_str_to_efa()

### CODE REVIEW

**Comment by galpress** [comment]
Note that there's a range of privilged qkeys with the msb turned on
0x8000_0000 thru 0x8000_FFFF: Available for general use - can be used without permission from the
InfiniBand Trade Association
0x8001_0000 Well known IB management Q_Key
0x8001_0001 Device Administration Agent (see Configuration Management Annex)
0x8001_0000 thru 0x8001_FFFF reserved for IBTA definition
0x8002_0000 thru 0x8FFF_FFFF Reserved for external use - An organization can request a privileged
Q_Key by sending the request to the InfiniBand Trade Association - attention Application Working Group.

**Comment by wzamazon** [comment]
@galpress Thank you for the information, will update PR to use 0x8000_0000 to 0x8000_FFFF.

**Comment by galpress** [comment]
I meant that this range probably shouldn't be used.

**Comment by wzamazon** [comment]
@galpress I am confused, I thought this range can be used for general purpose? Which range would you recommend us to use?

**Comment by wzamazon** [comment]
Offline chat with @galpress , 0x8000000 and up is privileged, I have updated the PR to use 0x0 to 0x7fffffff

**Pull request merged**
