### PR TITLE
fabtests/rdm_rma_trigger: add sync to make sure counter values match

### LINKED ISSUE #8165: prov/sockets: failing fi_rdm_rma_trigger
Failing consistently in CI tests:
```
name:   fi_rdm_rma_trigger -p "sockets"
18:21:12    timestamp: 20221026-012105+0000
18:21:12    result: Fail
18:21:12    time:   300
18:21:12    server_cmd: /home/cstbuild/ofi-Install/libfabric/ofi_libfabric/PR-8162/1/reg/bin/fi_rdm_rma_trigger -p "sockets"   -s ci19-eth2
18:21:12    server_stdout: |
18:21:12    client_cmd: /home/cstbuild/ofi-Install/libfabric/ofi_libfabric/PR-8162/1/reg/bin/fi_rdm_rma_trigger -p "sockets"   -s ci20-eth2 ci19-eth2
18:21:12    client_stdout: |
18:21:12      Triggered RMA write to server
18:21:12      RMA write to server
18:21:12      Received completion events for RMA write operations
```

### PR DESCRIPTION
**Pull request by aingerson**
Fixes #8165

### CODE REVIEW

**Comment by shefty** [comment]
🎃  Thanks!

**Comment by shefty** [comment]
bot:aws:retest

**Comment by shefty** [comment]
The changes are producing failures on AWS with the socket provider.
```
debug/install/fabtests/bin/fi_rdm_rma_trigger -p sockets -s 172.31.52.188
server_stdout:
Received message does not match expected message.
```
Failures appeared on 2 separate CI runs, though not on every platform.

**Comment by aingerson** [comment]
I am able to reproduce the error. Looks like a bigger issue happening here. Will update.

**Comment by aingerson** [comment]
Forgot to take into account the extra completion created by the added ft_sync call. Kept the call to eliminate the race condition with the completions and added a dependency on an out of band sync to not add in an extra unforeseen completion

**Comment by aingerson** [comment]
@shefty did you think you would ever see that green check mark again? I think this PR should be good to merge

**Comment by shefty** [comment]
glory hallelujah!

**Pull request merged**
