### PR TITLE
prov/rxd: Add provider specific man page

### PR DESCRIPTION
**Pull request by jithinjosepkl**
- Add fi_rxd.7.md man page
- Fix formatting issues in fi_rxd.7

Signed-off-by: Jithin Jose <jithin.jose@intel.com>

### CODE REVIEW

**Comment by jsquyres** [comment]
You might as well git rm fi_rxd.7 -- it's going to get generated by the OFIWG bot (see https://github.com/ofiwg/libfabric/pull/2214#issuecomment-234638211).

**Comment by j-xiong** [comment]
Removing fi_rxd.7 is not necessary since it is going to be overwritten anyway. In addition, with the file removed the building will fail until the bot generated file is pulled in.

**Comment by jithinjosepkl** [comment]
Hmm, I get build errors if I delete fi_rxd.7 (same for other providers too).

```
make[1]: Entering directory `/home/jose/workspace/tmp/libfabric'
make[1]: *** No rule to make target `man/man7/fi_rxd.7', needed by `all-am'.  Stop.
```

It works even with an empty file though. So, a little confused here.

**Comment by jithinjosepkl** [comment]
Ok, got it. So do you want me to remove the fi_rxd.7 in this PR, or let the ofiwg bot generate it?

**Comment by j-xiong** [comment]
I would suggest just keep it as it is, but I will let @jsquyres decide.

**Comment by jsquyres** [comment]
@j-xiong You're right -- we shouldn't remove it because it'll break the build (my mistake for suggesting it 😊 ).  But there's no point in updating it, either.

**Comment by jithinjosepkl** [comment]
Thanks @jsquyres, I have removed the edits in fi_rxd.7

**Comment by jsquyres** [comment]
👍

**Comment by jsquyres** [comment]
Your friendly OFIWG bot at work: 3346ad53adf75c668a1dcfc3f37d248a6e3a8622 and https://ofiwg.github.io/libfabric/master/man/fi_rxd.7.html

**Pull request merged**
