### PR TITLE
prov/util,efa,tcp,mrail,rxd,rxm,ucx: Refactor the usage of cntrs

### PR DESCRIPTION
**Pull request by shijin-aws**
Currently, cntrs for different operations have different
    field names in util_ep, which causes code duplication and
    makes it hard to expand in the future. This patch refactor
    this code path by introducing two arrays: util_ep.cntrs, and
    util_ep.cntr_inc_funcs to store the pointers to the cntrs
    and its inc functions, which share the uniform procedure
    in ep creation, bind, and close.

This PR also expand the rdm test in fabtests/pytest/shm,sm2 to cover cntr completion type.

### CODE REVIEW

**Review by shefty — APPROVED** [review]
Thanks - nice improvement

**Review by wenduwan — APPROVED** [review]

**Comment by shijin-aws** [comment]
@shefty may I know if the error in ci/cloudbees/stage/parallel-tests/ucx  related?

**Comment by shefty** [comment]
CI failure is related.  Problem building ucx provider.  Several errors along these lines:
```
17:03:41  In file included from prov/ucx/src/ucx_core.c:34:
17:03:41  prov/ucx/src/ucx_core.h: In function ‘ucx_gen_mrecv_completion’:
17:03:41  prov/ucx/src/ucx_core.h:94:3: warning: implicit declaration of function ‘ofi_ep_rx_cntr_inc’; did you mean ‘ofi_ep_cntr_inc’? [-Wimplicit-function-declaration]
17:03:41     ofi_ep_rx_cntr_inc(&req->ep->ep);
17:03:41     ^~~~~~~~~~~~~~~~~~
17:03:41     ofi_ep_cntr_inc
17:03:41  prov/ucx/src/ucx_core.h: In function ‘ucx_do_inject’:
17:03:41  prov/ucx/src/ucx_core.h:122:3: warning: implicit declaration of function ‘ofi_ep_tx_cntr_inc’; did you mean ‘ofi_ep_cntr_inc’? [-Wimplicit-function-declaration]
17:03:41     ofi_ep_tx_cntr_inc(&u_ep->ep);
17:03:41     ^~~~~~~~~~~~~~~~~~
```

**Comment by shijin-aws** [comment]
Thanks, I will fix them

But I am wondering why this error doesn't show in my build, i.e. my ucx does not got compiled, my configure command is like 

```
./configure --prefix=/fsx/libfabric/install
```

**Comment by shijin-aws** [comment]
@shefty May I know the Intel CI failures for this revision?

**Comment by shefty** [comment]
Looking at just the ucx errors:
```
17:53:40  prov/ucx/src/ucx_rma.c: In function ‘ucx_rma_callback’:
17:53:40  prov/ucx/src/ucx_rma.c:177:37: warning: left-hand operand of comma expression has no effect [-Wunused-value]
17:53:40      ofi_ep_cntr_inc(&(ucx_req->ep->ep, CNTR_WR));
17:53:40                                       ^
17:53:40  prov/ucx/src/ucx_rma.c:177:20: error: lvalue required as unary ‘&’ operand
17:53:40      ofi_ep_cntr_inc(&(ucx_req->ep->ep, CNTR_WR));
17:53:40                      ^
17:53:40  prov/ucx/src/ucx_rma.c:177:4: error: too few arguments to function ‘ofi_ep_cntr_inc’
17:53:40      ofi_ep_cntr_inc(&(ucx_req->ep->ep, CNTR_WR));
17:53:40      ^~~~~~~~~~~~~~~
17:53:40  In file included from prov/ucx/src/ucx.h:64,
17:53:40                   from prov/ucx/src/ucx_rma.c:33:
```

**Comment by shijin-aws** [comment]
@shefty I installed ucx and configure libfabric with `--enable-ucx=<ucx_path>` and I could reproduce the error. New revision should fix them. Let me know if Intel CI failed due to the PR again. Thanks!

**Comment by shefty** [comment]
There were a lot of failures with verbs;ofi_rxm.  I restarted the CI to verify.

**Comment by shijin-aws** [comment]
It seems the test failed again, what is the error?

**Comment by shefty** [comment]
CI is still running.  The reports from the previous run haven't been updated yet.  (Or maybe there's a problem updating the report, but I'd let the CI finish before trying to figure that out.)

**Comment by shijin-aws** [comment]
is the CI still running?

**Comment by aingerson** [comment]
@shijin-aws Still lots of rxm failures. All timeouts/hangs. Let me know if you want help reproducing or looking into them

**Comment by shijin-aws** [comment]
@aingerson can you give me an example of failure? rxm doesn't require a special hardware, right?

**Comment by aingerson** [comment]
The failures all happened in our verbs testing which requires special hardware but if the issue is in rxm then I think you should be able to reproduce it with -p "tcp;ofi_rxm" (you just might not see the failures with just "tcp" as the provider). I'm trying to reproduce it though and can't...

Here are all the failures:
```
09:39:32  	verbs-rxm fabtests dbg:                10:20     : 50.00% :  Pass  :   31 : Excluded/Notrun
09:39:32  		Failed tests: 10
09:39:32  			fi_av_xfer -e rdm -p "verbs;ofi_rxm"
09:39:32  			fi_cq_data -e rdm -o senddata -p "verbs;ofi_rxm"
09:39:32  			fi_cq_data -e rdm -o writedata -p "verbs;ofi_rxm"
09:39:32  			fi_poll -t queue -p "verbs;ofi_rxm"
09:39:32  			fi_poll -t counter -p "verbs;ofi_rxm"
09:39:32  			fi_rdm -p "verbs;ofi_rxm"
09:39:32  			fi_rdm -u -p "verbs;ofi_rxm"
09:39:32  			fi_rdm_tagged_peek -p "verbs;ofi_rxm"
09:39:32  			fi_multi_ep -e rdm -v -p "verbs;ofi_rxm"
09:39:32  			fi_recv_cancel -e rdm -v -p "verbs;ofi_rxm"
```

And here is an example of one:
```
09:39:30  - name:   fi_cq_data -e rdm -o writedata -p "verbs;ofi_rxm"
09:39:30    timestamp: 20230710-155724+0000
09:39:30    result: Fail
09:39:30    time:   301
09:39:30    server_cmd:  /home/cstbuild/cloudbees_job_install/OFIWG_Libfabric/ofi_libfabric/PR-9127/6/dbg/bin/fi_cq_data -e rdm -o writedata -p "verbs;ofi_rxm"   -s cb1-ib0
09:39:30    server_stdout: |
09:39:30    client_cmd:  /home/cstbuild/cloudbees_job_install/OFIWG_Libfabric/ofi_libfabric/PR-9127/6/dbg/bin/fi_cq_data -e rdm -o writedata -p "verbs;ofi_rxm"   -s cb2-ib0 cb1-ib0
09:39:30    client_stdout: |
```
All of them are the same - just hanging with no output

**Comment by aingerson** [comment]
@shijin-aws Actually I think it might be an issue with our systems. Let me look into it and then I'll restart it to see if they are resolved

**Comment by aingerson** [comment]
@shijin-aws Issue is resolved, all rxm tests passing. tcp failed but it's the reoccuring bw -U failure that we've been seeing so it's unrelated. everything looks good!

**Comment by shijin-aws** [comment]
@aingerson Thank you! Then I will merge this PR.

**Pull request merged**
