### PR TITLE
Final? set of changes prior to 1.0 alpha interface freeze

### PR DESCRIPTION
**Pull request by shefty**
Addresses open issues marked with alpha release label.

Removes environment variable from libfabric framework.
Defines completion order.
Moves WaitSet from a child of the domain to the fabric
Defines resource management.

### CODE REVIEW

**Comment by shefty** [comment]
@j-xiong @jithinjosepkl - This change set modifies the PSM and socket providers.  Please confirm that the changes make sense.

**Comment by pmmccorm** [comment]
Are all env vars getting removed? ie:
     grep getenv prov/ -R
     prov/sockets/src/sock_fabric.c: char *tmp = getenv("OFI_SOCK_LOG_LEVEL");
     prov/psm/src/psmx_util.c:       if ((s = getenv("OMPI_COMM_WORLD_LOCAL_SIZE"))) {
     prov/psm/src/psmx_util.c:               if ((s = getenv("OMPI_COMM_WORLD_LOCAL_RANK")))
     prov/psm/src/psmx_init.c:       s = getenv(name);
prov/psm/src/psmx_init.c:       psmx_env.uuid           = getenv("SFI_PSM_UUID");

**Comment by shefty** [comment]
No - provider specific values are remaining.  The providers get to deal with those.  Hopefully they remain undocumented and post 1.0, we add new interfaces for publishing and documenting what environment variables are available.

**Comment by j-xiong** [comment]
The PSM changes look fine to me.

**Comment by jithinjosepkl** [comment]
Sockets provider changes also look fine.

**Pull request merged**
