### PR TITLE
[v1.17.x] util/memhooks: Fix a bug when calculating mprotect region

### PR DESCRIPTION
**Pull request by shijin-aws**
backport https://github.com/ofiwg/libfabric/pull/9552

### CODE REVIEW

**Comment by j-xiong** [comment]
bot:aws:retest

**Review by j-xiong — APPROVED** [review]

**Comment by shijin-aws** [comment]
The AWS CI failure is actually real. Doesn't seem to be related to the change but may need to look into it.

**Comment by shijin-aws** [comment]
I will fix the segfault before merging the PR

**Comment by zachdworkin** [comment]
@j-xiong I tried to get this to pass intel-ci with the new jenkinsfile and the old run scripts with no success. I think we will need to backport many ci changes to get this/older branches to pass our new ci configuration.

**Comment by zachdworkin** [comment]
@shijin-aws can you rebase to pickup the CI backports that @aingerson merged last week? This will need to happen for this PR as well as your v1.16 and v1.15 PRs. I think that should resolve the intel-ci run issues.

**Comment by shijin-aws** [comment]
Acked, will do

**Comment by shijin-aws** [comment]
bot:aws:retest

**Comment by a-szegel** [comment]
bot:aws:retest

**Comment by a-szegel** [comment]
bot:aws:retest

**Comment by a-szegel** [comment]
CI is seeing segmentation faults, please fix if you want to backport.
```
[ip-172-31-32-167:63796] *** Process received signal ***
[ip-172-31-32-167:63796] Signal: Segmentation fault (11)
[ip-172-31-32-167:63796] Signal code: Address not mapped (1)
[ip-172-31-32-167:63796] Failing at address: 0x7f3f1920bcf0
```

**Comment by j-xiong** [comment]
@shijin-aws Do you still want to look into the failure? We could drop the backports for 1.15, 1.16 and 1.17 if you agree.

**Comment by shijin-aws** [comment]
@j-xiong it's likely a bug in our infra, I will close this PR before I figure it out. It's being tracked by us internally

**Pull request closed without merging**
