### PR TITLE
sockets: fi_getname()/fi_getpeer() set addrlen

### PR DESCRIPTION
**Pull request by jithinjosepkl**
Signed-off-by: Jithin Jose <jithin.jose@intel.com>

### CODE REVIEW

**Comment by shefty** [comment]
The socket implementations of getname/getpeer truncate the result.

**Comment by jithinjosepkl** [comment]
But if the address is truncated, is it useful to the application?
Instead, should we just return -FI_ETOOSMALL and set *addrlen to correct size?

**Comment by shefty** [comment]
Is it useful?  I'm guessing not, unless there's something useful near the front of the address that may be what the app really cares about, which is the case for struct sockaddr (sa_family).  I think it's fine to return ETOOSMALL(maybe) and set addrlen correctly.  The question is what happens to the user's buffer.  The socket calls that we're emulating truncate the result.

This is probably the behavior that we want to emulate.  The advantage this has is that an address format can grow in a backward compatible manner without the app needing to change.  E.g. struct sockaddr_ib can add new fields if needed.  An app programmed to use sockaddr_ib may not need those new fields or know that they even exist.

And this brings up the question of whether we should return ETOOSMALL or 0.  I'm not sure what the best answer is.  I don't think we want to prevent apps from allocating the address structure on the stack.

**Comment by jithinjosepkl** [comment]
OK, we can truncate the address if that helps backward compatibility.
For return value, I think ETOOSMALL might be better, so that application can be notified that the address is truncated.

**Comment by shefty** [comment]
I think ETOOSMALL makes sense.  An app can code for that as long as we document it correctly.

**Comment by jithinjosepkl** [comment]
Thanks, I have updated the PR.

**Pull request merged**
