### PR TITLE
Script changes required to run fabtests through Coverity Scan nightly

### PR DESCRIPTION
**Pull request by patrickmacarthur**
@jsquyres Please review when you get a chance.  Not super urgent---the fabtests Coverity project has been created but is still pending approval.  So you should probably wait to merge this patch set until the project is approved.  I have tested the script using the latest fabtests master on flatbed and it successfully uploaded the scan results for fabtests, but they are inaccessible until the project is approved.

### CODE REVIEW

**Comment by patrickmacarthur** [comment]
Also, once this gets merged, the `--fabtests-source-dir` and `--fabtests-coverity-token` arguments will need to be added to the cron job.

**Comment by patrickmacarthur** [comment]
Another update (sorry for the notification spam): I checked again and was able to access the defect list, so based on that it looks like the project has been approved on the Coverity side.

**Comment by jsquyres** [comment]
Overall, I made some very minor comments.  Otherwise, looks pretty good.

**Comment by patrickmacarthur** [comment]
I pushed two more commits which address your comments.

**Comment by jsquyres** [comment]
:+1: 

You want to merge and update flatbed to run this new stuff?

**Comment by patrickmacarthur** [comment]
Yes, should be good to merge.

**Pull request merged**
