### PR TITLE
prov/efa: ignore unsupported req packets instead write error

### PR DESCRIPTION
**Pull request by wzamazon**
Currently, receiver will write an eq error when it received
a REQ packet it cannot support. This patch make the receiver
to send a handshake back and ignore the unsupported REQ packet,
sender can act accordingly when it received handshake.

Signed-off-by: Wei Zhang <wzam@amazon.com>

### CODE REVIEW

**Comment by dipti-kothari** [comment]
bot:aws:retest

**Comment by rwespetal** [comment]
I don't think this safe to do. Doesn't this require us to resend a packet after a handshake is received stating an older protocol version? How is the sender going to know which packets need to be resent without blocking on each send that requires an extra feature? That's the goal here and I don't see how this change helps that.

In addition this is going to hide bugs if the sender erroneously adds a feature bit before processing the handshake packet.

**Comment by wzamazon** [comment]
The goal of this change is to give sender a choice in sending the REQ packets. 

Prior to this change, sender has no choice but to wait for handshake, the waiting time can be indefinite because the handshake packet is sent after receiver calls progress engine.

With this change, sender has a choice for some extra features. For those features that requires feed backs from receivers (delivery complete for example), the REQ can be sent directly without waiting handshake. The idea is that if a handshake came back and the receiver does not support it. libfabric will write an error completion entry to notify the application, and application can decide wether to resend or not. 

>How is the sender going to know which packets need to be resent without blocking on each send that requires an extra feature?
The EFA provider will not resend the packet, but will write error completion entry to indicate the send failed. The application will decide whether to resend or not.

**Comment by rwespetal** [comment]
> With this change, sender has a choice for some extra features. For those features that requires feed backs from receivers (delivery complete for example), the REQ can be sent directly without waiting handshake. The idea is that if a handshake came back and the receiver does not support it. libfabric will write an error completion entry to notify the application, and application can decide wether to resend or not.

I see, okay that makes sense. So that means that we have an option to either fallback until we get a handshake (RDMA) or just try and write an error (delivery complete). I think that's okay as long as client/server applications are willing to handle that error and retry. Of course, MPI will just crash and that's fine since mixed Libfabric versions are uncommon in that scenario.

> > In addition this is going to hide bugs if the sender erroneously adds a feature bit before processing the handshake packet.
> 
> Not sure I understand this scenario, would you please elaborate?

My concern is now the assert and error completion are being dropped in the receive path, so this will happen silently. If an extra flag is incorrectly set for a packet it won't be detected. I don't think putting an assert in here is correct either as then we can't test this behavior. I think adding some validation to the handshake packet init and processing in the debug path would be a good idea, the memcpy there right now seems a bit error prone.

**Comment by wzamazon** [comment]
>My concern is now the assert and error completion are being dropped in the receive path, so this will happen silently. If an extra flag is incorrectly set for a packet it won't be detected. I don't think putting an assert in here is correct either as then we can't test this behavior. I think adding some validation to the handshake packet init and processing in the debug path would be a good idea, the memcpy there right now seems a bit error prone.

Indeed, now the assertion and writing EQ as gone, packets can be ignored silently. The idea was rely on the FI_WARN to notify user, which mean user need to turn on FI_LOG_LEVEL=warn. Maybe instead of FI_WARN, we use ```fprintf``` to explicitly warn the application that happened?

The initialization of handshake packet is used when EP received any REQ packets, not just unsupported REQ packets, so might be the place we want to handle this.

**Comment by rwespetal** [comment]
> > My concern is now the assert and error completion are being dropped in the receive path, so this will happen silently. If an extra flag is incorrectly set for a packet it won't be detected. I don't think putting an assert in here is correct either as then we can't test this behavior. I think adding some validation to the handshake packet init and processing in the debug path would be a good idea, the memcpy there right now seems a bit error prone.
> 
> Indeed, now the assertion and writing EQ as gone, packets can be ignored silently. The idea was rely on the FI_WARN to notify user, which mean user need to turn on FI_LOG_LEVEL=warn. Maybe instead of FI_WARN, we use `fprintf` to explicitly warn the application that happened?
> 
> The initialization of handshake packet is used when EP received any REQ packets, not just unsupported REQ packets, so might be the place we want to handle this.

I'm okay with the FI_WARN. We just need to be aware of this when debugging the handshake packet in the future and adding some additional checks when debug is enabled will also help here.

**Comment by rwespetal** [comment]
Just adding a note here that this handshake feature was added in 1.10 so there are older versions in the field without this patch. This should be okay, though, as an error will be written somewhere so we won't silently drop packets. It'll be easier to handle this error on the sender side so users may want to update if this is important to them.

**Pull request merged**
