### PR TITLE
util/src: fix syntax error

### PR DESCRIPTION
**Pull request by amirshehataornl**
Fix syntax error introduced in:
32ead6680c8feb6ee933cf28482a6f3b6bc0a6b8 core and util/prov: introduce cuda ipc monitor

Signed-off-by: Amir Shehata <shehataa@ornl.gov>

### CODE REVIEW

**Review by shijin-aws — APPROVED** [review]

**Comment by shijin-aws** [comment]
Thank you @amirshehataornl !

**Comment by shijin-aws** [comment]
Can you back port it to v1.16.x?

**Comment by shijin-aws** [comment]
Thank you @amirshehataornl , can you backport it to v1.16.x?

**Comment by shijin-aws** [comment]
@shefty is this PR ok for merge?

**Comment by shefty** [comment]
Intel CI failure is unrelated:
```
name:   fi_rdm_pingpong -I 5 -v -U -p "shm"
08:50:21    timestamp: 20220926-155020+0000
08:50:21    result: Fail
08:50:21    time:   9
08:50:21    server_cmd:  /home/cstbuild/ofi-Install/libfabric/ofi_libfabric/PR-8029/1/reg/bin/fi_rdm_pingpong -I 5 -v -U -p "shm"  -D ze -i 0  -s ci10
08:50:21    server_stdout: |
08:50:21      [error] fabtests:common/shared.c:2610: cq_readerr 22 (Invalid argument), provider errno: -22 (Invalid argument)
```
Okay to merge

**Pull request merged**
