### PR TITLE
util/mr_cache: Series of changes to avoid calling malloc/free while holding monitor lock

### PR DESCRIPTION
**Pull request by shefty**
Not tested.

This series restructures the mr_cache, so that ofi_mr_cache_flush() will cleanup stale entries without holding the monitor lock.  Specifically, we cannot hold the monitor lock while calling util_mr_free_entry().

However, there are still code paths that call util_mr_free_entry() while holding the monitor lock.  For example, notify, merge, cleanup, and create still call uncache_entry, which calls free_entry.  The intent is for additional patches to update uncache_entry to move the stale entries to a flush_list, and have ofi_mr_cache_flush() cleanup those entries when called.

### CODE REVIEW

**Comment by shefty** [comment]
@jswaro - fairly simple change.  I'm still analyzing how to update the mr cache, particularly around handling the registration case.

**Comment by jswaro** [comment]
> jswaro: prov/util/src/util_buf.c:220: ofi_bufpool_destroy: Assertion `(pool->attr.flags & OFI_BUFPOOL_NO_TRACK) || (buf_region->use_cnt == 0)' failed.

**Comment by jswaro** [comment]
It does seem to avoid the hang though. I'll cancel my PR. It seems like this should address the issue.

**Comment by shefty** [comment]
@jswaro - Do you have a backtrace for that assertion?  If it's in the CI, I'll find it.

**Comment by jswaro** [comment]
> @jswaro - Do you have a backtrace for that assertion? If it's in the CI, I'll find it.

I don't. I was re-running the test case for #5554. I'll see if I can generate one, but it is occuring during MPI finalize while libfabric objects are being closed.

**Comment by jswaro** [comment]
```
(gdb) bt
#0  0x00002b13c8313e55 in ofi_bufpool_destroy (pool=0x460cd0) at prov/util/src/util_buf.c:223
#1  0x00002b13c831b549 in ofi_mr_cache_cleanup (cache=0x460898) at prov/util/src/util_mr_cache.c:455
#2  0x00002b13c83536b5 in vrb_domain_close (fid=0x460790) at prov/verbs/src/verbs_domain.c:130
#3  0x00002b13c8394d72 in fi_close (fid=0x460790) at ./include/rdma/fabric.h:587
#4  0x00002b13c8395350 in rxm_domain_close (fid=0x45cb50) at prov/rxm/src/rxm_domain.c:116
#5  0x00002b13c4a057a7 in PMPI_Finalize () ...
#6  0x00000000004014ec in main ()
```

**Comment by jswaro** [comment]
```
(gdb) print *pool
$2 = {
  free_list = {
    entries = {
      head = 0x85e020,
      tail = 0x2142deb0
    },
    regions = {
      next = 0x85e020,
      prev = 0x2142deb0
    }
  },
  entry_size = 160,
  entry_cnt = 832,
  region_table = 0x474380,
  region_cnt = 13,
  alloc_size = 10400,
  region_size = 10240,
  attr = {
    size = 120,
    alignment = 16,
    max_cnt = 0,
    chunk_cnt = 64,
    alloc_fn = 0x0,
    free_fn = 0x0,
    init_fn = 0x0,
    context = 0x0,
    flags = 0
  }
}
(gdb) print buf_region
$3 = (struct ofi_bufpool_region *) 0x45acf0
(gdb) print *buf_region
$4 = {
  entry = {
    next = 0x0,
    prev = 0x0
  },
  free_list = {
    next = 0x45ad00,
    prev = 0x45ad00
  },
  alloc_region = 0x85ddc0 "",
  mem_region = 0x85de60 "\360@\200\353\023+",
  index = 0,
  context = 0x0,
  pool = 0x460cd0,
  use_cnt = 4
}```

**Comment by jswaro** [comment]
Just based on the output so far, is it the case that the rbtree wasn't flushed during clean up to remove those stale entries?

**Comment by jswaro** [comment]
```c
diff --git a/prov/util/src/util_mr_cache.c b/prov/util/src/util_mr_cache.c
index fbfba7a18..6bc48592b 100644
--- a/prov/util/src/util_mr_cache.c
+++ b/prov/util/src/util_mr_cache.c
@@ -429,6 +429,8 @@ void ofi_mr_cache_cleanup(struct ofi_mr_cache *cache)
        if (!cache->domain)
                return;

+       ofi_mr_cache_flush(cache);
+
        FI_INFO(cache->domain->prov, FI_LOG_MR, "MR cache stats: "
                "searches %zu, deletes %zu, hits %zu notify %zu\n",
                cache->search_cnt, cache->delete_cnt, cache->hit_cnt,
```

The above solved the problem for me.

**Comment by shefty** [comment]
@jswaro - thanks.  That looks like the correct fix.  The ofi_mr_cache_cleanup() cleans up the lru_list, but not the flush_list.  We can simplify the ofi_mr_cache_cleanup() a little by calling ofi_mr_cache_flush in a loop.  I'll update my series.

**Comment by shefty** [comment]
Intel CI failure:
```
13:24:05  Start mpi_stress at Wed Jan 22 13:24:05 2020
13:24:05  
13:24:05     Size (bytes)	     TxMessages	  TxMillionBytes/s	   TxMessages/s
13:24:25  Cannot contact n1-hfi1: java.lang.InterruptedException
```
some node access error.

**Pull request merged**
