### PR TITLE
core/epoll: Enables the epoll over poll abstraction for all builds

### PR DESCRIPTION
**Pull request by shefty**
The purpose behind this series is to provide the ofi_epoll semantics over the poll() implementation directly to providers.  In scale-up testing, poll significantly outperforms epoll (by multiple factors).  So the epoll over poll implementation is exposed as a separate option that is directly callable, under a new name (ofi_pollfds).  The behavior of ofi_epoll remains the same, based on whether epoll is available or not.

Additional changes are still in the works to adapt the tcp provider to use the new ofi_pollfds.  Posting these changes for review, particularly since it updates the usnic provider to use the epoll abstraction.

### CODE REVIEW

**Comment by shefty** [comment]
@jsquyres - Please see the changes to the usnic provider.  In practice, as long as epoll is available, the behavior _should_ be the same, barring any coding errors in my conversion.  The change allows building libfabric with the --disable-epoll configure option, in order to force the use of the poll implementation of epoll (for testing purposes, and as it turned out, for performance).

If you're okay with the changes, I'd like to merge them.  Dropping them would just mean I would need to disable usnic from my build when testing the disable-epoll option.

**Comment by shefty** [comment]
This is close, but the rxm changes are incomplete.  Man page updates are also needed.

**Comment by jsquyres** [comment]
@shefty Fortunately, the Nroff Elves are still working throughout the COVID-19 pandemic.

thumbsup

**Comment by sydidelot** [comment]
@shefty I just came across this patch and I wonder what are the performance issues for epoll you are referring to?
```
 In scale-up testing, poll significantly outperforms epoll (by multiple factors).
```
Could you please detail/clarify this point? Is there any performance results you can share to illustrate this performance penalty with epoll()? I always thought that epoll() was significantly faster than poll() at scale, especially as with poll() you need to check individual `struct pollfd` entries, if they are ready or not.

**Pull request merged**
