### PR TITLE
fabtests/rdm_stress: Add count option to json key/pair options

### PR DESCRIPTION
**Pull request by wckzhang**
Signed-off-by: William Zhang <wilzhang@amazon.com>

### CODE REVIEW

**Comment by wckzhang** [comment]
A follow up to - https://github.com/ofiwg/libfabric/issues/8465

**Review by shefty — APPROVED** [review]
Intel CI failure is unrelated.

**Comment by wckzhang** [comment]
bot:aws:restart

**Comment by wckzhang** [comment]
bot:aws:retest

**Comment by wckzhang** [comment]
@shefty can we merge the PR?

**Comment by shefty** [comment]
done -- thanks

**Pull request merged**
