### PR TITLE
Fix assets loading over http.

### LINKED ISSUE #1635: Website doesn't render correctly when loaded over https
Some of the CSS resources are loaded using http and are blocked when loading over https.

### PR DESCRIPTION
**Pull request by bturrubiates**
This should fix #1635. 

@jsquyres @shefty 

Signed-off-by: Ben Turrubiates <bturrubi@cisco.com>

### CODE REVIEW

**Comment by jsquyres** [comment]
Does this make it work over both http and https?

**Comment by bturrubiates** [comment]
> Does this make it work over both http and https?

It currently works over both but we get errors on the https version about loading assets over http. So if you checkout the [https](https://ofiwg.github.io/libfabric/) version, it looks weird because the assets are blocked. I believe this should fix that.

**Comment by bturrubiates** [comment]
You can look at the version I deployed at: 

https://bturrubiates.github.io/libfabric/

**Comment by shefty** [comment]
As long as it works, I'm good.

**Comment by jsquyres** [comment]
:+1:

**Pull request merged**
