### PR TITLE
travis: set osx_image to a later (supported) version

### PR DESCRIPTION
**Pull request by shefty**
Re-enable support for dynamic receive buffering.  This
provides an optimization over the tcp provider to
avoid intermediate data copies through rxm bounce
buffers.

Signed-off-by: Sean Hefty <sean.hefty@intel.com>

### CODE REVIEW

**Comment by shefty** [comment]
bot:aws:retest

**Comment by shefty** [comment]
@rwespetal - Can you confirm that the AWS failures are resource related, and not issues in the PR?

**Comment by rwespetal** [comment]
It looks like the failures are NCCL test timeouts with `tcp;ofi_rxm`, so same signature as issue #6441. I thought that issue was resolved by another PR already.

**Comment by shefty** [comment]
This PR is wanting to re-enable one of the optimizations.  So it is possible that it's causing issues.

**Comment by shefty** [comment]
Dropped rxm/tcp changes -- just proceeding with the OS X CI change.

**Pull request merged**
