### PR TITLE
prov/gni: add a buddy allocator

### PR DESCRIPTION
**Pull request by hppritcha**
add a buddy allocator to gni provider.  This will be used in paths where fast allocation/release+
fast coalesce of preregistered buffers is needed.

Upstream merge of ofi-cray/libfabric-cray#594

@sungeunchoi

### CODE REVIEW

**Comment by jithinjosepkl** [comment]
@hppritcha - Can we move this into the common code? It would be good to have it there, if we could abstract out the memory registration part.

**Comment by hppritcha** [comment]
This code doesn't have memory registration calls buried in it.  This is a candidate for common code move at some point soon.  Please open an issue and assign to @e-harvey .

**Comment by jithinjosepkl** [comment]
Nice! I will open an issue for this.

**Comment by shefty** [comment]
Can we show that this is faster than alloc/free?

**Comment by sungeunchoi** [comment]
It's obviously going to depend on the use cases.  We don't expect to replace all our alloc/free call with this allocator.

**Pull request merged**
