### PR TITLE
prov/sm2: Add host to CUDA device IPC protocol 

### PR DESCRIPTION
**Pull request by sunkuamzn**
This protocol enables arbitrary sized messges from host memory to CUDA
device memory

### CODE REVIEW

**Comment by shijin-aws** [comment]
The title says ` prov/sm2: Add device to host IPC protocol #8956 `, but description says `This protocol enables arbitrary sized messges from host memory to CUDA`. So it's host-to-device or device-to-host?

**Comment by sunkuamzn** [comment]
> The title says `prov/sm2: Add device to host IPC protocol #8956`, but description says `This protocol enables arbitrary sized messges from host memory to CUDA`. So it's host-to-device or device-to-host?

fixed. it's host to CUDA device.

**Comment by a-szegel** [comment]
Where is device to host handled?

**Comment by sunkuamzn** [comment]
> Where is device to host handled?

Device to host with use regular IPC protocol because the local `iface` is `FI_HMEM_CUDA`. The logic in the `sm2_proto_select` function

**Comment by sunkuamzn** [comment]
Closing in favor of https://github.com/ofiwg/libfabric/pull/8919

**Pull request closed without merging**
