### PR TITLE
prov/gni: fix a problem with handling fi_addr_str

### LINKED ISSUE #4963: GNI provider needs to handle FL_ADDR_STR format better
Turns out the GNI provider partially implements support for ```FI_ADDR_STR``` but not for the case of ```FI_SOURCE``` + ```FI_SOURCE_ERR```.

### PR DESCRIPTION
**Pull request by hppritcha**
when also using FI_SOURCE_ERROR.  There were a bunch of places
in the GNI provider where the case of FI_ADDR_STR address format
was not being correctly handled.

Improve error handling for av insert.

Fixes #4963

Signed-off-by: Howard Pritchard <howardp@lanl.gov>

### CODE REVIEW

**Comment by hppritcha** [comment]
@soumagne would you mind having someone run the mercury tests against this?  It should not impact HG if you aren't using FI_STR_ADDR.

**Comment by soumagne** [comment]
Sorry for the delay in responding. OK I will take a look. Yes it should not matter to us though because we had to do our own string to native format conversion, see: https://github.com/mercury-hpc/mercury/blob/master/src/na/na_ofi.c#L1157
so we use FI_ADDR_GNI and not FI_ADDR_STR.

**Comment by hppritcha** [comment]
bot:intel:retest

**Comment by hppritcha** [comment]
looks like Intel CI failure is spurious.  merging.

**Pull request merged**
