### PR TITLE
prov/psm,psm2: Add some provider build options to debug output

### PR DESCRIPTION
**Pull request by j-xiong**
Also replace a few references of PSM with PSM2 for consistency.

Signed-off-by: Jianxin Xiong <jianxin.xiong@intel.com>

### CODE REVIEW

**Comment by hppritcha** [comment]
ignore the LANL -CI results for now I've got to fix up the way libfabric builds on trinitite slave node

**Comment by shefty** [comment]
FWIW, ofi_register_provider() displays this information as well.

**Comment by j-xiong** [comment]
Removed the version output since it's duplicated.

**Comment by hppritcha** [comment]
bot:lanl:retest

**Pull request merged**
