### PR TITLE
v1.16.1

### PR DESCRIPTION
**Pull request by shefty**
New package to pull in missing verbs_osd.h file.

Signed-off-by: Sean Hefty <sean.hefty@intel.com>

### CODE REVIEW

**Comment by shefty** [comment]
bot:aws:retest

**Comment by shefty** [comment]
@wckzhang - Can you help me understand the AWS failures?

**Comment by wzamazon** [comment]
bot:aws:retest

**Comment by wzamazon** [comment]
@shefty I restarted the CI

**Comment by shefty** [comment]
Intel CI failure is shm + ze problem.

**Comment by wzamazon** [comment]
@shefty Sorry for the last minute request, can you add https://github.com/ofiwg/libfabric/pull/8075 to this release?

**Comment by shefty** [comment]
No problem.  I just picked https://github.com/ofiwg/libfabric/pull/8067/commits/dcd37a737e35b640e094d1363f46c345034ea618 from main and added to this PR.

**Comment by shefty** [comment]
Memo to me:  update the release notes to reflect the new patches and release date.

**Pull request merged**
