### PR TITLE
prov/sockets: Added terminating comment.

### PR DESCRIPTION
**Pull request by e-harvey**
@hppritcha found a incomplete comment in the socket provider's version of fi_direct.h.

@sungeunchoi

### CODE REVIEW

**Comment by sungeunchoi** [comment]
:+1:

**Comment by shantonu** [comment]
Thanks!

**Comment by jithinjosepkl** [comment]
Wondering why the travis-CI FI_DIRECT build check didn't catch this.

**Comment by e-harvey** [comment]
@shantonu You're welcome.
@jithinjosepkl I'm not sure how the travis-CI build is setup, although maybe the FI_DIRECT build is building with the sockets provider disabled.

Please merge; I do not seem to have the option to merge.

**Comment by jithinjosepkl** [comment]
@e-harvey - Shantonu and I looked at this. Currently --enable-direct defines FABRIC_DIRECT_ENABLED, but the header files look for  FABRIC_DIRECT (except gni provider). I assume --enable-direct should define FABRIC_DIRECT. But I am confused here because gni provider is already making use of both FABRIC_DIRECT_ENABLED and FABRIC_DIRECT. We are double-checking this with Sean.

So, travis didn't show this error because FABRIC_DIRECT is not getting defined.

Btw, are you specifying FABRIC_DIRECT as CFLAGS in your build? Also, I am wondering why gni fabric-direct build is trying to build sockets-provider?

**Comment by e-harvey** [comment]
Okay.  FABRIC_DIRECT is defined in CFLAGS when building the application.  We shouldn't define FABRIC_DIRECT in CFLAGS when building libfabric.  I believe this was found by mistake while trying to compile gnitest using FABRIC_DIRECT.

**Pull request merged**
