### PR TITLE
prov/rxd: fix default av count

### PR DESCRIPTION
**Pull request by aingerson**
Environment variable FI_OFI_RXD_MAX_PEERS was added to set
the AV count - remove default AV size and replace with
environment variable.

TODO - implement dynamic AV sizing

Signed-off-by: aingerson <alexia.ingerson@intel.com>

### CODE REVIEW

**Comment by shefty** [comment]
If the environment variable isn't set, does the AV size get set to 0 and then not grow?

**Comment by aingerson** [comment]
@shefty If the environment variable isn't set then the util AV will grow but the per-connection data maxes out at that variable (default is 1024). 
We need to add the ability for the rxd_peer number to grow as needed (stored in the rxd_ep). Would you like me to add that for this fix or leave it for a later date?

**Comment by shefty** [comment]
We can save the dynamic growing until later.  I was mostly concerned that this would just stop working completely if someone didn't set the environment variable.

**Comment by aingerson** [comment]
Ah gotcha. Well yes and no, it defaults to 1024. Just doesn't work if you're trying to run more than that and don't set it because the av can't grow past that (as of now).

**Pull request merged**
