### PR TITLE
fabtest: Add fabtests for FI_DELIVERY_COMPLETE

### PR DESCRIPTION
**Pull request by aolia-0303**
Add fabtests to test EFA provider can support FI_DELIVERY_COMPLETE

Signed-off-by: Ao Li <aolia@amazon.com>

### CODE REVIEW

**Review by wzamazon — APPROVED** [review]

**Comment by shefty** [comment]
Please update man page.  I restarted Intel CI to re-check failure

**Comment by shefty** [comment]
Recording the Intel CI failure this time, and restarting.  The failure was:
```
12:27:55  /home/build/ofi-Install/libfabric/ofi_libfabric/PR-6369/2/dbg/bin/runfabtests.sh: line 483: 191835 Killed                  ${SERVER_CMD} "${EXPORT_ENV} $s_cmd" &>$s_outp
12:27:55  - name:   fi_rdm_atomic -o all -I 1000 -U -p "shm"
12:27:55    result: Fail
12:27:55    time:   2
```
which is related to this change.  It's possible that the -U increased the time needed to run the test, resulting in a forced timeout.

**Comment by aolia-0303** [comment]
> Recording the Intel CI failure this time, and restarting. The failure was:
> 
> ```
> 12:27:55  /home/build/ofi-Install/libfabric/ofi_libfabric/PR-6369/2/dbg/bin/runfabtests.sh: line 483: 191835 Killed                  ${SERVER_CMD} "${EXPORT_ENV} $s_cmd" &>$s_outp
> 12:27:55  - name:   fi_rdm_atomic -o all -I 1000 -U -p "shm"
> 12:27:55    result: Fail
> 12:27:55    time:   2
> ```
> 
> which is related to this change. It's possible that the -U increased the time needed to run the test, resulting in a forced timeout.

The `-U` flag should only works with efa provider. I will address that.

**Comment by rajachan** [comment]
> The -U flag should only works with efa provider. I will address that.

Why is that? Should it not be applicable to any provider that supports delivery complete?

**Comment by aingerson** [comment]
This should work with the shm provider. It's not a timeout issue though. It's completing right away but finishing with an error. I'll take a look.

**Comment by shefty** [comment]
I agree with Raghu, the -U option is generic, we just need to understand the failure.

**Comment by aingerson** [comment]
It's a shm bug. I'll push a fix for it shortly.

**Comment by aolia-0303** [comment]
> It's a shm bug. I'll push a fix for it shortly.

Thanks!

**Comment by aingerson** [comment]
#6383 should fix this issue. Thanks for catching!

**Comment by aolia-0303** [comment]
> Please update man page. I restarted Intel CI to re-check failure

Updated the man page just now.

**Comment by shefty** [comment]
@aolia-0303 - Please rebase over master, so CI will run with the latest shm provider fixes.

**Comment by aolia-0303** [comment]
> @aolia-0303 - Please rebase over master, so CI will run with the latest shm provider fixes.

Rebased. Passing all the tests right now.

**Pull request merged**
