### PR TITLE
Fix warning while making libfabric.map target.

### PR DESCRIPTION
**Pull request by bturrubiates**
- The file needs to invoke the C preprocessor but the old filename had
  the .cpp extension which made gcc treat it as if it were a C++ file.
  When combined with the -std=gnu99 flag, this produced a warning.
  Renaming the file to have a .c extension fixes the problem.

@shefty @jsquyres @goodell @hppritcha @sungeunchoi @e-harvey 

Signed-off-by: Ben Turrubiates <bturrubi@cisco.com>

### CODE REVIEW

**Comment by jsquyres** [comment]
:+1:

...except for the persistent, nagging thought I have: why are we using the C pre-processor at all?  I know it's working, but it just seems downright weird to use the CPP to process a non-C/plain text file.  Why not use the m4 preprocessor?  I.e., can't you use something like `m4_include` instead of `#include`?

**Comment by e-harvey** [comment]
:+1:

**Comment by jsquyres** [comment]
@e-harvey Have a look at #1829 as an alternative to this PR.

**Comment by e-harvey** [comment]
Either solution seems appropriate. I think it's good that #1829 checks for the existence of provider.map during configury.

**Comment by bturrubiates** [comment]
> ...except for the persistent, nagging thought I have: why are we using the C pre-processor at all? I know it's working, but it just seems downright weird to use the CPP to process a non-C/plain text file. Why not use the m4 preprocessor? I.e., can't you use something like m4_include instead of #include?

I think it definitely makes more sense to use m4 for this. If that works correctly, then we can just close this one. :+1:

**Comment by goodell** [comment]
Even m4 seems like overkill here when plain autoconf could handle it.  Why not just switch this to be `libfabric.map.in` and then [`AC_SUBST_FILE`](http://www.gnu.org/software/autoconf/manual/autoconf.html#Setting-Output-Variables) either `prov/$enable_direct/provider_FABRIC_1.0.map` or `/dev/null` depending on whether `enable_direct` is set?

**Comment by jsquyres** [comment]
I think we're coming to consensus on #1829.  @bturrubiates Do you want to close this PR?

**Comment by bturrubiates** [comment]
> I think we're coming to consensus on #1829. @bturrubiates Do you want to close this PR?

Sure

**Pull request closed without merging**
