### PR TITLE
verbs: Enable fork support by default

### LINKED ISSUE #1763: Need fork support
This is a general issue about what to do for fork support.  Specifically, the verbs provider does not handle users calling fork.  Doing so requires either setting an environment variable or calling ibv_fork_init.

There is overhead to always assuming that an application will call fork.  Should libfabric expose some sort of control option or capability that an app can use to indicate that fork support is required?

We need input from at least one other provider on whether it can handle fork and how.

### PR DESCRIPTION
**Pull request by a-ilango**
This should fix #1763

### CODE REVIEW

**Comment by sayantansur** [comment]
Is there an OFI specified way for an app to turn off fork support? The issue that's linked seemed to indicate that there would be a way for an app to disable it. Of course, we could use provider specific ways, such as IBV_FORK_SAFE etc.

**Comment by a-ilango** [comment]
This patch doesn't address the "disabling fork support" part yet. Sorry, I missed that in the issue. We could have an environment variable which if set would turn off enabling fork support. Does that work?

**Comment by a-ilango** [comment]
Added env variable FI_VERBS_DISABLE_FORK which if set to "no" will turn off enabling fork support.

**Comment by shefty** [comment]
What if we went with a generic env var instead, rather than a provider specific one?  FI_NO_FORK?  Not sure of the name, but we're not disabling fork, only indicating that it won't be called. Though even that may be too much - fork-exec is likely always okay.

**Comment by a-ilango** [comment]
If any other provider would also have such fork based limitation, we could make it a generic env variable. How about FI_NO_FORK_SAFE (similar to IBV_FORK_SAFE)? That says it may not be safe to call fork when this variable is set.

**Comment by shefty** [comment]
I want to convert NO_FORK_SAFE to FORK_UNSAFE.

**Comment by sayantansur** [comment]
In terms of what we call it ... Is the real problem with fork() or the fact that certain providers/HW don't interact very well with COW? As you pointed out fork, exec is fine.

Should we name it something like FI_MR_REG_[DONT]FORK, that actually specifies the application visible behavior, i.e. the availability of registered memory regions in the child after fork.

Or is this unnecessarily pedantic and confusing? :-)

**Comment by shefty** [comment]
The flag is intending to specify the application behavior, not the provider's.  It indicates the app will not call fork.  Then the provider can optimize around that behavior.

No network related resources, which includes application network buffers, are defined for use by a forked process, whether this is set or not.

**Comment by sayantansur** [comment]
Yea, you're right. I was being difficult.

**Comment by shefty** [comment]
See #2169

**Comment by shefty** [comment]
@a-ilango - if it makes things easier, just have this patch call fork_init, and leave the env var to a separate patch.

**Comment by a-ilango** [comment]
I think it shouldn't be a prob. I was just waiting for a consensus. I shall update this patch to use FI_FORK_UNSAFE generic env variable. I'm assuming there are no more changes.

**Comment by a-ilango** [comment]
Updated the PR with new env variable and help text.

**Pull request merged**
