### PR TITLE
More 1.5 api version checks

### PR DESCRIPTION
**Pull request by shefty**
and my editor automatically strips trailing white space when saving, accounting for the removal of unnecessary white space changes in the files.

The most significant patch attempts to handle the update to the domain_attr::mr_mode field.

This series touches multiple providers. @a-ilango @alexander-sannikov @jsquyres

### CODE REVIEW

**Comment by shefty** [comment]
Build issues with the providers I don't build myself have been resolved.

**Comment by shefty** [comment]
@a-ilango @goodell @jsquyres - this series touches the verbs and usnic providers.  Although minor, I'd prefer approval prior to merging.

**Comment by a-ilango** [comment]
👍

**Comment by shefty** [comment]
updated series to resolve merge conflicts

**Comment by shefty** [comment]
Resolving conflicts pulled in a patch to the verbs provider that needed to be updated.

**Pull request merged**
