### PR TITLE
sockets: minor updates

### PR DESCRIPTION
**Pull request by jithinjosepkl**
- fix src/dest iov len mismatch for readv operations
- change ifdef to if while checking for debug flag

### CODE REVIEW

**Comment by shefty** [comment]
Is there a delay in runfabtests that ensures that the server for the next test doesn't conflict with the previous test?  Do we need a longer delay in test startup?  Is there someway to sync the script that doesn't use a hard-coded delay, like waiting for the server to print "ready" or something like that?  ( @pmmccorm @shantonu )

**Comment by shantonu** [comment]
In <code>runfabtests.sh</code> we have a 2s ssh <code>ConnectTimeout</code> and we <code>wait</code> for server and client process to finish before starting the next test. Not sure why are seeing the failure in Travis.

**Comment by a-ilango** [comment]
There is 1 second delay between starting server and starting the client.
I tried the sync method where the server would print some string and runfabtests.sh would wait for it before starting off the client but I'm unable to get it working. In the current code, the server output is redirected to a file. When I try reading the file I'm not seeing the string I'm printing from the server.

**Comment by jithinjosepkl** [comment]
Merging the pull-request as the travis failure is unrelated to this.

**Pull request merged**
