### PR TITLE
v1.16.0rc2

### PR DESCRIPTION
**Pull request by shefty**
Signed-off-by: Sean Hefty <sean.hefty@intel.com>

Once merged, I will create the v1.16.x branch

### CODE REVIEW

**Comment by zachdworkin** [comment]
@shefty the ci fail is my fault, ill run it again for you when it finishes this run

**Comment by wzamazon** [comment]
bot:aws:retest

**Comment by wzamazon** [comment]
bot:aws:retest

**Comment by shefty** [comment]
I pulled in the wrong patch for the verbs fix, updating.

**Pull request merged**
