### PR TITLE
hmem: Fix rocr_is_addr_valid() check for AMD GPU memory

### PR DESCRIPTION
**Pull request by lradeke**
rocr_is_addr_valid() should only return true if hsa_agent_get_info() says the
agent is HSA_DEVICE_TYPE_GPU.

Signed-off-by: Leena Radeke <leena.radeke@hpe.com>

### CODE REVIEW

**Review by shefty — APPROVED** [review]
@iziemba - These changes look okay to me, but I'm not familiar with RoCR.

**Comment by iziemba** [comment]
Changes look good. Please wait for cray CI to finish before merging.

**Comment by shefty** [comment]
How or when does the cray CI start?

**Comment by iziemba** [comment]
If the cray-jenkins-build label is attached to the PR, it is suppose to run the PR through our CI. We have been working on reducing our PR testing duration to allow our CI to run for each OFIWG PR. I'm not sure were this is at.

The reason why our CI didn't run with the label is due to Jenkins credential issues :(

**Comment by jswaro** [comment]
@iziemba , @lradeke : You'll need to test this by hand. Credentials are broken for the testing account at the moment. Once you've verified the build, please post a result of some sort to this thread.

**Comment by shefty** [comment]
Is this PR good to merge?

**Comment by lradeke** [comment]
> Is this PR good to merge?

Yup, the build was tested with the CI internally and passed. I'll merge the PR shortly.

**Pull request merged**
