### PR TITLE
util: Move FI_REMOTE/LOCAL_COMM to secondary caps

### PR DESCRIPTION
**Pull request by iziemba**
API defines FI_REMOTE_COMM and FI_LOCAL_COMM as secondary caps. Fix this misclassification.

### CODE REVIEW

**Review by j-xiong — APPROVED** [review]

**Comment by wenduwan** [comment]
bot:aws:retest

**Comment by wenduwan** [comment]
bot:aws:retest

**Comment by j-xiong** [comment]
Intel CI failure is unrelated:
```
18:03:57  	tcp mpich mpichtestsuite reg : cb[21-22] : [rocky87,icx,hdr] : 882:883 : 99.89% :  Pass :   42 : Excluded/Notrun
18:03:57  		Failed tests: 1
18:03:57  			./rma/win_shared_put_flush_load 3
```

**Comment by wenduwan** [comment]
bot:aws:retest

**Comment by iziemba** [comment]
Rebased on main.

**Pull request merged**
