### PR TITLE
[v1.19.x] Backport prov/efa: fix efa device name matching

### PR DESCRIPTION
**Pull request by wenduwan**
This patch fixes a bug in EFA device name matching logic, which only accounts for the first prefix match. As a result, efa_10-rdm domain name is matched with efa_1 device instead of efa_10.

Signed-off-by: Wenduo Wang <wenduwan@amazon.com>
(cherry picked from commit 9961ccf2336d1f354f102f1c9b2c3a1305a7db6c)

### CODE REVIEW

**Review by shijin-aws — APPROVED** [review]

**Comment by wenduwan** [comment]
bot:aws:retest

**Comment by shijin-aws** [comment]
bot:aws:retest

**Comment by shijin-aws** [comment]
bot:aws:retest

**Comment by shijin-aws** [comment]
bot:aws:retest

**Pull request merged**
