### PR TITLE
include,src/hmem: deprecate redundant synapseai hmem ops

### PR DESCRIPTION
**Pull request by wenduwan**
Replace redundant synapseai hmem ops with ofi hmem functions

Signed-off-by: Wenduo Wang <wenduwan@amazon.com>

### CODE REVIEW

**Review by wzamazon — APPROVED** [review]

**Comment by wzamazon** [comment]
@shefty Is "continuous-integration/jenkins/pr-head" error need looking into?

**Review by shijin-aws — APPROVED** [review]

**Comment by shijin-aws** [comment]
The change is good. But the commit message: `no-op` just means do nothing, which usually means return FI_SUCCESS. ENOSYS are not no-op.

**Comment by shefty** [comment]
shm failed with ubertest.  I restarted to see if it repeats.

**Comment by shefty** [comment]
I don't see how the shm failure is related to this PR though.

**Comment by wenduwan** [comment]
> The change is good. But the commit message: no-op just means do nothing, which usually means return FI_SUCCESS. ENOSYS are not no-op.

Ack. Reworded commit message.

**Comment by wenduwan** [comment]
bot:aws:retest

**Pull request merged**
