### PR TITLE
Verbs provider. EP_RDM bugfix.

### PR DESCRIPTION
**Pull request by evgeny-leksikov**
- fix buffered rma write and data types
- add FI_COMPLETION to verbs_rdm_rx_attr.op_flags (**update:** removed from this PR)

@shefty @a-ilango, please look at 	https://github.com/ofiwg/libfabric/commit/9e7aafe1f6d1e562980efbba2bbcb7816cded4e7, is this correct to initialize rx_attr.op_flags with FI_COMPLETION?

### CODE REVIEW

**Comment by a-ilango** [comment]
AFAIK whether rx_attr.op_flags is set to FI_COMPLETION would matter only when FI_SELECTIVE_COMPLETION is set when binding an EP to a CQ. Otherwise completions should be generated by default for all non-inject calls (see example # 3 under fi_ep_bind -> FI_SELECTIVE_COMPLETION in fi_endpoint man page). So I think it is not necessary to set rx_attr.op_flags to FI_COMPLETION and the app would have to set this to correct flags when using selective completion.

**Comment by evgeny-leksikov** [comment]
@a-ilango, got it, thanks! I reverted corresponding commit to make this PR free to merge. Completion logic and flags will be implemented in other PR.

**Comment by evgeny-leksikov** [comment]
BTW, as FI_COMPLETION is a "default" mode, an application is able to request it by hints->rx_attr->op_flags. Now, verbs provider return FI_ENODATA in this case, so as I understand this is an error.

**Comment by a-ilango** [comment]
Yes, that would be an error. It seems we might need different flags for checking and setting them when returning fi_info. I guess other providers would have a similar issue as well. The ideal fix would be to fix this in util provider's fi_check_info logic and make verbs provider use it. I can take a look at this.

**Pull request merged**
