### PR TITLE
Create build.yml

### PR DESCRIPTION
**Pull request by shefty**
Use github action to build main, as a possible replacement for Travis CI.

Signed-off-by: Sean Hefty <sean.hefty@intel.com>

### CODE REVIEW

**Comment by shefty** [comment]
I used the github web tools + C/C++ build template to construct this.  Let's see if this works and what it actually does.  I'm hoping it builds main on ubuntu and reports the results.  Next step would be to see how much of the CI can it actually run.

**Comment by raghupazl** [comment]
Needs to go under `.github/workflow/` for it to get picked up.

**Comment by rajachan** [comment]
Needs to go under `.github/workflow` for it to get picked up.

**Comment by shefty** [comment]
Okay - when going through the tool, it showed it going in that location.  I have no idea why the PR decided to put it at the root.

**Comment by jsquyres** [comment]
@shefty You might want to make a `do_the_build.sh` script and invoke that (vs. having a bunch of independent tasks), similar to how the Nroff Elves do it (the Elves .yaml file invokes the Elves .sh file).

Or you could combine all those multiple steps into:

```yaml
    - name: Configure and build
      run: |
          ./configure
          make
          make check
          make distcheck

**Comment by shefty** [comment]
@jsquyres - I didn't actually write this, it was generated for me from a template.  What's the advantage of moving this into a .sh versus just having the .yaml file?  Just for more flexibility on what we can do?

Btw, we'll eventually want this to pull in libibverbs, etc. to build more providers.

**Comment by jsquyres** [comment]
> @jsquyres - I didn't actually write this, it was generated for me from a template. What's the advantage of moving this into a .sh versus just having the .yaml file? Just for more flexibility on what we can do?

Yeah.  If you have more than a handful of commands to execute, and/or have any type of non-sequential logic, the formatting in the YAML file becomes a pain, and becomes a barrier to people who want to maintain the tests.

IMHO, it's better to put in the YAML only what needs to be in the YAML, and have the heavy lifting of the actual work to run the build / tests / etc. in a standalone file that any Linux scripting dev can easily understand/edit/maintain.  Just my $0.02.

Check out https://github.com/ofiwg/libfabric/blob/main/.github/workflows/nroff-elves.yaml vs. https://github.com/ofiwg/libfabric/blob/main/.github/workflows/nroff-elves.sh.  It's not exactly the same comparison because the Nroff Elves do quite a bit of conditional logic (which would be... ugly in the YAML file), but you get the idea.

> Btw, we'll eventually want this to pull in libibverbs, etc. to build more providers.

👍

**Comment by shefty** [comment]
Do not merge - leaving open as a reference.

**Comment by shefty** [comment]
gah - the wizards created extra goofy branches in the upstream tree... sigh... will delete later

**Pull request closed without merging**
