### PR TITLE
Make fi_log exported functions part of 1.0 ABI.

### PR DESCRIPTION
**Pull request by pmmccorm**
Signed-off-by: pmmccorm <patrick.m.mccormick@intel.com>

### CODE REVIEW

**Comment by jsquyres** [comment]
Just curious -- what's this for?  Do we want applications to be able to call fi_log()?

**Comment by pmmccorm** [comment]
out-of-tree providers should only use this.

**Comment by hppritcha** [comment]
Just curious, have you verified that the logging mechanism is working with out-of-tree providers?  It ought to but I don't know if anyone's verified that it works.

**Comment by pmmccorm** [comment]
Just tested it: doesn't work when providers are built =dl:

```
 FI_LOG_LEVEL=9 ./simple/fi_info
libfabric:core:core:fi_ini_dir():324<warn> dlopen(lib/libfabric/libverbs-fi.so): lib/libfabric/libverbs-fi.so: undefined symbol: fi_create_filter
libfabric:core:core:fi_ini_dir():324<warn> dlopen(lib/libfabric/libpsmx-fi.so): lib/libfabric/libpsmx-fi.so: undefined symbol: fi_create_filter
```

**Comment by shefty** [comment]
It looks like we need to separate fi_log.c into what the provider needs, versus what the framework requires. Maybe move fi_log and fi_log_enabled into common.c?

**Comment by pmmccorm** [comment]
Working on it.

**Comment by shefty** [comment]
These changes are correct, just not sufficient to make everything work.  Merging this in and letting other patches fix the rest of the issues.

**Pull request merged**
