### PR TITLE
v1.15.0

### PR DESCRIPTION
**Pull request by shefty**

### CODE REVIEW

**Comment by zachdworkin** [comment]
@shefty you are using the old jenkinsfile pipeline for this job.

Did you mean to do that?

**Comment by shefty** [comment]
I'm using whatever is in the tip of the v1.15.x branch.

**Comment by shefty** [comment]
AppVeyor error was one setup failing to access the git tree.

**Comment by j-xiong** [comment]
There are already two verbs failures with Intel CI. Are these just temporary resource contentions or something to be concerned? 
```
20:13:53  - name:   fi_av_xfer -e rdm -p "verbs;ofi_rxm"
20:13:53    result: Fail
20:13:53    time:   4
20:13:53    server_cmd: /home/cstbuild/ofi-Install/libfabric/ofi_libfabric/PR-7718/11/reg/bin/fi_av_xfer -e rdm -p "verbs;ofi_rxm"   -s ci3-ib0
20:13:53    server_stdout: |
20:13:53      bind: Address already in use
20:13:53      AV address removal: FAIL
20:13:53    client_cmd: /home/cstbuild/ofi-Install/libfabric/ofi_libfabric/PR-7718/11/reg/bin/fi_av_xfer -e rdm -p "verbs;ofi_rxm"   -s ci4-ib0 ci3-ib0
20:13:53    client_stdout: |
20:13:53      AV address removal: PASS
20:13:53      AV re-insertion address: PASS
```
```
20:17:05  - name:   fi_bw -e rdm -v -T 1 -U -p "verbs;ofi_rxm"
20:17:05    result: Fail
20:17:05    time:   158
20:17:05    server_cmd: /home/cstbuild/ofi-Install/libfabric/ofi_libfabric/PR-7718/11/reg/bin/fi_bw -e rdm -v -T 1 -U -p "verbs;ofi_rxm"   -s ci3-ib0
20:17:05    server_stdout: |
20:17:05      fi_enable(): common/shared.c:1249, ret=-12 (Cannot allocate memory)
20:17:05    client_cmd: /home/cstbuild/ofi-Install/libfabric/ofi_libfabric/PR-7718/11/reg/bin/fi_bw -e rdm -v -T 1 -U -p "verbs;ofi_rxm"   -s ci4-ib0 ci3-ib0
20:17:05    client_stdout: |
20:17:05      transmit(): common/shared.c:1916, ret=-12 (Cannot allocate memory)
```

**Comment by shefty** [comment]
See #7711.  I think those failures are related to the systems being flaky in their reporting of IPv6 address.  In debugging OMPI those were the same error messages that would show up when MPI ended up mismatching IPv6 and IPv4 addresses.

**Comment by shefty** [comment]
Verbs tests passed after re-running CI.  MPI had 2 failures, which both show up as unable to allocate memory.  Previous debugging showed that can occur when mixing ipv6 with ipv4 addresses.  (A failure lower down results in a function returning null, which gets interpreted as ENOMEM).

**Comment by shefty** [comment]
Re-ran CI, uhm, we're at run 14 now.  Verbs has passed fine last 2 times.  MPI has various failures mixed in with successful runs, but has never succeeded on verbs.  Failures are always cannot allocate memory.

**Comment by shefty** [comment]
I knew if I ran the CI 15 times, it would eventually pass.

**Pull request merged**
