### PR TITLE
v1.19.x

### PR DESCRIPTION
**Pull request by shefty**

### CODE REVIEW

**Comment by shefty** [comment]
@shijin-aws @darrylabbate - Can someone from AWS provide a list of items to capture in the NEWS.md file?  I can update the file; I just need the list.

**Comment by darrylabbate** [comment]
ACK, we'll work on getting this ASAP. Is there a date you'd like it by, ideally?

**Comment by darrylabbate** [comment]
Also, should our changelog reflect changes since v1.18.0 or v1.18.2?

**Comment by shefty** [comment]
Ideally, I'd like the update by 9/1 - tomorrow.  The change should include anything from v1.18.0 on, but does NOT need to include changes that went into v1.18.1 or v1.18.2.  Those changes are already included in the NEWS file.  (If they do get duplicated, oh well, not a big deal.)

**Comment by shijin-aws** [comment]
Libfabric 1.19.x efa news

* Onboard Peer API, use shm provider as a peer provider
* Uses util SRX framework in shared receive procedures.
* Register shm MR with hmem_data, allow shm to use gdrcopy for cuda data movement.
* Finish the refactor for rxr squash.
* Use rdma-core WR API for send requests.
* Check optlen in getopt call
* Fix the rdma-read support check in RMA and MSG operations
* Optimize ep lock usage
* Modify how EFA selects intranode provider
* Use an internal fi_mr_attr for memory registration

**Comment by shefty** [comment]
@shijin-aws - thanks - I added that to the NEWS and updated the PR.  Working through the release cycle now.

**Comment by shijin-aws** [comment]
We are adding a new change to main and backporting to v1.19.x. But the news should be good. Thanks!

**Comment by shefty** [comment]
Picked commit from #9275 and retesting.

**Pull request merged**
