### PR TITLE
man/domain: Clarify when FI_LOCAL_MR is ignored

### PR DESCRIPTION
**Pull request by shefty**
Signed-off-by: Sean Hefty <sean.hefty@intel.com>

### CODE REVIEW

**Comment by shefty** [comment]
@bturrubiates @thananon - does this update help?

**Comment by shefty** [comment]
AppVeyor is apparently unable to build PRs that only contain man page updates.

**Comment by bturrubiates** [comment]
> @bturrubiates @thananon - does this update help?

Yeah, I think that clarifies things for me.

**Comment by thananon** [comment]
> @bturrubiates @thananon - does this update help?
Yes, this looks good. Thank you.

**Pull request merged**
