### PR TITLE
Update librdmacm git dependency to point at the Github mirror.

### LINKED ISSUE #1773: Travis build on Linux broken
```bash
if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    git clone git://www.openfabrics.org/~shefty/librdmacm.git
fi

Cloning into 'librdmacm'...
fatal: unable to connect to www.openfabrics.org:
www.openfabrics.org[0: 69.55.231.73]: errno=Connection refused
```

@shefty Is `librdmacm` still located  there?

### PR DESCRIPTION
**Pull request by bturrubiates**
Closes #1773.

Signed-off-by: Ben Turrubiates <bturrubi@cisco.com>

### CODE REVIEW

**Comment by bturrubiates** [comment]
I'll merge once the PR is verified by Travis.

**Comment by shefty** [comment]
thanks

**Comment by bturrubiates** [comment]
Is the signed off checker also not running for the same reason? I think it ran on flatbed.

**Comment by shefty** [comment]
Yes, flatbed was hacked and is being upgraded.  I don't think it will be fully operational until later this week.

**Comment by bturrubiates** [comment]
> Yes, flatbed was hacked and is being upgraded.  I don't think it will be fully operational until later this week.

Okay, merging this. We can probably do without the signed off checker for a bit.

**Pull request merged**
