### PR TITLE
 [v1.7.x] prov/rxm: cherry-picked fixes / improvements

### PR DESCRIPTION
**Pull request by a-ilango**
Some smaller commits were picked to avoid some of the merge conflicts.

### CODE REVIEW

**Comment by shefty** [comment]
Is this commit list correct?  This is a lot of commits at once to add to a stable branch so soon after it was released.

**Comment by a-ilango** [comment]
Yes, the list is lengthy. It's a mix of commits missed to add to v1.7.1 + commits that fixed issues after v1.7.1 + smaller commits to avoid merge conflicts. There would be a v1.7.2 in the future, no?

**Comment by shefty** [comment]
Yes, we can do a 1.7.2 release at some point.  I was just wanting to verify the list in case there was some sort of rebase or merge error.

**Comment by a-ilango** [comment]
There were some merge conflicts along the way. I can probably drop a commit or two that are not essential.

**Comment by swelch** [comment]
I will need to add the changes from PR4922 to v1.7.x as well, but can wait until this PR is resolved unless it helps with the conflicts.

**Comment by a-ilango** [comment]
> I will need to add the changes from PR4922 to v1.7.x as well, but can wait until this PR is resolved unless it helps with the conflicts.

Those are verbs provider changes. Please open a PR for them, no need to wait.

**Comment by swelch** [comment]
>
> Those are verbs provider changes. Please open a PR for them, no need to wait.

Doh! :-) Will do.

**Comment by a-ilango** [comment]
I've reduced the # of commits. This PR now has only those commits that don't have merge conflicts. Let me do the cherry-picks in bite sized PRs.

**Comment by a-ilango** [comment]
Ignoring one resource leak issue that Intel CI reports and merging this. A follow-up cherry-pick PR should fix that issue.

**Pull request merged**
